// اسم‌های دیگه (عمدتا انگلیسی) برای 149 حرکت اولیه — جدا از legacy.ts تا
// خود ورودی‌ها و اسم‌هاشون دست‌نخورده بمونن. برای جستجو و تطبیق اسم AI.

import type { ExerciseEquipment } from "../exerciseCatalogMeta";

// تجهیزات حرکات اولیه‌ای که ابزارشون توی اسم نیومده (تشخیص خودکار از روی
// اسم براشون «وزن بدن» درمیومد).
export const LEGACY_EQUIPMENT: Record<string, ExerciseEquipment> = {
  "اسکوات گابلت": "dumbbell",
  "اسکوات پا جلو": "barbell",
  "هیپ تراست": "barbell",
  "هایپراکستنشن": "machine",
  "ساق پا نشسته": "machine",
  "ساق پا خم": "machine",
  "زیربغل لت": "cable",
  "پول‌اور": "dumbbell",
  "پرس آرنولد": "dumbbell",
  "نشر جانبی": "dumbbell",
  "نشر خم به جلو": "dumbbell",
  "جلوبازو لاری": "barbell",
  "جلوبازو چکشی": "dumbbell",
  "جلوبازو کانسنتریشن": "dumbbell",
  "جلوبازو روی نیمکت شیب‌دار": "dumbbell",
  "کیک‌بک پشت بازو": "dumbbell",
  "مچ دست معکوس": "barbell",
  "پلانک بارگذاری‌شده": "other",
  "باکس اسکوات": "barbell",
  "گابلت لانج": "dumbbell",
  "کیک‌بک باسن": "cable",
  "آپ‌رایت رو": "barbell",
  "فارمر واک": "dumbbell",
  "چرخ شکم": "other",
  "طناب زدن": "other",
  "طناب‌زنی سنگین (بتل‌روپ)": "other",
  "شنا (استخر)": "other",
  "پرس سینه دست جمع": "barbell",
  "پرس سینه دکلاین": "barbell",
};

export const LEGACY_ALIASES: Record<string, string[]> = {
  "اسکوات هالتر": ["Barbell Back Squat", "Back Squat", "Squat"],
  "اسکوات گابلت": ["Goblet Squat"],
  "اسکوات پا جلو": ["Front Squat", "فرانت اسکوات"],
  "اسکوات وزن بدن": ["Bodyweight Squat", "Air Squat"],
  "اسکوات سومو": ["Sumo Squat"],
  "هاک اسکوات": ["Hack Squat"],
  "لانج با دمبل": ["Dumbbell Lunge"],
  "لانج بلغاری": ["Bulgarian Split Squat"],
  "لانج": ["Lunge", "Forward Lunge"],
  "ددلیفت": ["Deadlift", "Conventional Deadlift", "Barbell Deadlift"],
  "ددلیفت رومانیایی": ["Romanian Deadlift", "RDL", "Barbell RDL"],
  "ددلیفت سومو": ["Sumo Deadlift"],
  "ددلیفت تک‌پا": ["Single-Leg Deadlift"],
  "هیپ تراست": ["Hip Thrust"],
  "هیپ تراست هالتر": ["Barbell Hip Thrust"],
  "هایپراکستنشن": ["Back Extension", "Hyperextension"],
  "پرس پا": ["Leg Press"],
  "لگ اکستنشن": ["Leg Extension", "جلو پا دستگاه"],
  "لگ کرل": ["Leg Curl", "پشت پا دستگاه"],
  "ساق پا ایستاده": ["Standing Calf Raise"],
  "ساق پا نشسته": ["Seated Calf Raise"],
  "ساق پا": ["Calf Raise"],
  "پرس سینه هالتر": ["Barbell Bench Press", "Bench Press"],
  "پرس سینه دمبل": ["Dumbbell Bench Press"],
  "پرس سینه اسمیت": ["Smith Machine Bench Press"],
  "پرس شیب‌دار دمبل": ["Incline Dumbbell Press", "پرس بالا سینه دمبل"],
  "پرس شیب‌دار هالتر": ["Incline Barbell Bench Press", "Incline Bench Press", "پرس بالا سینه هالتر"],
  "فلای دمبل": ["Dumbbell Fly", "قفسه سینه دمبل"],
  "فلای سیم‌کش": ["Cable Fly"],
  "شنا سوئدی": ["Push Up", "Push-up", "شنا"],
  "شنا سوئدی روی زانو": ["Knee Push Up"],
  "دیپ": ["Dip", "Dips", "Parallel Bar Dip"],
  "دیپ وزنه‌دار": ["Weighted Dip"],
  "زیربغل هالتر خم": ["Bent Over Barbell Row", "Barbell Row"],
  "زیربغل تک‌دست دمبل": ["One-Arm Dumbbell Row", "Single-Arm Dumbbell Row", "Dumbbell Row"],
  "زیربغل تی-بار": ["T-Bar Row"],
  "زیربغل سیمکش": ["Seated Cable Row", "قایقی"],
  "زیربغل لت": ["Lat Pulldown", "لت از جلو"],
  "پول‌اور": ["Pullover"],
  "بارفیکس": ["Pull Up", "Pull-up"],
  "بارفیکس وزنه‌دار": ["Weighted Pull Up"],
  "کول‌آپ کمکی": ["Assisted Chin Up"],
  "پرس سرشانه هالتر": ["Overhead Press", "Military Press", "Barbell Shoulder Press", "پرس سرشانه ایستاده"],
  "پرس سرشانه دمبل": ["Dumbbell Shoulder Press", "Seated Dumbbell Press"],
  "پرس آرنولد": ["Arnold Press"],
  "نشر جانبی دمبل": ["Dumbbell Lateral Raise", "Lateral Raise", "Side Raise"],
  "نشر جانبی سیم‌کش": ["Cable Lateral Raise"],
  "نشر خم به جلو": ["Bent Over Reverse Fly", "Rear Delt Raise"],
  "فیس‌پول": ["Face Pull"],
  "شراگ هالتر": ["Barbell Shrug", "Shrug"],
  "شراگ دمبل": ["Dumbbell Shrug"],
  "جلوبازو دمبل": ["Dumbbell Curl", "Bicep Curl"],
  "جلوبازو هالتر": ["Barbell Curl"],
  "جلوبازو لاری": ["Preacher Curl"],
  "جلوبازو چکشی": ["Hammer Curl"],
  "جلوبازو سیم‌کش": ["Cable Curl"],
  "پشت‌بازو سیمکش": ["Tricep Pushdown", "Cable Pushdown", "پشت بازو سیم‌کش"],
  "پشت بازو هالتر خوابیده": ["Skull Crusher", "Lying Triceps Extension"],
  "پشت بازو دمبل تک‌دست": ["Overhead Dumbbell Triceps Extension", "پشت بازو دمبل بالای سر"],
  "پشت بازو روی نیمکت": ["Bench Dip"],
  "مچ دست هالتر": ["Barbell Wrist Curl", "Wrist Curl"],
  "پلانک": ["Plank", "Forearm Plank"],
  "پلانک جانبی": ["Side Plank"],
  "کرانچ": ["Crunch"],
  "کرانچ سیم‌کش": ["Cable Crunch"],
  "زانو بغل معلق": ["Hanging Knee Raise"],
  "راشین تویست": ["Russian Twist"],
  "برپی": ["Burpee"],
  "پرش جعبه": ["Box Jump"],
  "اسکوات جامپ": ["Jump Squat", "Squat Jump"],
  "طناب زدن": ["Jump Rope", "Skipping"],
  "دویدن آرام": ["Jogging", "Easy Run"],
  "دوچرخه ثابت": ["Stationary Bike", "Exercise Bike"],
  "کشش کامل بدن": ["Full Body Stretch"],
  "باکس اسکوات": ["Box Squat"],
  "لانج معکوس": ["Reverse Lunge"],
  "لانج پیاده‌روی": ["Walking Lunge"],
  "استپ آپ": ["Step Up"],
  "سیسی اسکوات": ["Sissy Squat"],
  "گود مورنینگ": ["Good Morning"],
  "پول-ترو سیم‌کش": ["Cable Pull Through"],
  "کیک‌بک باسن": ["Glute Kickback"],
  "هیپ اداکشن دستگاه": ["Hip Adduction Machine", "Adductor Machine", "دستگاه ران داخلی"],
  "هیپ ابداکشن دستگاه": ["Hip Abduction Machine", "Abductor Machine", "دستگاه ران خارجی"],
  "پرس پا تک‌پا": ["Single-Leg Leg Press"],
  "پرس سینه دستگاه": ["Machine Chest Press"],
  "پک دک (فلای دستگاه)": ["Pec Deck", "Machine Fly", "پک دک"],
  "پرس سینه شیب‌دار دستگاه": ["Incline Machine Press"],
  "فلای دمبل شیب‌دار": ["Incline Dumbbell Fly"],
  "کراس‌اور سیم‌کش": ["Cable Crossover"],
  "زیربغل دستگاه نشسته": ["Seated Machine Row"],
  "پول‌داون نزدیک": ["Close Grip Pulldown"],
  "رک پول": ["Rack Pull"],
  "پرس سرشانه دستگاه": ["Machine Shoulder Press"],
  "پرس سرشانه اسمیت": ["Smith Machine Shoulder Press"],
  "نشر جانبی دستگاه": ["Machine Lateral Raise"],
  "آپ‌رایت رو": ["Upright Row", "کول هالتر"],
  "پرس لندماین": ["Landmine Press"],
  "جلوبازو کانسنتریشن": ["Concentration Curl", "جلوبازو تمرکزی"],
  "جلوبازو روی نیمکت شیب‌دار": ["Incline Dumbbell Curl"],
  "جلوبازو دستگاه": ["Machine Bicep Curl"],
  "پشت بازو دستگاه": ["Machine Triceps Extension"],
  "کیک‌بک پشت بازو": ["Dumbbell Kickback", "Triceps Kickback"],
  "مچ دست معکوس": ["Reverse Wrist Curl"],
  "فارمر واک": ["Farmer's Walk", "Farmer Carry"],
  "کوهنورد": ["Mountain Climber"],
  "چرخ شکم": ["Ab Wheel Rollout", "Ab Rollout"],
  "دد باگ": ["Dead Bug"],
  "بردباره": ["Plank Shoulder Tap", "پلانک شانه زدن"],
  "قایقی (روئینگ) دستگاه": ["Rowing Machine", "Rower", "Erg"],
  "الپتیکال": ["Elliptical"],
  "پله‌نوردی": ["Stair Climber", "Stairmaster"],
  "شنا (استخر)": ["Swimming"],
  "طناب‌زنی سنگین (بتل‌روپ)": ["Battle Ropes", "بتل روپ"],
  "کتل‌بل سوئینگ": ["Kettlebell Swing"],
  "جامپینگ جک": ["Jumping Jacks"],
  "های‌نیز": ["High Knees"],
  "کشش همسترینگ نشسته": ["Seated Hamstring Stretch"],
  "کشش چهارسر ایستاده": ["Standing Quad Stretch"],
  "کبوتر (یوگا)": ["Pigeon Pose", "کبوتر"],
  "کشش سرشانه پشت بدن": ["Cross Body Shoulder Stretch"],
  "فوم رولینگ": ["Foam Rolling"],
  "پرس سینه دست جمع": ["Close Grip Bench Press"],
  "پرس سینه دکلاین": ["Decline Bench Press"],
  "اسکوات تک‌پا": ["Single-Leg Squat"],
  "پروانه معکوس دمبل": ["Reverse Dumbbell Fly"],
  "پروانه معکوس دستگاه": ["Reverse Pec Deck", "Rear Delt Machine"],
  "دراز و نشست": ["Sit Up"],
  "بالا آوردن پا خوابیده": ["Lying Leg Raise", "Leg Raise"],
  "کرانچ معکوس": ["Reverse Crunch"],
};
