// GENERATED by mobile/tooling/prismaShim.mjs from prisma/schema.prisma — do not edit.
// shimِ @prisma/client برای باندلِ کلاینتِ اپ موبایل (بدونِ query engine).
/* eslint-disable */

export const Market = {
  IRAN: "IRAN",
  INTERNATIONAL: "INTERNATIONAL",
} as const;
export type Market = (typeof Market)[keyof typeof Market];

export const Currency = {
  IRR: "IRR",
  USD: "USD",
} as const;
export type Currency = (typeof Currency)[keyof typeof Currency];

export const AiModel = {
  HAIKU: "HAIKU",
  SONNET: "SONNET",
} as const;
export type AiModel = (typeof AiModel)[keyof typeof AiModel];

export const ModuleKey = {
  ROUTINE: "ROUTINE",
  SLEEP: "SLEEP",
  TASKS: "TASKS",
  EXERCISE: "EXERCISE",
  CALORIE: "CALORIE",
  TRADE: "TRADE",
  ROADMAP: "ROADMAP",
  AI_INSIGHT: "AI_INSIGHT",
} as const;
export type ModuleKey = (typeof ModuleKey)[keyof typeof ModuleKey];

export const SubscriptionStatus = {
  TRIAL: "TRIAL",
  ACTIVE: "ACTIVE",
  PAST_DUE: "PAST_DUE",
  CANCELED: "CANCELED",
  EXPIRED: "EXPIRED",
} as const;
export type SubscriptionStatus = (typeof SubscriptionStatus)[keyof typeof SubscriptionStatus];

export const BillingInterval = {
  MONTHLY: "MONTHLY",
  YEARLY: "YEARLY",
} as const;
export type BillingInterval = (typeof BillingInterval)[keyof typeof BillingInterval];

export const ReferralUsageStatus = {
  PENDING: "PENDING",
  REWARDED: "REWARDED",
  REVOKED: "REVOKED",
} as const;
export type ReferralUsageStatus = (typeof ReferralUsageStatus)[keyof typeof ReferralUsageStatus];

export const PartnerType = {
  GYM: "GYM",
  OTHER: "OTHER",
} as const;
export type PartnerType = (typeof PartnerType)[keyof typeof PartnerType];

export const FriendshipStatus = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
} as const;
export type FriendshipStatus = (typeof FriendshipStatus)[keyof typeof FriendshipStatus];

export const AiFeatureKey = {
  DAILY_BRIEFING: "DAILY_BRIEFING",
  WEEKLY_COACH_REPORT: "WEEKLY_COACH_REPORT",
  CORRELATION_INSIGHT: "CORRELATION_INSIGHT",
  ROADMAP_GENERATION: "ROADMAP_GENERATION",
  EXERCISE_PLAN_GENERATION: "EXERCISE_PLAN_GENERATION",
  FOOD_SCAN: "FOOD_SCAN",
  ROUTINE_ASSISTANT: "ROUTINE_ASSISTANT",
} as const;
export type AiFeatureKey = (typeof AiFeatureKey)[keyof typeof AiFeatureKey];

export const ErrorSeverity = {
  WARNING: "WARNING",
  ERROR: "ERROR",
  CRITICAL: "CRITICAL",
} as const;
export type ErrorSeverity = (typeof ErrorSeverity)[keyof typeof ErrorSeverity];

export const TradeAccountType = {
  REAL: "REAL",
  DEMO: "DEMO",
  PROP: "PROP",
  BACKTEST: "BACKTEST",
} as const;
export type TradeAccountType = (typeof TradeAccountType)[keyof typeof TradeAccountType];

export const TradeGoalType = {
  AMOUNT: "AMOUNT",
  PERCENT: "PERCENT",
} as const;
export type TradeGoalType = (typeof TradeGoalType)[keyof typeof TradeGoalType];

export const TradeDirection = {
  BUY: "BUY",
  SELL: "SELL",
} as const;
export type TradeDirection = (typeof TradeDirection)[keyof typeof TradeDirection];

export const TradeStatus = {
  OPEN: "OPEN",
  CLOSED: "CLOSED",
  CANCELED: "CANCELED",
} as const;
export type TradeStatus = (typeof TradeStatus)[keyof typeof TradeStatus];

export const TradeResult = {
  PROFIT: "PROFIT",
  LOSS: "LOSS",
  BREAKEVEN: "BREAKEVEN",
} as const;
export type TradeResult = (typeof TradeResult)[keyof typeof TradeResult];

export const TradeSession = {
  SYDNEY: "SYDNEY",
  TOKYO: "TOKYO",
  LONDON: "LONDON",
  NEWYORK: "NEWYORK",
} as const;
export type TradeSession = (typeof TradeSession)[keyof typeof TradeSession];

export const TradeEntryReason = {
  STRATEGY: "STRATEGY",
  TECHNICAL_SIGNAL: "TECHNICAL_SIGNAL",
  FUNDAMENTAL_SIGNAL: "FUNDAMENTAL_SIGNAL",
  NEWS: "NEWS",
  INTUITION: "INTUITION",
  OTHERS_ADVICE: "OTHERS_ADVICE",
  FOMO: "FOMO",
  REVENGE: "REVENGE",
  OTHER: "OTHER",
} as const;
export type TradeEntryReason = (typeof TradeEntryReason)[keyof typeof TradeEntryReason];

export const TradeExitReason = {
  TAKE_PROFIT: "TAKE_PROFIT",
  STOP_LOSS: "STOP_LOSS",
  MANUAL: "MANUAL",
  TRAILING_STOP: "TRAILING_STOP",
  MARKET_CHANGE: "MARKET_CHANGE",
  EMOTIONAL: "EMOTIONAL",
  TIME_BASED: "TIME_BASED",
  OTHER: "OTHER",
} as const;
export type TradeExitReason = (typeof TradeExitReason)[keyof typeof TradeExitReason];

export const TradeEmotionBefore = {
  CALM: "CALM",
  NEUTRAL: "NEUTRAL",
  EXCITED: "EXCITED",
  ANXIOUS: "ANXIOUS",
  ANGRY: "ANGRY",
  OVERCONFIDENT: "OVERCONFIDENT",
} as const;
export type TradeEmotionBefore = (typeof TradeEmotionBefore)[keyof typeof TradeEmotionBefore];

export const TradeEmotionAfter = {
  SATISFIED: "SATISFIED",
  RELIEVED: "RELIEVED",
  INDIFFERENT: "INDIFFERENT",
  ANXIOUS: "ANXIOUS",
  REGRET: "REGRET",
  ANGRY: "ANGRY",
} as const;
export type TradeEmotionAfter = (typeof TradeEmotionAfter)[keyof typeof TradeEmotionAfter];

export const MtPlatform = {
  MT4: "MT4",
  MT5: "MT5",
} as const;
export type MtPlatform = (typeof MtPlatform)[keyof typeof MtPlatform];

export const EconomicImpact = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
} as const;
export type EconomicImpact = (typeof EconomicImpact)[keyof typeof EconomicImpact];

export const TradeChatReportReason = {
  SPAM: "SPAM",
  ABUSE: "ABUSE",
  SCAM: "SCAM",
  OFFTOPIC: "OFFTOPIC",
  OTHER: "OTHER",
} as const;
export type TradeChatReportReason = (typeof TradeChatReportReason)[keyof typeof TradeChatReportReason];

export const TradeChatReportStatus = {
  OPEN: "OPEN",
  ACTIONED: "ACTIONED",
  DISMISSED: "DISMISSED",
} as const;
export type TradeChatReportStatus = (typeof TradeChatReportStatus)[keyof typeof TradeChatReportStatus];

export const SupportTicketStatus = {
  OPEN: "OPEN",
  ANSWERED: "ANSWERED",
  CLOSED: "CLOSED",
} as const;
export type SupportTicketStatus = (typeof SupportTicketStatus)[keyof typeof SupportTicketStatus];

export type User = any;
export type OAuthAccount = any;
export type Session = any;
export type LoginEvent = any;
export type PasswordResetOtp = any;
export type TwoFactorOtp = any;
export type SignupOtp = any;
export type EmailLoginOtp = any;
export type EmailChangeOtp = any;
export type Plan = any;
export type PlanModule = any;
export type Subscription = any;
export type Payment = any;
export type ModuleAccess = any;
export type ReferralCode = any;
export type ReferralUsage = any;
export type DiscountCode = any;
export type DiscountCodeUsage = any;
export type Partner = any;
export type AiUsageRecord = any;
export type AiMonthlyQuota = any;
export type RoutineItem = any;
export type DailyEntry = any;
export type Friendship = any;
export type FriendStar = any;
export type UserBlock = any;
export type SleepEntry = any;
export type Task = any;
export type ExercisePlan = any;
export type ExerciseLog = any;
export type ExerciseMedia = any;
export type FoodItem = any;
export type FoodLogEntry = any;
export type CalorieTarget = any;
export type TradeAccount = any;
export type TradeTag = any;
export type TradeChecklist = any;
export type TradeChecklistItem = any;
export type TradeEntry = any;
export type TradeImage = any;
export type TradeMtLink = any;
export type TradeNote = any;
export type TradeSyncTombstone = any;
export type EconomicEvent = any;
export type Roadmap = any;
export type WeeklyReportSnapshot = any;
export type WeeklyGoal = any;
export type PushSubscription = any;
export type UserSetting = any;
export type ExportRequest = any;
export type SharedProgressLink = any;
export type AuditLog = any;
export type ErrorLog = any;
export type AnalyticsEvent = any;
export type AppSetting = any;
export type TradeChatMessage = any;
export type TradeChatReport = any;
export type SupportTicket = any;
export type SupportMessage = any;
export type MobileCheckout = any;

class NullTypeValue {
  constructor(readonly _name: string) {}
}

export class PrismaClientKnownRequestError extends Error {
  code = "";
}

export const Prisma = {
  DbNull: new NullTypeValue("DbNull"),
  JsonNull: new NullTypeValue("JsonNull"),
  AnyNull: new NullTypeValue("AnyNull"),
  PrismaClientKnownRequestError,
};

export declare namespace Prisma {
  type JsonValue = any;
  type InputJsonValue = any;
  type JsonObject = Record<string, any>;
  type TransactionClient = any;
}

// delegateها طوری تایپ شده‌ن که findMany آرایه برگردونه (کدِ سرورِ وب که
// فقط از راهِ import typeِ زنجیره‌ای type-check می‌شه، implicit any نده).
type PrismaDelegate = ((...args: any[]) => any) & {
  findMany(...args: any[]): Promise<any[]>;
  [method: string]: any;
};

export class PrismaClient {
  [key: string]: PrismaDelegate;
  constructor(..._args: unknown[]) {
    throw new Error("PrismaClient is server-only");
  }
}
