// GENERATED by mobile/tooling/prismaShim.mjs from prisma/schema.prisma — do not edit.
// shimِ @prisma/client برای باندلِ کلاینتِ اپ موبایل (بدونِ query engine).
/* eslint-disable */

export const Market = {
  IRAN: "IRAN",
  INTERNATIONAL: "INTERNATIONAL",
} as const;
export type Market = (typeof Market)[keyof typeof Market];

export const Currency = {
  IRR: "IRR",
  USD: "USD",
} as const;
export type Currency = (typeof Currency)[keyof typeof Currency];

export const AiModel = {
  HAIKU: "HAIKU",
  SONNET: "SONNET",
} as const;
export type AiModel = (typeof AiModel)[keyof typeof AiModel];

export const ModuleKey = {
  ROUTINE: "ROUTINE",
  SLEEP: "SLEEP",
  TASKS: "TASKS",
  EXERCISE: "EXERCISE",
  CALORIE: "CALORIE",
  TRADE: "TRADE",
  ROADMAP: "ROADMAP",
  AI_INSIGHT: "AI_INSIGHT",
} as const;
export type ModuleKey = (typeof ModuleKey)[keyof typeof ModuleKey];

export const SubscriptionStatus = {
  TRIAL: "TRIAL",
  ACTIVE: "ACTIVE",
  PAST_DUE: "PAST_DUE",
  CANCELED: "CANCELED",
  EXPIRED: "EXPIRED",
} as const;
export type SubscriptionStatus = (typeof SubscriptionStatus)[keyof typeof SubscriptionStatus];

export const BillingInterval = {
  MONTHLY: "MONTHLY",
  YEARLY: "YEARLY",
} as const;
export type BillingInterval = (typeof BillingInterval)[keyof typeof BillingInterval];

export const ReferralUsageStatus = {
  PENDING: "PENDING",
  REWARDED: "REWARDED",
  REVOKED: "REVOKED",
} as const;
export type ReferralUsageStatus = (typeof ReferralUsageStatus)[keyof typeof ReferralUsageStatus];

export const PartnerType = {
  GYM: "GYM",
  OTHER: "OTHER",
} as const;
export type PartnerType = (typeof PartnerType)[keyof typeof PartnerType];

export const FriendshipStatus = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
} as const;
export type FriendshipStatus = (typeof FriendshipStatus)[keyof typeof FriendshipStatus];

export const AiFeatureKey = {
  DAILY_BRIEFING: "DAILY_BRIEFING",
  WEEKLY_COACH_REPORT: "WEEKLY_COACH_REPORT",
  CORRELATION_INSIGHT: "CORRELATION_INSIGHT",
  ROADMAP_GENERATION: "ROADMAP_GENERATION",
  EXERCISE_PLAN_GENERATION: "EXERCISE_PLAN_GENERATION",
  FOOD_SCAN: "FOOD_SCAN",
  ROUTINE_ASSISTANT: "ROUTINE_ASSISTANT",
} as const;
export type AiFeatureKey = (typeof AiFeatureKey)[keyof typeof AiFeatureKey];

export const ErrorSeverity = {
  WARNING: "WARNING",
  ERROR: "ERROR",
  CRITICAL: "CRITICAL",
} as const;
export type ErrorSeverity = (typeof ErrorSeverity)[keyof typeof ErrorSeverity];

export const TradeAccountType = {
  REAL: "REAL",
  DEMO: "DEMO",
  PROP: "PROP",
  BACKTEST: "BACKTEST",
} as const;
export type TradeAccountType = (typeof TradeAccountType)[keyof typeof TradeAccountType];

export const TradeGoalType = {
  AMOUNT: "AMOUNT",
  PERCENT: "PERCENT",
} as const;
export type TradeGoalType = (typeof TradeGoalType)[keyof typeof TradeGoalType];

export const TradeDirection = {
  BUY: "BUY",
  SELL: "SELL",
} as const;
export type TradeDirection = (typeof TradeDirection)[keyof typeof TradeDirection];

export const TradeStatus = {
  OPEN: "OPEN",
  CLOSED: "CLOSED",
  CANCELED: "CANCELED",
} as const;
export type TradeStatus = (typeof TradeStatus)[keyof typeof TradeStatus];

export const TradeResult = {
  PROFIT: "PROFIT",
  LOSS: "LOSS",
  BREAKEVEN: "BREAKEVEN",
} as const;
export type TradeResult = (typeof TradeResult)[keyof typeof TradeResult];

export const TradeSession = {
  SYDNEY: "SYDNEY",
  TOKYO: "TOKYO",
  LONDON: "LONDON",
  NEWYORK: "NEWYORK",
} as const;
export type TradeSession = (typeof TradeSession)[keyof typeof TradeSession];

export const TradeEntryReason = {
  STRATEGY: "STRATEGY",
  TECHNICAL_SIGNAL: "TECHNICAL_SIGNAL",
  FUNDAMENTAL_SIGNAL: "FUNDAMENTAL_SIGNAL",
  NEWS: "NEWS",
  INTUITION: "INTUITION",
  OTHERS_ADVICE: "OTHERS_ADVICE",
  FOMO: "FOMO",
  REVENGE: "REVENGE",
  OTHER: "OTHER",
} as const;
export type TradeEntryReason = (typeof TradeEntryReason)[keyof typeof TradeEntryReason];

export const TradeExitReason = {
  TAKE_PROFIT: "TAKE_PROFIT",
  STOP_LOSS: "STOP_LOSS",
  MANUAL: "MANUAL",
  TRAILING_STOP: "TRAILING_STOP",
  MARKET_CHANGE: "MARKET_CHANGE",
  EMOTIONAL: "EMOTIONAL",
  TIME_BASED: "TIME_BASED",
  OTHER: "OTHER",
} as const;
export type TradeExitReason = (typeof TradeExitReason)[keyof typeof TradeExitReason];

export const TradeEmotionBefore = {
  CALM: "CALM",
  NEUTRAL: "NEUTRAL",
  EXCITED: "EXCITED",
  ANXIOUS: "ANXIOUS",
  ANGRY: "ANGRY",
  OVERCONFIDENT: "OVERCONFIDENT",
} as const;
export type TradeEmotionBefore = (typeof TradeEmotionBefore)[keyof typeof TradeEmotionBefore];

export const TradeEmotionAfter = {
  SATISFIED: "SATISFIED",
  RELIEVED: "RELIEVED",
  INDIFFERENT: "INDIFFERENT",
  ANXIOUS: "ANXIOUS",
  REGRET: "REGRET",
  ANGRY: "ANGRY",
} as const;
export type TradeEmotionAfter = (typeof TradeEmotionAfter)[keyof typeof TradeEmotionAfter];

export const MtPlatform = {
  MT4: "MT4",
  MT5: "MT5",
} as const;
export type MtPlatform = (typeof MtPlatform)[keyof typeof MtPlatform];

export const EconomicImpact = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
} as const;
export type EconomicImpact = (typeof EconomicImpact)[keyof typeof EconomicImpact];

export const TradeChatReportReason = {
  SPAM: "SPAM",
  ABUSE: "ABUSE",
  SCAM: "SCAM",
  OFFTOPIC: "OFFTOPIC",
  OTHER: "OTHER",
} as const;
export type TradeChatReportReason = (typeof TradeChatReportReason)[keyof typeof TradeChatReportReason];

export const TradeChatReportStatus = {
  OPEN: "OPEN",
  ACTIONED: "ACTIONED",
  DISMISSED: "DISMISSED",
} as const;
export type TradeChatReportStatus = (typeof TradeChatReportStatus)[keyof typeof TradeChatReportStatus];

export const SupportTicketStatus = {
  OPEN: "OPEN",
  ANSWERED: "ANSWERED",
  CLOSED: "CLOSED",
} as const;
export type SupportTicketStatus = (typeof SupportTicketStatus)[keyof typeof SupportTicketStatus];

export type User = any;
export type OAuthAccount = any;
export type Session = any;
export type LoginEvent = any;
export type PasswordResetOtp = any;
export type TwoFactorOtp = any;
export type SignupOtp = any;
export type EmailLoginOtp = any;
export type EmailChangeOtp = any;
export type Plan = any;
export type PlanModule = any;
export type Subscription = any;
export type Payment = any;
export type ModuleAccess = any;
export type ReferralCode = any;
export type ReferralUsage = any;
export type DiscountCode = any;
export type DiscountCodeUsage = any;
export type Partner = any;
export type AiUsageRecord = any;
export type AiMonthlyQuota = any;
export type RoutineItem = any;
export type DailyEntry = any;
export type Friendship = any;
export type FriendStar = any;
export type UserBlock = any;
export type SleepEntry = any;
export type Task = any;
export type ExercisePlan = any;
export type ExerciseLog = any;
export type ExerciseMedia = any;
export type FoodItem = any;
export type FoodLogEntry = any;
export type CalorieTarget = any;
export type TradeAccount = any;
export type TradeTag = any;
export type TradeChecklist = any;
export type TradeChecklistItem = any;
export type TradeEntry = any;
export type TradeImage = any;
export type TradeMtLink = any;
export type TradeNote = any;
export type TradeSyncTombstone = any;
export type EconomicEvent = any;
export type Roadmap = any;
export type WeeklyReportSnapshot = any;
export type WeeklyGoal = any;
export type PushSubscription = any;
export type UserSetting = any;
export type ExportRequest = any;
export type SharedProgressLink = any;
export type AuditLog = any;
export type ErrorLog = any;
export type AnalyticsEvent = any;
export type AppSetting = any;
export type TradeChatMessage = any;
export type TradeChatReport = any;
export type SupportTicket = any;
export type SupportMessage = any;
export type MobileCheckout = any;

class NullTypeValue {
  constructor(readonly _name: string) {}
}

export class PrismaClientKnownRequestError extends Error {
  code = "";
}

export const Prisma = {
  DbNull: new NullTypeValue("DbNull"),
  JsonNull: new NullTypeValue("JsonNull"),
  AnyNull: new NullTypeValue("AnyNull"),
  PrismaClientKnownRequestError,
};

export declare namespace Prisma {
  type JsonValue = any;
  type InputJsonValue = any;
  type JsonObject = Record<string, any>;
  type TransactionClient = any;
  type UserUncheckedCreateInput = any;
  type UserCreateInput = any;
  type UserUncheckedUpdateInput = any;
  type UserUpdateInput = any;
  type UserWhereInput = any;
  type UserWhereUniqueInput = any;
  type UserGetPayload<T> = any;
  type OAuthAccountUncheckedCreateInput = any;
  type OAuthAccountCreateInput = any;
  type OAuthAccountUncheckedUpdateInput = any;
  type OAuthAccountUpdateInput = any;
  type OAuthAccountWhereInput = any;
  type OAuthAccountWhereUniqueInput = any;
  type OAuthAccountGetPayload<T> = any;
  type SessionUncheckedCreateInput = any;
  type SessionCreateInput = any;
  type SessionUncheckedUpdateInput = any;
  type SessionUpdateInput = any;
  type SessionWhereInput = any;
  type SessionWhereUniqueInput = any;
  type SessionGetPayload<T> = any;
  type LoginEventUncheckedCreateInput = any;
  type LoginEventCreateInput = any;
  type LoginEventUncheckedUpdateInput = any;
  type LoginEventUpdateInput = any;
  type LoginEventWhereInput = any;
  type LoginEventWhereUniqueInput = any;
  type LoginEventGetPayload<T> = any;
  type PasswordResetOtpUncheckedCreateInput = any;
  type PasswordResetOtpCreateInput = any;
  type PasswordResetOtpUncheckedUpdateInput = any;
  type PasswordResetOtpUpdateInput = any;
  type PasswordResetOtpWhereInput = any;
  type PasswordResetOtpWhereUniqueInput = any;
  type PasswordResetOtpGetPayload<T> = any;
  type TwoFactorOtpUncheckedCreateInput = any;
  type TwoFactorOtpCreateInput = any;
  type TwoFactorOtpUncheckedUpdateInput = any;
  type TwoFactorOtpUpdateInput = any;
  type TwoFactorOtpWhereInput = any;
  type TwoFactorOtpWhereUniqueInput = any;
  type TwoFactorOtpGetPayload<T> = any;
  type SignupOtpUncheckedCreateInput = any;
  type SignupOtpCreateInput = any;
  type SignupOtpUncheckedUpdateInput = any;
  type SignupOtpUpdateInput = any;
  type SignupOtpWhereInput = any;
  type SignupOtpWhereUniqueInput = any;
  type SignupOtpGetPayload<T> = any;
  type EmailLoginOtpUncheckedCreateInput = any;
  type EmailLoginOtpCreateInput = any;
  type EmailLoginOtpUncheckedUpdateInput = any;
  type EmailLoginOtpUpdateInput = any;
  type EmailLoginOtpWhereInput = any;
  type EmailLoginOtpWhereUniqueInput = any;
  type EmailLoginOtpGetPayload<T> = any;
  type EmailChangeOtpUncheckedCreateInput = any;
  type EmailChangeOtpCreateInput = any;
  type EmailChangeOtpUncheckedUpdateInput = any;
  type EmailChangeOtpUpdateInput = any;
  type EmailChangeOtpWhereInput = any;
  type EmailChangeOtpWhereUniqueInput = any;
  type EmailChangeOtpGetPayload<T> = any;
  type PlanUncheckedCreateInput = any;
  type PlanCreateInput = any;
  type PlanUncheckedUpdateInput = any;
  type PlanUpdateInput = any;
  type PlanWhereInput = any;
  type PlanWhereUniqueInput = any;
  type PlanGetPayload<T> = any;
  type PlanModuleUncheckedCreateInput = any;
  type PlanModuleCreateInput = any;
  type PlanModuleUncheckedUpdateInput = any;
  type PlanModuleUpdateInput = any;
  type PlanModuleWhereInput = any;
  type PlanModuleWhereUniqueInput = any;
  type PlanModuleGetPayload<T> = any;
  type SubscriptionUncheckedCreateInput = any;
  type SubscriptionCreateInput = any;
  type SubscriptionUncheckedUpdateInput = any;
  type SubscriptionUpdateInput = any;
  type SubscriptionWhereInput = any;
  type SubscriptionWhereUniqueInput = any;
  type SubscriptionGetPayload<T> = any;
  type PaymentUncheckedCreateInput = any;
  type PaymentCreateInput = any;
  type PaymentUncheckedUpdateInput = any;
  type PaymentUpdateInput = any;
  type PaymentWhereInput = any;
  type PaymentWhereUniqueInput = any;
  type PaymentGetPayload<T> = any;
  type ModuleAccessUncheckedCreateInput = any;
  type ModuleAccessCreateInput = any;
  type ModuleAccessUncheckedUpdateInput = any;
  type ModuleAccessUpdateInput = any;
  type ModuleAccessWhereInput = any;
  type ModuleAccessWhereUniqueInput = any;
  type ModuleAccessGetPayload<T> = any;
  type ReferralCodeUncheckedCreateInput = any;
  type ReferralCodeCreateInput = any;
  type ReferralCodeUncheckedUpdateInput = any;
  type ReferralCodeUpdateInput = any;
  type ReferralCodeWhereInput = any;
  type ReferralCodeWhereUniqueInput = any;
  type ReferralCodeGetPayload<T> = any;
  type ReferralUsageUncheckedCreateInput = any;
  type ReferralUsageCreateInput = any;
  type ReferralUsageUncheckedUpdateInput = any;
  type ReferralUsageUpdateInput = any;
  type ReferralUsageWhereInput = any;
  type ReferralUsageWhereUniqueInput = any;
  type ReferralUsageGetPayload<T> = any;
  type DiscountCodeUncheckedCreateInput = any;
  type DiscountCodeCreateInput = any;
  type DiscountCodeUncheckedUpdateInput = any;
  type DiscountCodeUpdateInput = any;
  type DiscountCodeWhereInput = any;
  type DiscountCodeWhereUniqueInput = any;
  type DiscountCodeGetPayload<T> = any;
  type DiscountCodeUsageUncheckedCreateInput = any;
  type DiscountCodeUsageCreateInput = any;
  type DiscountCodeUsageUncheckedUpdateInput = any;
  type DiscountCodeUsageUpdateInput = any;
  type DiscountCodeUsageWhereInput = any;
  type DiscountCodeUsageWhereUniqueInput = any;
  type DiscountCodeUsageGetPayload<T> = any;
  type PartnerUncheckedCreateInput = any;
  type PartnerCreateInput = any;
  type PartnerUncheckedUpdateInput = any;
  type PartnerUpdateInput = any;
  type PartnerWhereInput = any;
  type PartnerWhereUniqueInput = any;
  type PartnerGetPayload<T> = any;
  type AiUsageRecordUncheckedCreateInput = any;
  type AiUsageRecordCreateInput = any;
  type AiUsageRecordUncheckedUpdateInput = any;
  type AiUsageRecordUpdateInput = any;
  type AiUsageRecordWhereInput = any;
  type AiUsageRecordWhereUniqueInput = any;
  type AiUsageRecordGetPayload<T> = any;
  type AiMonthlyQuotaUncheckedCreateInput = any;
  type AiMonthlyQuotaCreateInput = any;
  type AiMonthlyQuotaUncheckedUpdateInput = any;
  type AiMonthlyQuotaUpdateInput = any;
  type AiMonthlyQuotaWhereInput = any;
  type AiMonthlyQuotaWhereUniqueInput = any;
  type AiMonthlyQuotaGetPayload<T> = any;
  type RoutineItemUncheckedCreateInput = any;
  type RoutineItemCreateInput = any;
  type RoutineItemUncheckedUpdateInput = any;
  type RoutineItemUpdateInput = any;
  type RoutineItemWhereInput = any;
  type RoutineItemWhereUniqueInput = any;
  type RoutineItemGetPayload<T> = any;
  type DailyEntryUncheckedCreateInput = any;
  type DailyEntryCreateInput = any;
  type DailyEntryUncheckedUpdateInput = any;
  type DailyEntryUpdateInput = any;
  type DailyEntryWhereInput = any;
  type DailyEntryWhereUniqueInput = any;
  type DailyEntryGetPayload<T> = any;
  type FriendshipUncheckedCreateInput = any;
  type FriendshipCreateInput = any;
  type FriendshipUncheckedUpdateInput = any;
  type FriendshipUpdateInput = any;
  type FriendshipWhereInput = any;
  type FriendshipWhereUniqueInput = any;
  type FriendshipGetPayload<T> = any;
  type FriendStarUncheckedCreateInput = any;
  type FriendStarCreateInput = any;
  type FriendStarUncheckedUpdateInput = any;
  type FriendStarUpdateInput = any;
  type FriendStarWhereInput = any;
  type FriendStarWhereUniqueInput = any;
  type FriendStarGetPayload<T> = any;
  type UserBlockUncheckedCreateInput = any;
  type UserBlockCreateInput = any;
  type UserBlockUncheckedUpdateInput = any;
  type UserBlockUpdateInput = any;
  type UserBlockWhereInput = any;
  type UserBlockWhereUniqueInput = any;
  type UserBlockGetPayload<T> = any;
  type SleepEntryUncheckedCreateInput = any;
  type SleepEntryCreateInput = any;
  type SleepEntryUncheckedUpdateInput = any;
  type SleepEntryUpdateInput = any;
  type SleepEntryWhereInput = any;
  type SleepEntryWhereUniqueInput = any;
  type SleepEntryGetPayload<T> = any;
  type TaskUncheckedCreateInput = any;
  type TaskCreateInput = any;
  type TaskUncheckedUpdateInput = any;
  type TaskUpdateInput = any;
  type TaskWhereInput = any;
  type TaskWhereUniqueInput = any;
  type TaskGetPayload<T> = any;
  type ExercisePlanUncheckedCreateInput = any;
  type ExercisePlanCreateInput = any;
  type ExercisePlanUncheckedUpdateInput = any;
  type ExercisePlanUpdateInput = any;
  type ExercisePlanWhereInput = any;
  type ExercisePlanWhereUniqueInput = any;
  type ExercisePlanGetPayload<T> = any;
  type ExerciseLogUncheckedCreateInput = any;
  type ExerciseLogCreateInput = any;
  type ExerciseLogUncheckedUpdateInput = any;
  type ExerciseLogUpdateInput = any;
  type ExerciseLogWhereInput = any;
  type ExerciseLogWhereUniqueInput = any;
  type ExerciseLogGetPayload<T> = any;
  type ExerciseMediaUncheckedCreateInput = any;
  type ExerciseMediaCreateInput = any;
  type ExerciseMediaUncheckedUpdateInput = any;
  type ExerciseMediaUpdateInput = any;
  type ExerciseMediaWhereInput = any;
  type ExerciseMediaWhereUniqueInput = any;
  type ExerciseMediaGetPayload<T> = any;
  type FoodItemUncheckedCreateInput = any;
  type FoodItemCreateInput = any;
  type FoodItemUncheckedUpdateInput = any;
  type FoodItemUpdateInput = any;
  type FoodItemWhereInput = any;
  type FoodItemWhereUniqueInput = any;
  type FoodItemGetPayload<T> = any;
  type FoodLogEntryUncheckedCreateInput = any;
  type FoodLogEntryCreateInput = any;
  type FoodLogEntryUncheckedUpdateInput = any;
  type FoodLogEntryUpdateInput = any;
  type FoodLogEntryWhereInput = any;
  type FoodLogEntryWhereUniqueInput = any;
  type FoodLogEntryGetPayload<T> = any;
  type CalorieTargetUncheckedCreateInput = any;
  type CalorieTargetCreateInput = any;
  type CalorieTargetUncheckedUpdateInput = any;
  type CalorieTargetUpdateInput = any;
  type CalorieTargetWhereInput = any;
  type CalorieTargetWhereUniqueInput = any;
  type CalorieTargetGetPayload<T> = any;
  type TradeAccountUncheckedCreateInput = any;
  type TradeAccountCreateInput = any;
  type TradeAccountUncheckedUpdateInput = any;
  type TradeAccountUpdateInput = any;
  type TradeAccountWhereInput = any;
  type TradeAccountWhereUniqueInput = any;
  type TradeAccountGetPayload<T> = any;
  type TradeTagUncheckedCreateInput = any;
  type TradeTagCreateInput = any;
  type TradeTagUncheckedUpdateInput = any;
  type TradeTagUpdateInput = any;
  type TradeTagWhereInput = any;
  type TradeTagWhereUniqueInput = any;
  type TradeTagGetPayload<T> = any;
  type TradeChecklistUncheckedCreateInput = any;
  type TradeChecklistCreateInput = any;
  type TradeChecklistUncheckedUpdateInput = any;
  type TradeChecklistUpdateInput = any;
  type TradeChecklistWhereInput = any;
  type TradeChecklistWhereUniqueInput = any;
  type TradeChecklistGetPayload<T> = any;
  type TradeChecklistItemUncheckedCreateInput = any;
  type TradeChecklistItemCreateInput = any;
  type TradeChecklistItemUncheckedUpdateInput = any;
  type TradeChecklistItemUpdateInput = any;
  type TradeChecklistItemWhereInput = any;
  type TradeChecklistItemWhereUniqueInput = any;
  type TradeChecklistItemGetPayload<T> = any;
  type TradeEntryUncheckedCreateInput = any;
  type TradeEntryCreateInput = any;
  type TradeEntryUncheckedUpdateInput = any;
  type TradeEntryUpdateInput = any;
  type TradeEntryWhereInput = any;
  type TradeEntryWhereUniqueInput = any;
  type TradeEntryGetPayload<T> = any;
  type TradeImageUncheckedCreateInput = any;
  type TradeImageCreateInput = any;
  type TradeImageUncheckedUpdateInput = any;
  type TradeImageUpdateInput = any;
  type TradeImageWhereInput = any;
  type TradeImageWhereUniqueInput = any;
  type TradeImageGetPayload<T> = any;
  type TradeMtLinkUncheckedCreateInput = any;
  type TradeMtLinkCreateInput = any;
  type TradeMtLinkUncheckedUpdateInput = any;
  type TradeMtLinkUpdateInput = any;
  type TradeMtLinkWhereInput = any;
  type TradeMtLinkWhereUniqueInput = any;
  type TradeMtLinkGetPayload<T> = any;
  type TradeNoteUncheckedCreateInput = any;
  type TradeNoteCreateInput = any;
  type TradeNoteUncheckedUpdateInput = any;
  type TradeNoteUpdateInput = any;
  type TradeNoteWhereInput = any;
  type TradeNoteWhereUniqueInput = any;
  type TradeNoteGetPayload<T> = any;
  type TradeSyncTombstoneUncheckedCreateInput = any;
  type TradeSyncTombstoneCreateInput = any;
  type TradeSyncTombstoneUncheckedUpdateInput = any;
  type TradeSyncTombstoneUpdateInput = any;
  type TradeSyncTombstoneWhereInput = any;
  type TradeSyncTombstoneWhereUniqueInput = any;
  type TradeSyncTombstoneGetPayload<T> = any;
  type EconomicEventUncheckedCreateInput = any;
  type EconomicEventCreateInput = any;
  type EconomicEventUncheckedUpdateInput = any;
  type EconomicEventUpdateInput = any;
  type EconomicEventWhereInput = any;
  type EconomicEventWhereUniqueInput = any;
  type EconomicEventGetPayload<T> = any;
  type RoadmapUncheckedCreateInput = any;
  type RoadmapCreateInput = any;
  type RoadmapUncheckedUpdateInput = any;
  type RoadmapUpdateInput = any;
  type RoadmapWhereInput = any;
  type RoadmapWhereUniqueInput = any;
  type RoadmapGetPayload<T> = any;
  type WeeklyReportSnapshotUncheckedCreateInput = any;
  type WeeklyReportSnapshotCreateInput = any;
  type WeeklyReportSnapshotUncheckedUpdateInput = any;
  type WeeklyReportSnapshotUpdateInput = any;
  type WeeklyReportSnapshotWhereInput = any;
  type WeeklyReportSnapshotWhereUniqueInput = any;
  type WeeklyReportSnapshotGetPayload<T> = any;
  type WeeklyGoalUncheckedCreateInput = any;
  type WeeklyGoalCreateInput = any;
  type WeeklyGoalUncheckedUpdateInput = any;
  type WeeklyGoalUpdateInput = any;
  type WeeklyGoalWhereInput = any;
  type WeeklyGoalWhereUniqueInput = any;
  type WeeklyGoalGetPayload<T> = any;
  type PushSubscriptionUncheckedCreateInput = any;
  type PushSubscriptionCreateInput = any;
  type PushSubscriptionUncheckedUpdateInput = any;
  type PushSubscriptionUpdateInput = any;
  type PushSubscriptionWhereInput = any;
  type PushSubscriptionWhereUniqueInput = any;
  type PushSubscriptionGetPayload<T> = any;
  type UserSettingUncheckedCreateInput = any;
  type UserSettingCreateInput = any;
  type UserSettingUncheckedUpdateInput = any;
  type UserSettingUpdateInput = any;
  type UserSettingWhereInput = any;
  type UserSettingWhereUniqueInput = any;
  type UserSettingGetPayload<T> = any;
  type ExportRequestUncheckedCreateInput = any;
  type ExportRequestCreateInput = any;
  type ExportRequestUncheckedUpdateInput = any;
  type ExportRequestUpdateInput = any;
  type ExportRequestWhereInput = any;
  type ExportRequestWhereUniqueInput = any;
  type ExportRequestGetPayload<T> = any;
  type SharedProgressLinkUncheckedCreateInput = any;
  type SharedProgressLinkCreateInput = any;
  type SharedProgressLinkUncheckedUpdateInput = any;
  type SharedProgressLinkUpdateInput = any;
  type SharedProgressLinkWhereInput = any;
  type SharedProgressLinkWhereUniqueInput = any;
  type SharedProgressLinkGetPayload<T> = any;
  type AuditLogUncheckedCreateInput = any;
  type AuditLogCreateInput = any;
  type AuditLogUncheckedUpdateInput = any;
  type AuditLogUpdateInput = any;
  type AuditLogWhereInput = any;
  type AuditLogWhereUniqueInput = any;
  type AuditLogGetPayload<T> = any;
  type ErrorLogUncheckedCreateInput = any;
  type ErrorLogCreateInput = any;
  type ErrorLogUncheckedUpdateInput = any;
  type ErrorLogUpdateInput = any;
  type ErrorLogWhereInput = any;
  type ErrorLogWhereUniqueInput = any;
  type ErrorLogGetPayload<T> = any;
  type AnalyticsEventUncheckedCreateInput = any;
  type AnalyticsEventCreateInput = any;
  type AnalyticsEventUncheckedUpdateInput = any;
  type AnalyticsEventUpdateInput = any;
  type AnalyticsEventWhereInput = any;
  type AnalyticsEventWhereUniqueInput = any;
  type AnalyticsEventGetPayload<T> = any;
  type AppSettingUncheckedCreateInput = any;
  type AppSettingCreateInput = any;
  type AppSettingUncheckedUpdateInput = any;
  type AppSettingUpdateInput = any;
  type AppSettingWhereInput = any;
  type AppSettingWhereUniqueInput = any;
  type AppSettingGetPayload<T> = any;
  type TradeChatMessageUncheckedCreateInput = any;
  type TradeChatMessageCreateInput = any;
  type TradeChatMessageUncheckedUpdateInput = any;
  type TradeChatMessageUpdateInput = any;
  type TradeChatMessageWhereInput = any;
  type TradeChatMessageWhereUniqueInput = any;
  type TradeChatMessageGetPayload<T> = any;
  type TradeChatReportUncheckedCreateInput = any;
  type TradeChatReportCreateInput = any;
  type TradeChatReportUncheckedUpdateInput = any;
  type TradeChatReportUpdateInput = any;
  type TradeChatReportWhereInput = any;
  type TradeChatReportWhereUniqueInput = any;
  type TradeChatReportGetPayload<T> = any;
  type SupportTicketUncheckedCreateInput = any;
  type SupportTicketCreateInput = any;
  type SupportTicketUncheckedUpdateInput = any;
  type SupportTicketUpdateInput = any;
  type SupportTicketWhereInput = any;
  type SupportTicketWhereUniqueInput = any;
  type SupportTicketGetPayload<T> = any;
  type SupportMessageUncheckedCreateInput = any;
  type SupportMessageCreateInput = any;
  type SupportMessageUncheckedUpdateInput = any;
  type SupportMessageUpdateInput = any;
  type SupportMessageWhereInput = any;
  type SupportMessageWhereUniqueInput = any;
  type SupportMessageGetPayload<T> = any;
  type MobileCheckoutUncheckedCreateInput = any;
  type MobileCheckoutCreateInput = any;
  type MobileCheckoutUncheckedUpdateInput = any;
  type MobileCheckoutUpdateInput = any;
  type MobileCheckoutWhereInput = any;
  type MobileCheckoutWhereUniqueInput = any;
  type MobileCheckoutGetPayload<T> = any;
}

// delegateها طوری تایپ شده‌ن که findMany آرایه برگردونه (کدِ سرورِ وب که
// فقط از راهِ import typeِ زنجیره‌ای type-check می‌شه، implicit any نده).
type PrismaDelegate = ((...args: any[]) => any) & {
  findMany(...args: any[]): Promise<any[]>;
  [method: string]: any;
};

export class PrismaClient {
  [key: string]: PrismaDelegate;
  constructor(..._args: unknown[]) {
    throw new Error("PrismaClient is server-only");
  }
}
