-- AlterTable
ALTER TABLE "FoodLogEntry" ADD COLUMN     "proteinG" DOUBLE PRECISION,
ADD COLUMN     "carbsG" DOUBLE PRECISION,
ADD COLUMN     "fatG" DOUBLE PRECISION,
ADD COLUMN     "aiScanned" BOOLEAN NOT NULL DEFAULT false;
