import type { BlogPostEn } from "./types";

// English translation of ../health.ts — key = slug
export const HEALTH_POSTS_EN: Record<string, BlogPostEn> = {
  "how-to-write-a-bodybuilding-program": {
    title: "How to Write a Bodybuilding Program?",
    metaTitle: "How to Write a Bodybuilding Program? A Complete Step-by-Step Guide",
    description:
      "A guide to writing a bodybuilding program: choosing your goal, training days per week, muscle splits, sets and reps, progressive overload and rest, with a sample weekly program.",
    keywords: [
      "bodybuilding program",
      "how to write a bodybuilding program",
      "weekly workout program",
      "muscle split",
      "sets and reps",
      "bodybuilding volume program",
    ],
    excerpt:
      "From choosing a goal to sets, reps and progressive overload: how to write a bodybuilding program that fits your real life.",
    takeaways: [
      "A good program starts with the goal, not with a list of exercises.",
      "Choose your training days based on the time you really have, not the ideal.",
      "Training each muscle group about 2 times a week at moderate volume usually gives the best balance.",
      "Progress means progressive overload: a little more weight or a few more reps, not sudden jumps.",
      "Recovery and sleep are part of the program, not something separate from it.",
    ],
    blocks: [
      { type: "p", text: "Most bodybuilding programs we take from a friend or find online were written for someone else: with a different goal, level, schedule and situation that are not necessarily ours. The result is that a few weeks later we either get exhausted, get injured, or abandon the program. In this guide you will learn step by step to write a bodybuilding program from scratch, and to understand why every number in it is where it is." },
      { type: "p", text: "Writing a program starts with one question: exactly what are you training for? After that come a few small decisions in sequence: how many days a week, which exercises, how many sets and reps for each exercise, and how to make it gradually harder." },
      { type: "h2", text: "Step one: define your goal" },
      { type: "p", text: "The goal determines how heavy the weight should be, how many reps you do, and how long you rest between sets. Four common goals are:" },
      {
        type: "ul",
        items: [
          "Strength: low reps (3 to 6) with heavy weight and long rest; for someone who wants to get stronger in main lifts like squats, bench press and deadlifts.",
          "Muscle growth (hypertrophy): moderate reps (about 6 to 12 or a little more) and enough weekly volume for each muscle group.",
          "Cut (losing fat): resistance training to keep muscle alongside a calorie deficit and some cardio.",
          "Endurance and general fitness: a mix of cardio and lighter strength training with higher reps.",
        ],
      },
      { type: "p", text: "Chasing several demanding goals at once, for example maximal strength alongside an aggressive cut, usually does not move any of them forward properly. Your body's capacity for recovery is limited. If you are a beginner, the good news is that a simple general program will move all of these forward a little together." },
      { type: "h2", text: "Step two: choose your training days realistically" },
      { type: "p", text: "A program written for 5 days a week, when you actually have 3 days, falls behind from the very first week. Build the program around the number of days that you truly and consistently have available, even if that is below the ideal. Three sessions that happen every week on schedule are ahead of five sessions where half get skipped." },
      { type: "tip", title: "A rule from experience", text: "Pick a number of days you can keep even in a busy week. If a week goes well, add an extra session; do not build the program around the good week." },
      { type: "h2", text: "Step three: split the muscles across the days" },
      { type: "p", text: "The general rule is that each muscle group should be trained about 2 times a week, with at least 48 hours between two sessions for the same muscle. Based on the number of days, these patterns are common:" },
      { type: "table", head: ["Days", "Pattern", "Suitable for"], rows: [
        ["2 to 3 days", "Full body", "Beginners and people with little time"],
        ["4 days", "Upper / lower", "Beginner to intermediate level"],
        ["3 to 6 days", "Push / Pull / Legs", "Intermediate to advanced level with more training volume"],
        ["5 days", "Body-part split", "Someone with plenty of time and sufficient experience"],
      ] },
      { type: "h3", text: "What is Push / Pull / Legs?" },
      { type: "p", text: "On a Push day you train the muscles that \"push\" the movement: chest, shoulders and triceps. On a Pull day, the muscles that \"pull\": back, biceps and rear shoulders. Legs day covers all the leg muscles and usually the abs. This pattern is logical and popular because it groups muscles that work together on the same day." },
      { type: "h2", text: "Step four: choose your exercises" },
      { type: "p", text: "Think of exercises in two categories. First, compound exercises such as squats, deadlifts, bench press, overhead press, pull-ups or cable lat pulldowns and rows; these work many muscles at once and form the backbone of the program. Second, isolation exercises such as biceps curls, triceps extensions, lateral raises and leg extensions, which come in to complete a specific muscle." },
      { type: "p", text: "A simple rule: start each session with one or two compound exercises, while your energy is high, and then move on to isolation exercises. For most people, 4 to 7 exercises in total per session is enough." },
      { type: "h2", text: "Step five: sets, reps and rest" },
      { type: "p", text: "Choose these three numbers based on your goal. The table below shows common, general ranges, not absolute numbers:" },
      { type: "table", head: ["Goal", "Reps per set", "Rest between sets", "Weekly sets per muscle"], rows: [
        ["Strength", "3 to 6", "2 to 4 minutes", "About 8 to 12"],
        ["Volume", "6 to 12", "1 to 2 minutes", "About 10 to 16"],
        ["Cut", "8 to 15", "60 to 90 seconds", "About 8 to 14"],
        ["Endurance", "12 to 20", "30 to 60 seconds", "About 8 to 12"],
      ] },
      { type: "p", text: "Beginners are better off starting at the lower end of the ranges. High volume at the start only causes muscle soreness and fatigue, not faster growth. The last set of each exercise should be hard, but your form should not break down in it; usually you finish with 1 to 3 reps left before complete failure." },
      { type: "h2", text: "Step six: progressive overload" },
      { type: "p", text: "Your body only changes when it sees a new stimulus. If you train for months with the same weight and the same reps, your body gets used to it and progress stalls. This is called progressive overload. The practical way to do it is:" },
      {
        type: "ol",
        items: [
          "For each exercise, set a rep range, for example 8 to 12.",
          "Start with a weight that lets you finish the sets at about 8 reps.",
          "In each session, try to get one more rep until you reach the top of the range (12).",
          "When all sets reach 12, increase the weight a little (for example 2 to 5 percent) and start again from 8.",
          "Write down the weight and reps in every session so you know what you did last time.",
        ],
      },
      { type: "h2", text: "Sample weekly program (upper / lower, 4 days)" },
      { type: "p", text: "This is just an example to understand the structure. Exercises and number of sets can be changed to fit your level and equipment." },
      { type: "table", head: ["Day", "Focus", "Main exercises"], rows: [
        ["Saturday", "Upper A", "Bench press, row, overhead press, lat pulldown, biceps curl"],
        ["Sunday", "Lower A", "Squat, Romanian deadlift, lunge, calf raise, abs"],
        ["Monday", "Rest", "Light walk and stretching"],
        ["Tuesday", "Upper B", "Incline bench press, pull-up or lat pulldown, lateral raise, triceps extension"],
        ["Wednesday", "Lower B", "Deadlift or hip thrust, leg press, leg curl, calf raise"],
        ["Thursday and Friday", "Rest", "Recovery or light cardio"],
      ] },
      { type: "h2", text: "Warm-up, recovery and sleep" },
      { type: "p", text: "Before your first exercise, do 5 to 8 minutes of general warm-up (such as a stationary bike or dynamic stretches) and then one or two light sets of the exercise you are about to do. This lowers the risk of injury. Muscle does not grow in the gym; it grows in the recovery after it. So adequate sleep and proper food are inseparable parts of the program. To set your sleep schedule, the sleep cycle article in this blog can help." },
      { type: "cta", text: "Enter your height, weight and training history and calculate your daily calorie intake for your bodybuilding goal.", href: "/tools/calorie-calculator", label: "Free calorie calculator" },
      { type: "h2", text: "Common mistakes when writing a program" },
      {
        type: "ul",
        items: [
          "Copying the program of a champion who progressed over years with genetics, special conditions and experience.",
          "Constantly switching programs; give any program at least 6 to 8 weeks.",
          "Heavy weight with poor form; real progress means correct form with heavier weight.",
          "Ignoring rest days and sleep.",
          "Not tracking; without notes on weight and reps, overload is just a guess.",
        ],
      },
      { type: "h2", text: "Execution details that make a difference" },
      { type: "h3", text: "Speed and control" },
      { type: "p", text: "Lower the weight in a controlled way (about 2 to 3 seconds) and raise it smoothly without swinging your body. A weight that goes up with a jerky motion puts more stress on joints and the lower back than on the target muscle." },
      { type: "h3", text: "Range of motion" },
      { type: "p", text: "Perform the movement through the full range your joints allow, without pain. A half-rep with heavy weight looks impressive but usually reduces muscle stimulation." },
      { type: "h3", text: "Breathing" },
      { type: "p", text: "Usually inhale while lowering or before starting the effort, and exhale when you push the weight. Practice very heavy lifts such as a heavy squat with a coach." },
      { type: "h2", text: "Track your training and review every few weeks" },
      { type: "p", text: "A written program is only a hypothesis; the evidence comes from your logged workouts. In every session, note the weight for each exercise, the reps of each set, and a simple difficulty score (for example from 1 to 10). Every 4 to 6 weeks, take a look: Has the weight gone up? Is there an exercise that always hurts? Is there a session that keeps getting skipped? Based on these answers, change one or two things, not the whole program." },
      { type: "p", text: "If you feel more tired for two or three weeks in a row and your weights are dropping, take a lighter week (a deload): the same exercises, about half the sets or 60 percent of the weight. This planned rest is usually needed to keep progressing." },
      { type: "h2", text: "Arion program builder" },
      { type: "p", text: "Arion applies this same logic with artificial intelligence. You describe your goal in free text, enter your height, weight and training history and the days you really go to the gym, and the program is built on that basis. If you have physical limitations, suitable alternative exercises are substituted. The bodybuilding section is a separate module, and a new account gets a 3-day trial period." },
      { type: "cta", text: "Build a weekly program that matches your goal and your days.", href: "/bodybuilding-program", label: "Arion bodybuilding program" },
    ],
    faq: [
      { q: "How many days a week should I train as a beginner?", a: "For beginners, 2 to 3 days a week with a full-body program is enough and low-risk. Consistency matters more than the number of days. Once your body adapts and your recovery is good, you can move up to 4 days. Starting with 6 days usually ends in exhaustion and giving up the program." },
      { q: "How many sets and reps should I do per exercise?", a: "For muscle growth, 3 to 4 sets of 6 to 12 reps are usually chosen, and for strength, 3 to 5 sets of 3 to 6 reps. A beginner starting with 2 to 3 sets per exercise is enough. The main criterion is that the last sets are hard but your form does not break down." },
      { q: "How often should I change the program?", a: "You do not need to change it constantly. A program is usually followed for 6 to 12 weeks, and during that time you only increase the weight and reps. When you have no progress for several weeks in a row, then changing exercises or volume makes sense." },
      { q: "Can I write a program without a coach?", a: "Yes, by following the basic principles. But for heavy lifts such as squats and deadlifts, having a coach watch your form, or even filming yourself, is a big help. If you have an injury or a medical condition, it is better to consult a doctor or physiotherapist before starting." },
      { q: "How important are rest days?", a: "Very. Muscle repairs and gets stronger in the time between sessions. Usually at least 1 to 2 full rest days per week and about 48 hours between two sessions for the same muscle are recommended. Sufficient sleep at night is also a major part of this recovery." },
    ],
    related: [
      { href: "/bodybuilding-program", label: "Arion AI bodybuilding program" },
      { href: "/blog/beginner-gym-program-3-days", label: "3-day bodybuilding program for beginners" },
      { href: "/blog/how-much-protein-per-day", label: "How much protein do we need per day?" },
      { href: "/tools/calorie-calculator", label: "Free calorie calculator" },
    ],
  },
  "how-to-count-daily-calories": {
    title: "How to Calculate Daily Calories and a Calorie Deficit",
    metaTitle: "Calculating Daily Calories and Calorie Deficit | Complete Guide",
    description:
      "Calculate your daily calories with the Mifflin-St Jeor formula, the difference between BMR and TDEE, activity factors, and the right size of a calorie deficit or surplus for losing or gaining weight, with a worked example.",
    keywords: [
      "daily calorie calculation",
      "calorie deficit",
      "BMR calculation",
      "TDEE calculation",
      "calories your body needs",
      "calories for weight loss",
    ],
    excerpt:
      "The difference between BMR and TDEE, the formula, activity factors and the right size of a calorie deficit or surplus, with a worked example.",
    takeaways: [
      "First you need to know your maintenance calories (TDEE), then reduce or increase them.",
      "TDEE is BMR multiplied by the activity factor.",
      "For weight loss, a deficit of about 15 to 20 percent is usually reasonable and sustainable.",
      "The calculated number is an estimate; correct it after two or three weeks of weight tracking.",
      "This article is general information and does not replace advice from a doctor or dietitian.",
    ],
    blocks: [
      { type: "p", text: "Before making any decision about your diet, you need a baseline number: the calories your body uses in a day. Without this number, \"I'll eat less\" or \"I'll eat more\" is just a guess, because you do not know what you are reducing or increasing. In this article you will learn step by step how to calculate your daily calories with a reliable formula, see how it works with a numerical example, and find your final number based on your goal (losing, maintaining or gaining weight)." },
      { type: "p", text: "A short reminder: the material on this page is general information, not medical advice. If you have an underlying condition, are pregnant, breastfeeding, or have a history of an eating disorder, consult a doctor or dietitian before changing your diet." },
      { type: "h2", text: "What are calories and why does counting them matter?" },
      { type: "p", text: "A calorie is a unit of food energy. Your body uses a certain amount of energy every day and takes in a certain amount from food. If intake is lower than use, your weight gradually goes down; if it is higher, your weight goes up; and if they are equal, your weight stays roughly the same. It sounds simple, but in practice, without numbers, mental estimates are usually very wrong. Most of us underestimate how much we eat and overestimate how active we are. Calculating calories means replacing guesswork with a measurable starting point." },
      { type: "h2", text: "What is BMR?" },
      { type: "p", text: "BMR, or basal metabolic rate, is the energy your body uses even at complete rest; for breathing, heartbeat, brain function and keeping your body temperature stable. A large part of your daily calories (usually more than half) goes to these basic functions. This number is calculated from sex, height, weight and age using formulas. One of the best-known and most widely used is the Mifflin-St Jeor formula:" },
      { type: "table", head: ["Sex", "BMR formula (calories per day)"], rows: [
        ["Male", "10 × weight (kg) + 6.25 × height (cm) − 5 × age (years) + 5"],
        ["Female", "10 × weight (kg) + 6.25 × height (cm) − 5 × age (years) − 161"],
      ] },
      { type: "h2", text: "From BMR to TDEE" },
      { type: "p", text: "TDEE, or total daily energy expenditure (maintenance calories), is the total energy you use over an actual day: BMR plus the energy of daily work, walking, digesting food and training. To calculate it, BMR is multiplied by an activity factor:" },
      { type: "table", head: ["Activity level", "Description", "Factor"], rows: [
        ["Sedentary", "Desk work, almost no exercise", "1.2"],
        ["Lightly active", "Light exercise 1 to 3 days a week", "1.375"],
        ["Moderately active", "Moderate exercise 3 to 5 days a week", "1.55"],
        ["Very active", "Hard exercise 6 to 7 days a week", "1.725"],
        ["Extremely active", "Heavy physical work plus daily training", "1.9"],
      ] },
      { type: "tip", title: "Usually choose the level one step lower", text: "Most people overestimate their activity. If you are unsure between two levels, choose the lower one and then correct it by tracking your weight." },
      { type: "h2", text: "A complete worked example" },
      { type: "p", text: "Suppose you are a 30-year-old woman, 165 cm tall and weighing 70 kg, who exercises 3 days a week. The calculation steps look like this:" },
      {
        type: "ol",
        items: [
          "BMR = 10 × 70 + 6.25 × 165 − 5 × 30 − 161 = 700 + 1031.25 − 150 − 161 = about 1420 calories.",
          "Activity factor for 3 days of exercise per week: about 1.55 (moderately active). If your exercise is lighter, use 1.375.",
          "TDEE = 1420 × 1.55 = about 2200 calories per day; this is your weight-maintenance intake.",
          "For weight loss with a 15 to 20 percent deficit: 2200 × 0.8 to 0.85 = about 1760 to 1870 calories per day.",
          "Safety floor check: this number is above your BMR (1420), so it is acceptable.",
        ],
      },
      { type: "h2", text: "Calorie deficit and surplus" },
      {
        type: "ul",
        items: [
          "Weight loss: a reasonable deficit is usually about 15 to 20 percent below TDEE. A larger deficit is usually accompanied by severe hunger, low energy and muscle loss, and it is hard to keep up.",
          "Weight or muscle gain: a surplus of about 10 to 15 percent above TDEE is enough. A very large surplus mostly turns into fat.",
          "Weight maintenance: the target is your TDEE.",
        ],
      },
      { type: "p", text: "A safer and more sustainable pace of weight loss is usually said to be about half to one percent of body weight per week. For someone weighing 70 kg, that is about 350 to 700 grams per week. Faster losses are hard for most people to sustain and are usually followed by weight regain." },
      { type: "h2", text: "Why a safety floor is necessary" },
      { type: "p", text: "A percentage deficit for someone who is small and sedentary can push the daily target even below their BMR; that is, less than the energy the body needs just for basic functions. This is neither healthy nor effective in the long run for most people. For this reason, the daily target should not go below two limits: BMR itself, and the common minimum (usually about 1200 calories for women and 1500 calories for men). If your calculation comes out below these, rather than a harsher deficit, it is better to slow the plan down or work on it with a specialist." },
      { type: "h2", text: "It is an estimate, not an absolute truth" },
      { type: "p", text: "Every formula is an average for a group of people, and it may differ by 5 to 10 percent for your body. So treat the number you get as a \"first hypothesis\" and review it with this method:" },
      {
        type: "ol",
        items: [
          "For two to three weeks, eat the same amount of calories and log everything you eat.",
          "Every morning, fasting and after using the toilet, weigh yourself.",
          "Compare the average weight of the week with the previous week, not the weight of a single day.",
          "If your weight does not change in line with your goal, adjust by about 100 to 150 calories up or down.",
          "Wait two more weeks and measure again; small, gradual changes are better than big jumps.",
        ],
      },
      { type: "h2", text: "An example for a man and a note on weight gain" },
      { type: "p", text: "Now take a 25-year-old man, 180 cm tall and weighing 70 kg, who does bodybuilding 4 days a week and wants to build muscle:" },
      {
        type: "ol",
        items: [
          "BMR = 10 × 70 + 6.25 × 180 − 5 × 25 + 5 = 700 + 1125 − 125 + 5 = about 1705 calories.",
          "Factor 1.55 for moderate activity: TDEE = 1705 × 1.55 = about 2640 calories.",
          "A surplus of 10 to 15 percent: 2640 × 1.10 to 1.15 = about 2900 to 3040 calories per day.",
          "If your weight has not changed after 3 weeks, add 150 calories; if it rises too fast (more than about half a percent of body weight per week), reduce a little.",
        ],
      },
      { type: "p", text: "To build muscle without piling on too much fat, a slow rate of weight gain (from a few hundred grams a month up to about one percent of body weight a month) is usually preferable. Rapid weight gain is more fat than muscle." },
      { type: "h2", text: "How should you account for calories burned in exercise?" },
      { type: "p", text: "The activity factor already includes your exercise in TDEE, so you do not need to add the \"calories burned\" back to your food after every session. If you chose the factor based on your week and then also eat extra food for today's workout, the calculation is counted twice. Only raise the factor if your weekly activity has permanently changed (for example from 2 to 5 sessions)." },
      { type: "h2", text: "Calories are only half of the story" },
      { type: "p", text: "Calories show the amount of energy but not the quality of food. 500 calories of yogurt, fruit and chicken feel and affect you very differently from 500 calories of soda and sweets. In practice, along with counting calories, consider two things: first, enough protein (to preserve muscle and feel fuller), and second, fiber and minimally processed food, which give more volume for the same calories. For details on protein, see the article \"How much protein do we need per day\" in this blog." },
      { type: "h2", text: "Splitting calories across meals" },
      { type: "p", text: "You do not need to split your daily calories equally across meals. The number of meals (from 2 to 6) depends on your work hours, appetite and lifestyle. For example, if you have no appetite in the morning, breakfast gets a smaller share and lunch and dinner get more. For a target of 1800 calories and 4 meals, it might look like 450 calories for breakfast, 600 for lunch, 250 for a snack and 500 for dinner. What matters is choosing a split you can keep up for weeks." },
      { type: "cta", text: "Enter your height, weight, age and activity level to see your BMR, TDEE and target calories in seconds.", href: "/tools/calorie-calculator", label: "Free calorie calculator" },
      { type: "h2", text: "Common mistakes when counting calories" },
      {
        type: "ul",
        items: [
          "Not logging oil, sauces, drinks and small snacks between meals; these usually throw off the total.",
          "Not weighing food on a scale; visual estimates are very inaccurate, especially for rice and oil.",
          "Fully trusting the calories-burned number on exercise machines, which often overestimate.",
          "A very severe deficit in the first weeks that is later offset by overeating.",
          "Comparing your daily weight; fluctuations of a few hundred grams to a kilogram a day in body water are normal.",
          "Not updating the number after your weight has changed; after losing a few kilos, your TDEE also drops and needs to be recalculated.",
        ],
      },
      { type: "h2", text: "Logging calories in Arion" },
      { type: "p", text: "Arion performs this calculation with the Mifflin-St Jeor formula and the same safety floor we discussed, and divides calories across your daily meals. To log food, simply find its name in the list of foods and enter the amount, and its calories and macronutrients are calculated. The calorie counter is a separate module, and a new account gets a 3-day trial period." },
      { type: "cta", text: "Log your food and see how much of your calorie goal is left for today.", href: "/calorie-counter", label: "Arion calorie counter" },
    ],
    faq: [
      { q: "How many calories does my body need per day?", a: "It depends on sex, age, height, weight and activity, and there is no single fixed number for everyone. The right approach is to calculate BMR with a formula such as Mifflin-St Jeor and multiply it by an activity factor to get TDEE, or maintenance calories. Then correct it by tracking your weight over a few weeks." },
      { q: "What is the difference between BMR and TDEE?", a: "BMR is the energy the body uses at complete rest for basic functions. TDEE is the total daily energy and also includes activity, walking and exercise. TDEE is always larger than BMR and is the basis for calculating a calorie deficit or surplus." },
      { q: "How many calories should I cut to lose weight?", a: "Usually a deficit of about 15 to 20 percent below TDEE is reasonable and sustainable. A harsher deficit may bring hunger, fatigue and muscle loss. Your daily target should not fall below BMR and the common minimums. If you have a lot of weight to lose, it is better to plan with a doctor or dietitian." },
      { q: "How accurate is the Mifflin-St Jeor formula?", a: "This formula is one of the most common for ordinary people and is generally considered more accurate than older examples. Still, it is a statistical estimate and may differ by a few percent for you, which is why it should be checked against your actual weight results." },
      { q: "Do I have to count calories all the time?", a: "No. Many people count precisely for a few weeks to get a sense of appropriate portion sizes, and then continue with smart estimation. If counting causes anxiety or obsession about food, it is better to set it aside and talk to a specialist." },
    ],
    related: [
      { href: "/tools/calorie-calculator", label: "Free calorie calculator" },
      { href: "/calorie-counter", label: "Arion calorie counter" },
      { href: "/blog/how-much-protein-per-day", label: "How much protein do we need per day?" },
      { href: "/blog/what-is-bmi", label: "What is BMI and how is it calculated?" },
    ],
  },
  "sleep-cycles-best-time-to-wake-up": {
    title: "What Is a Sleep Cycle and What Is the Best Time to Wake Up?",
    metaTitle: "What Is a Sleep Cycle? The Best Time to Wake Up and Go to Sleep",
    description:
      "What a sleep cycle is, why each cycle lasts about 90 minutes, and how to calculate your bedtime and wake-up time based on cycles, with a ready-made table and examples.",
    keywords: [
      "sleep cycle",
      "best time to wake up",
      "90-minute sleep cycles",
      "sleep time calculation",
      "sleep stages",
      "deep sleep and REM",
    ],
    excerpt:
      "Sleep stages, cycles of about 90 minutes, and how to calculate your bedtime and wake-up time, with a ready-made table.",
    takeaways: [
      "A night of sleep is made of several repeating cycles, and each cycle lasts about 90 minutes on average.",
      "Waking up at the end of a cycle usually feels lighter than waking up in the middle of deep sleep.",
      "To calculate your bedtime, add the time it takes you to fall asleep (about 10 to 20 minutes).",
      "The length of a cycle varies a little from person to person and from night to night; 90 minutes is an average.",
      "This article is general information and does not replace medical advice.",
    ],
    blocks: [
      { type: "p", text: "You have probably slept 8 hours and still woken up feeling wiped out, and on another night slept only 6 hours and felt fresh. One common explanation for this difference is sleep cycles: at what point in your sleep the alarm goes off. In this article you will see what a sleep cycle is, what its stages are, and how you can plan your bedtime and wake-up time based on them." },
      { type: "p", text: "A short reminder: this article is general information, not medical advice. If your sleep has been chronically disrupted, you snore heavily, or you are excessively sleepy during the day, it is better to talk to a doctor." },
      { type: "h2", text: "What is a sleep cycle?" },
      { type: "p", text: "Night sleep is not a uniform state. Over the course of the night, the brain passes through different sleep stages several times, and each complete run through these stages is called a sleep cycle. In an adult, each cycle lasts about 90 minutes on average (usually between 80 and 110 minutes), and in a typical night about 4 to 6 cycles occur one after another." },
      { type: "h2", text: "Sleep stages" },
      { type: "p", text: "Each cycle has two main parts: non-REM sleep, which itself has three stages, and REM sleep, during which vivid dreams occur." },
      { type: "h3", text: "Light sleep (stages 1 and 2)" },
      { type: "p", text: "Stage 1 is the first moments of falling asleep; your pulse and breathing slow down and you are easy to wake. In stage 2 your body relaxes further, your temperature drops slightly, and a large part of the whole night (about half of it) is spent in this stage." },
      { type: "h3", text: "Deep sleep (stage 3)" },
      { type: "p", text: "Deep sleep, or slow-wave sleep, is the stage in which it is hard to wake someone, and if you wake up during it you feel groggy and heavy. This stage takes a larger share in the early cycles of the night (the first half). That is why sleep lost at the start of the night is the most affected by sleep deprivation." },
      { type: "h3", text: "REM sleep" },
      { type: "p", text: "In REM sleep the brain is active, the eyes move under the eyelids, and most dreams occur in this stage. As the night goes on, the length of REM sleep in each cycle increases; so in the final cycles of the morning, REM takes a larger share and sleep is lighter." },
      { type: "table", head: ["Stage", "Characteristics", "How easily do we wake up?"], rows: [
        ["1 (NREM)", "The first moments of falling asleep, slow breathing and pulse", "Very easily"],
        ["2 (NREM)", "Light sleep, the largest share of the night", "Easily"],
        ["3 (NREM)", "Deep sleep, mostly in the first half of the night", "Hard, with grogginess"],
        ["REM", "Vivid dreams, high brain activity", "Relatively easily"],
      ] },
      { type: "h2", text: "Why does the wake-up time matter?" },
      { type: "p", text: "If the alarm goes off in the middle of deep sleep, the brain has to suddenly come out of its slow state. The result is the \"morning heaviness\" known as sleep inertia, which can last up to several tens of minutes. If you wake near the end of a cycle (that is, in light sleep or close to it), the transition is smoother. This is a rough rule rather than a guarantee, because the length of a cycle varies a little each night and from person to person." },
      { type: "h2", text: "Don't forget the time it takes to fall asleep" },
      { type: "p", text: "A common mistake in these calculations is assuming that sleep starts the moment your head touches the pillow. In reality, most people take about 10 to 20 minutes to fall asleep (this is called sleep latency). So when calculating your time to lie down, add this period before the cycles begin. If you usually fall asleep faster or slower, use your own number; the common default is 15 minutes." },
      { type: "h2", text: "How to calculate your bedtime based on cycles" },
      {
        type: "ol",
        items: [
          "Decide on your desired wake-up time, for example 6:30.",
          "Choose the number of cycles: for most adults, 5 cycles (7.5 hours) or 6 cycles (9 hours) is a good target; 4 cycles (6 hours) is the minimum before it counts as sleep deprivation.",
          "Multiply the number of cycles by 90 minutes and subtract that from your wake-up time to get the time you need to fall asleep.",
          "Also subtract your personal time to fall asleep (for example 15 minutes) to find the time you should lie down.",
          "Try this schedule for a few days; if you still wake up sluggish, shift it by a few minutes, since everyone's body is slightly different.",
        ],
      },
      { type: "h2", text: "Bedtime table based on wake-up time" },
      { type: "p", text: "The table below is calculated assuming 15 minutes to fall asleep. The times are when you lie down in bed:" },
      { type: "table", head: ["Wake-up time", "6 cycles (9 hours)", "5 cycles (7.5 hours)", "4 cycles (6 hours)"], rows: [
        ["6:30", "21:15", "22:45", "0:15"],
        ["7:00", "21:45", "23:15", "0:45"],
        ["7:30", "22:15", "23:45", "1:15"],
      ] },
      { type: "h2", text: "Reverse table: if I sleep now, when should I wake up?" },
      { type: "p", text: "Sometimes your bedtime is fixed and you want to determine the alarm time. If you lie down at 23:00 and it takes you about 15 minutes to fall asleep (sleep starts at 23:15):" },
      { type: "table", head: ["Number of cycles", "Sleep duration", "Wake-up time"], rows: [
        ["4 cycles", "6 hours", "5:15"],
        ["5 cycles", "7.5 hours", "6:45"],
        ["6 cycles", "9 hours", "8:15"],
      ] },
      { type: "cta", text: "Tap your bedtime or wake-up time to see the best times based on 90-minute cycles and your own time to fall asleep.", href: "/tools/sleep-calculator", label: "Free sleep time calculator" },
      { type: "h2", text: "Some tips for better sleep cycles" },
      {
        type: "ul",
        items: [
          "Keep your bedtime and wake-up time as consistent as possible, even on weekends. A stable schedule helps your body's daily rhythm.",
          "Reduce or avoid caffeine in the late afternoon and evening; its effects stay in the body for hours.",
          "A cool, dark, quiet room, and keeping a bright phone screen away during the last hour before bed, often help you fall asleep faster.",
          "Regular exercise usually improves sleep quality, but very heavy training right before bed bothers some people.",
          "If it is late and you only have time for 4 cycles, a short 20-minute nap during the day can partly make up the shortfall.",
        ],
      },
      { type: "tip", title: "90 minutes is an average", text: "You should not follow the calculation rigidly. If you wake up ten minutes earlier or later than the table time, the world does not end. Consistency of the schedule and reaching enough total sleep matter more than mathematical precision." },
      { type: "h2", text: "If you have to sleep less" },
      { type: "p", text: "Sometimes circumstances do not allow 5 or 6 cycles of sleep: exams, travel, shift work or a newborn. In these situations, a few rules help:" },
      {
        type: "ul",
        items: [
          "If you only have 3 cycles (4.5 hours), waking at the end of the third cycle is usually better than waking in the middle of it, but this is not a substitute for enough sleep.",
          "Make up for a full cycle with a short 20-minute nap or a long 90-minute one; a nap between these two (for example 40 to 60 minutes) may leave you groggy after waking.",
          "Get morning light early; natural light helps your body clock raise alertness.",
          "Drink caffeine before noon and avoid it in the 6 hours before bed.",
          "The next night, instead of going to bed very late, go to bed one to two hours earlier to gradually pay back the debt.",
        ],
      },
      { type: "h2", text: "A few myths about sleep cycles" },
      { type: "ul", items: [
        "\"Every night is exactly 90 minutes per cycle\": in reality the length of a cycle varies, and in the first cycles it is usually shorter than in later ones.",
        "\"If I wake up at the end of a cycle I am never tired\": tiredness depends on the total length of sleep, its quality and your sleep debt as well.",
        "\"Deep sleep only needs to be one hour a night\": the amount varies with age and decreases as we get older.",
        "\"Coffee replaces sleep\": caffeine temporarily raises alertness but does not erase your sleep debt.",
      ] },
      { type: "h2", text: "Logging sleep in Arion" },
      { type: "p", text: "In the sleep section of Arion you can set a sleep goal, log your nights and see how many complete cycles you slept. The sleep section is part of the \"My Routine\" module, which gives each new account a 14-day trial. If you only want a quick number, the free calculator is enough." },
      { type: "cta", text: "Look at your sleep and daily routine side by side and build a consistent schedule.", href: "/routine", label: "My Routine on Arion" },
    ],
    faq: [
      { q: "How long is a sleep cycle?", a: "In an adult, each complete sleep cycle lasts about 90 minutes on average and usually varies between 80 and 110 minutes. The length of a cycle differs a little from night to night and from person to person, so 90 minutes is a suitable average for planning rather than an exact number." },
      { q: "How many sleep cycles per night are enough?", a: "For most adults, 5 to 6 cycles (about 7.5 to 9 hours) is a good target. 4 cycles means 6 hours, which for many people counts as sleep deprivation. The exact need depends on age, health and lifestyle; the main indicator is how alert you feel the next day." },
      { q: "Does waking at the end of a cycle really make a difference?", a: "Many people find waking at the end of a cycle gentler, because they have not been pulled out of deep sleep. However, since the length of a cycle is not exact and is only roughly calculated, the result differs for each person. The most important factor is still the duration and consistency of your sleep." },
      { q: "Why am I tired even after 8 hours of sleep?", a: "There are many reasons: waking in the middle of deep sleep, poor sleep quality due to light, noise and caffeine, an irregular sleep schedule, or conditions such as sleep apnea. If your tiredness is persistent and does not improve after adjusting your habits, it is better to consult a doctor." },
      { q: "How much time should I allow to fall asleep?", a: "For most people it is about 10 to 20 minutes, and 15 minutes is a common default. If you usually fall asleep very quickly (under 5 minutes) you may be sleep deprived, and if it regularly takes more than 30 minutes, it is worth looking for the cause or seeking advice." },
    ],
    related: [
      { href: "/tools/sleep-calculator", label: "Free sleep time calculator" },
      { href: "/blog/how-many-hours-of-sleep", label: "How many hours of sleep do we need?" },
      { href: "/routine", label: "My Routine on Arion" },
      { href: "/blog/category/sleep", label: "All sleep articles" },
    ],
  },
  "how-many-hours-of-sleep": {
    title: "How Many Hours of Sleep Do We Need Per Day?",
    metaTitle: "How Many Hours of Sleep Do You Need? Sleep Needs by Age",
    description:
      "How many hours of sleep do you need? A table of sleep needs at every age from infants to older adults, signs of sleep deprivation, and practical ways to get enough sleep each day.",
    keywords: [
      "how many hours of sleep do you need",
      "ideal sleep hours",
      "sleep needs by age",
      "sleep deprivation",
      "adult sleep hours",
      "enough sleep",
    ],
    excerpt:
      "Sleep needs at different ages, signs of sleep deprivation, and practical ways to get enough sleep.",
    takeaways: [
      "Most adults generally need about 7 to 9 hours of sleep per day.",
      "Teenagers and children need more sleep, and older adults usually need around 7 to 8 hours.",
      "The exact number is not the same for everyone; how alert you feel the next day is the best indicator.",
      "A consistent bedtime and wake-up time matters as much as the amount of sleep.",
      "This article is general information and does not replace medical advice.",
    ],
    blocks: [
      { type: "p", text: "\"How many hours should I really sleep?\" is one of the most frequently asked health questions. One person says 8 hours, another gets through the day on 5 hours, and a third is still tired after 10. In this article you will see the commonly accepted recommendations for each age group, understand why the exact number differs for each person, and learn several practical ways to get enough sleep." },
      { type: "p", text: "This article is general information and does not replace medical diagnosis or treatment. If you have a chronic sleep problem or an underlying condition, discuss it with your doctor." },
      { type: "h2", text: "Why is sleep so important?" },
      { type: "p", text: "Sleep is not just \"being switched off.\" During sleep the brain organizes the information from the day, the body repairs itself, and the regulation of hormones such as those related to appetite and stress continues. Chronic sleep deprivation is usually accompanied by reduced concentration, irritability, lower motivation and worse athletic performance. For this reason, most health guidelines present sleep, alongside nutrition and physical activity, as the third pillar of a healthy lifestyle." },
      { type: "h2", text: "Sleep needs by age" },
      { type: "p", text: "The numbers below are the common and widely accepted recommendations of specialist sleep organizations for total sleep in a 24-hour period (including naps). These are general ranges, not absolute rules:" },
      { type: "table", head: ["Age group", "Recommended sleep per 24 hours"], rows: [
        ["Newborn (0 to 3 months)", "14 to 17 hours"],
        ["Infant (4 to 11 months)", "12 to 15 hours"],
        ["Toddler (1 to 2 years)", "11 to 14 hours"],
        ["Preschool (3 to 5 years)", "10 to 13 hours"],
        ["School-age child (6 to 13 years)", "9 to 11 hours"],
        ["Teenager (14 to 17 years)", "8 to 10 hours"],
        ["Young and middle-aged adult (18 to 64 years)", "7 to 9 hours"],
        ["Older adult (65 years and over)", "7 to 8 hours"],
      ] },
      { type: "h2", text: "Adults: 7 to 9 hours" },
      { type: "p", text: "For adults aged 18 to 64, the 7 to 9 hour range is the most common recommendation. Some people function best at the lower end of this range (7 hours) and some at the upper end (9 hours). Factors affecting individual needs include genetics, physical activity level, illness, stress and even the season. Someone who trains intensely or has recently recovered from an illness usually needs more sleep." },
      { type: "h3", text: "Is 5 or 6 hours of sleep enough?" },
      { type: "p", text: "Some people say they function well on 5 or 6 hours, but sleep research has shown that people tend to underestimate how much their performance drops. A reliable test is whether you stay alert and steady during the day without an alarm clock and heavy coffee. If you depend heavily on caffeine to stay awake, you probably need more than you are sleeping." },
      { type: "h2", text: "Signs of sleep deprivation" },
      {
        type: "ul",
        items: [
          "Severe daytime sleepiness, especially when idle or driving.",
          "Needing several alarms and difficulty waking up, every day.",
          "Reduced concentration, small memory lapses and slower decision-making.",
          "Irritability, low interest and mood swings.",
          "Increased appetite, especially for sweet and high-calorie foods.",
          "Falling asleep in under 5 minutes after lying down; a sign of high sleep debt.",
        ],
      },
      { type: "h2", text: "Sleep debt cannot be repaid all at once" },
      { type: "p", text: "Most of us sleep too little on workdays and sleep 10 hours on the weekend. Catching up on weekends helps a little, but it disrupts your body clock and gives you \"social jet lag\" on Mondays. It is better to keep the difference in wake-up time between workdays and days off to a maximum of one hour, and to repay the deficit over several nights, going to bed 30 to 60 minutes earlier, rather than in a single night." },
      { type: "h2", text: "How to get enough sleep" },
      {
        type: "ol",
        items: [
          "First, decide on your consistent wake-up time, since it is usually set by your morning schedule.",
          "Count backwards from the wake-up time: your target sleep duration (for example 7.5 hours) plus about 15 minutes to fall asleep.",
          "Set a reminder to start winding down about 30 to 60 minutes before your bedtime.",
          "During this window, reduce bright light, phone screens, caffeine and heavy food.",
          "Stick with it for two weeks and compare your daytime alertness with the week before; then adjust the number a little.",
        ],
      },
      { type: "tip", title: "Use cycles to help", text: "Rather than a general hour target, try to set your sleep duration as a multiple of 90 minutes (about 6, 7.5 or 9 hours). The details are in the article on sleep cycles." },
      { type: "cta", text: "Tap your wake-up time to see when you should go to bed to get 5 or 6 full cycles.", href: "/tools/sleep-calculator", label: "Free sleep time calculator" },
      { type: "h2", text: "Factors that affect sleep needs" },
      { type: "ul", items: [
        "Genetics: individual differences in sleep need are partly hereditary, and some families are naturally shorter or longer sleepers.",
        "Activity level: heavy exercise and periods of high work or study pressure raise the need for sleep.",
        "Illness and recovery: the body needs more sleep during illness or after an injury.",
        "Pregnancy: especially in the first and last trimesters, sleep need and fatigue usually increase.",
        "Sleep quality: 8 hours of frequent, interrupted sleep may be less restorative than 7 hours of continuous sleep.",
      ] },
      { type: "h2", text: "Morning types and night owls" },
      { type: "p", text: "People's body clocks are not all the same. Some naturally go to bed early and wake early (morning types), and some feel more energetic at night and find mornings hard (night owls). Neither is bad, but problems arise when your work or study schedule does not match your body clock. If you are a night owl and can start work later, it is better to do so; if you cannot, morning light and a consistent wake-up time will gradually shift your body clock forward." },
      { type: "h2", text: "Signs that you should see a doctor" },
      { type: "ul", items: [
        "Loud, persistent snoring with breathing pauses or waking up gasping for air.",
        "Insomnia lasting more than a few weeks that disrupts daily life.",
        "Severe daytime sleepiness despite getting enough sleep.",
        "Leg movements or discomfort at night that make it hard to sleep peacefully.",
        "A sudden change in your sleep pattern without a clear reason.",
      ] },
      { type: "h2", text: "Sleep quality versus amount" },
      { type: "p", text: "Sometimes the duration of sleep is sufficient but its quality is poor. Signs of good quality include: falling asleep in under about 30 minutes, waking up no more than once or twice at night and then falling back asleep easily, and waking in the morning without multiple alarms and staying alert until noon. If you sleep about 8 hours but are tired every day, rather than adding more hours, focus on quality: keeping a consistent schedule, cooling the room, cutting caffeine in the evening and reducing screen light." },
      { type: "h2", text: "A sample plan for a good night" },
      { type: "table", head: ["Time", "Action"], rows: [
        ["About 6 hours before bed", "Your last strong coffee or tea"],
        ["About 3 hours before", "Your last heavy meal; finish intense exercise"],
        ["About 1 hour before", "Dim the room lights, set aside demanding mental tasks"],
        ["About 30 minutes before", "Calming activities: warm shower, a book, gentle stretching"],
        ["Bedtime", "Lie down in a dark, cool and quiet bed"],
      ] },
      { type: "h2", text: "Sleep and your daily routine" },
      { type: "p", text: "Good sleep usually comes from a consistent routine: a set wake-up time, a nightly reminder and logging your sleep to see the trend. In the \"My Routine\" section, Arion lets you set a sleep goal and log your nights so you can see how much you actually sleep. After the 14-day trial period, this section requires the \"My Routine\" plan." },
      { type: "cta", text: "Put your sleep, tasks and habits side by side in one daily schedule.", href: "/routine", label: "My Routine on Arion" },
    ],
    faq: [
      { q: "How many hours of sleep does an adult need?", a: "The common recommendation for adults aged 18 to 64 is about 7 to 9 hours per 24 hours. Older adults usually need 7 to 8 hours. Each person's exact need depends on genetics, health and activity level; if you have enough energy and alertness the next day, your sleep is probably adequate." },
      { q: "Is 6 hours of sleep enough?", a: "For most adults, 6 hours is less than the recommended range. You might cope for a few days, but ongoing short sleep usually affects concentration and mood. If you have no choice but to sleep less, a short nap and gradual catch-up on the following nights can help." },
      { q: "How many hours of sleep do teenagers need?", a: "The common recommendation for teenagers aged 14 to 17 is about 8 to 10 hours. At this age the body clock naturally shifts toward later bedtimes, which clashes with school start times and makes sleep deprivation common." },
      { q: "Is sleeping too much also harmful?", a: "A very long and persistent need for sleep (for example more than 9 to 10 hours in an adult without a clear reason) can sometimes be a sign of a problem such as depression, an underactive thyroid or poor sleep quality. This does not mean you should self-diagnose, but if it continues for a long time, consult a doctor." },
      { q: "How can I repay my sleep debt?", a: "The best approach is gradual repayment: go to bed 30 to 60 minutes earlier for several nights in a row and keep your wake-up time consistent. Sleeping in for a long time on one weekend day does not fully make up for the debt and disrupts your body clock." },
    ],
    related: [
      { href: "/tools/sleep-calculator", label: "Free sleep time calculator" },
      { href: "/blog/sleep-cycles-best-time-to-wake-up", label: "Sleep cycles and the best time to wake up" },
      { href: "/routine", label: "My Routine on Arion" },
      { href: "/blog/how-to-build-a-daily-routine", label: "How to build a daily routine?" },
    ],
  },
  "how-much-protein-per-day": {
    title: "How Much Protein Do We Need Per Day?",
    metaTitle: "How Much Protein Do You Need Per Day? Calculated by Body Weight",
    description:
      "How much protein do you need per day based on body weight? Grams per kilogram ranges for ordinary people and athletes, a worked example, and a table of protein in common foods.",
    keywords: [
      "daily protein needs",
      "how much protein should I eat",
      "protein by body weight",
      "protein for muscle building",
      "protein in common foods",
      "grams of protein per day",
    ],
    excerpt:
      "Your protein needs based on body weight, ranges for ordinary people and athletes, and a table of protein in common foods.",
    takeaways: [
      "For an ordinary, sedentary person, the common minimum is about 0.8 grams of protein per kilogram of body weight.",
      "For people doing resistance training, the common range is about 1.6 to 2.2 grams per kilogram.",
      "Spread your protein across meals; about 20 to 40 grams per meal suits most people.",
      "Protein values for foods are approximate and vary with cooking method and brand.",
      "If you have kidney disease or a specific condition, consult a doctor before increasing your protein.",
    ],
    blocks: [
      { type: "p", text: "Protein is one of the most important nutrients: it is needed to build and repair muscle, for enzymes, skin and many other functions in the body. However, between official recommendations, gym talk and supplement packaging, completely different numbers are heard. In this article you will calculate your daily needs with a simple formula, see how much protein common foods contain, and learn how to spread it across your meals." },
      { type: "p", text: "This article is general nutrition information and does not replace advice from a doctor or dietitian, especially if you have kidney disease, are pregnant or have another specific condition." },
      { type: "h2", text: "What does protein do?" },
      { type: "p", text: "Protein is made of amino acids. The body uses them to build muscle, repair tissues, produce enzymes and hormones, and support the immune system. The body has no large protein store like fat does, so it must be supplied regularly from food. During a calorie deficit (a weight-loss diet), enough protein also helps the body burn more fat rather than muscle, and makes you feel fuller." },
      { type: "h2", text: "Daily protein needs by body weight" },
      { type: "p", text: "Protein needs are usually expressed in grams per kilogram of body weight. The common ranges seen in sports and general nutrition sources are roughly as follows:" },
      { type: "table", head: ["Situation", "Protein (grams per kilogram of body weight)"], rows: [
        ["Sedentary adult (common minimum)", "About 0.8"],
        ["Lightly active and healthy", "About 1.0 to 1.4"],
        ["Resistance training to maintain and build muscle", "About 1.6 to 2.2"],
        ["Weight loss with training (preserving muscle)", "About 1.8 to 2.4"],
        ["Active older adult", "About 1.0 to 1.2 or a little more"],
      ] },
      { type: "p", text: "These are approximate ranges, not absolute numbers. Going above about 2.2 grams per kilogram usually brings little extra benefit for most people; it just takes room from carbohydrates and fat." },
      { type: "h2", text: "A calculation example" },
      { type: "p", text: "Suppose you weigh 75 kilograms, do bodybuilding 3 days a week, and your goal is to maintain and build muscle." },
      {
        type: "ol",
        items: [
          "Choose the range: about 1.6 to 2.2 grams per kilogram.",
          "Minimum: 75 × 1.6 = 120 grams per day.",
          "Maximum: 75 × 2.2 = 165 grams per day.",
          "Take a middle number to start with, for example 140 grams, and if you eat 4 meals, about 35 grams per meal.",
          "Stay with this number for a few weeks and adjust it based on fullness, budget and progress.",
        ],
      },
      { type: "tip", title: "If you are overweight", text: "Some sources suggest basing the calculation on your target weight or lean body mass rather than your current weight, so the number does not become unrealistically large. If you are unsure, get help from a dietitian." },
      { type: "h2", text: "Protein in common foods" },
      { type: "p", text: "The table below shows the approximate protein per 100 grams of several common foods. These figures are approximate averages from nutrition tables and vary by cooking method, fat content, brand and moisture:" },
      { type: "table", head: ["Food (100 grams)", "Approximate protein (grams)", "Notes"], rows: [
        ["Cooked chicken breast", "About 30", "Raw about 22 to 23 grams"],
        ["Cooked lean lamb or beef", "About 25 to 27", "Depends on how much fat the cut has"],
        ["Canned tuna in water", "About 24 to 26", "Ready to eat"],
        ["Whole egg", "About 12 to 13", "One medium egg is about 6 grams"],
        ["White Iranian cheese", "About 14 to 17", "High in salt; eat in small amounts"],
        ["Cooked lentils", "About 9", "Raw about 24 grams"],
        ["Cooked chickpeas", "About 8 to 9", "Raw about 19 grams"],
        ["Plain yogurt", "About 3.5 to 4", "Strained yogurt is about 8 to 10"],
        ["Milk", "About 3.4", "A 250-gram glass is about 8 grams"],
        ["Walnuts", "About 15", "High in calories"],
        ["Cooked rice", "About 2.5 to 3", "A small portion, but significant in volume"],
      ] },
      { type: "p", text: "For example, to reach 140 grams, you could have breakfast with eggs and cheese (about 25 grams), lunch with 150 grams of cooked chicken and rice (about 47 grams), a snack of strained yogurt and nuts (about 20 grams), and dinner of lentil rice or meat stew (about 40 grams)." },
      { type: "h2", text: "Plant or animal protein?" },
      { type: "p", text: "Animal protein (meat, chicken, fish, eggs, dairy) usually has all the essential amino acids in a good ratio. Most plant sources (legumes, grains, soy) lack one or two amino acids if eaten alone, but combining foods over the course of the day, such as lentils with rice or chickpeas with bread, covers this gap. For people who are vegetarian, eating a little more (about 10 percent above the numbers above) is sometimes recommended." },
      { type: "h2", text: "Spreading protein across the day" },
      { type: "p", text: "Sports nutrition research suggests that spreading protein across 3 to 5 meals, each with about 20 to 40 grams (about 0.25 to 0.4 grams per kilogram), is better for building muscle than packing most of it into one meal. The post-workout meal is important, but the \"golden window\" is not as narrow as it was once thought; the daily total matters more." },
      { type: "cta", text: "Before spreading your protein across meals, calculate your daily calories.", href: "/tools/calorie-calculator", label: "Free calorie calculator" },
      { type: "h2", text: "Is too much protein harmful?" },
      { type: "p", text: "For healthy people, protein intake within the range mentioned (up to about 2.2 grams per kilogram) is generally considered safe. However, with kidney disease, gout or some other conditions, high protein can cause problems and should be adjusted on a doctor's advice. Relying excessively on supplements rather than real food is also unnecessary; a supplement is just a convenient way to reach the number." },
      { type: "h2", text: "An example day with about 140 grams of protein" },
      { type: "table", head: ["Meal", "Example", "Approximate protein (grams)"], rows: [
        ["Breakfast", "2 eggs, 50 grams of cheese, bread", "About 25"],
        ["Snack", "1 bowl of strained yogurt and walnuts", "About 20"],
        ["Lunch", "150 grams of cooked chicken with rice and salad", "About 48"],
        ["Afternoon snack", "1 glass of milk and a handful of roasted chickpeas", "About 15"],
        ["Dinner", "Lentil rice or stew with 100 grams of meat", "About 35"],
      ] },
      { type: "p", text: "The total for this day is about 143 grams. The numbers are approximate and precision to the gram is not needed; the goal is to be in the right range on most days, not hit an exact number every day." },
      { type: "h2", text: "Common mistakes about protein" },
      { type: "ul", items: [
        "Counting the weight of food instead of its protein: 100 grams of cooked chicken is not 100 grams of protein; it has about 30 grams.",
        "Eating all your protein in one dinner and leaving the rest of the day empty.",
        "Putting all your hope in shakes and supplements while ignoring whole food.",
        "Forgetting enough calories: without sufficient energy, the body burns some of the protein for fuel.",
        "Being needlessly afraid of protein if you are healthy, or on the other hand, eating far more than needed hoping for faster results.",
      ] },
      { type: "h2", text: "Protein and weight loss" },
      { type: "p", text: "When you cut calories, the body tends to lose some muscle too. Higher protein intake combined with resistance training reduces this loss. Protein is also more filling than carbohydrates and fat and has a higher thermic effect, so staying on a lighter diet is easier for many people." },
      { type: "h2", text: "Logging protein in Arion" },
      { type: "p", text: "In the Arion calorie counter you can log foods with their amounts and see calories and macronutrients (protein, carbohydrates and fat) for each meal and for the whole day. The calorie counter is a separate module, and a new account gets a 3-day trial." },
      { type: "cta", text: "Log today's food and see whether you have reached your protein target.", href: "/calorie-counter", label: "Arion calorie counter" },
    ],
    faq: [
      { q: "How many grams of protein should I eat per day?", a: "For a sedentary adult, about 0.8 grams per kilogram of body weight is common, and for people doing resistance training, about 1.6 to 2.2 grams per kilogram. For example, a 70-kilogram person who does bodybuilding usually targets about 110 to 155 grams per day." },
      { q: "How much protein is needed for building muscle?", a: "The common range is about 1.6 to 2.2 grams per kilogram of body weight per day. More than this usually does not add benefit. Sufficient calories, training with progressive overload and sleep are just as important as protein for muscle growth." },
      { q: "Can I get enough protein without supplements?", a: "Yes. Chicken, meat, fish, eggs, dairy and legumes can get you to your target. Supplements are not necessary and only help when reaching the number with food is difficult or time-consuming. Real food also provides micronutrients and fiber in addition to protein." },
      { q: "How much protein do an egg and a chicken breast have?", a: "A medium egg has about 6 grams of protein. 100 grams of cooked chicken breast has about 30 grams. These numbers are approximate and vary a little depending on size and cooking method." },
      { q: "Does high protein damage the kidneys?", a: "In healthy people, protein intake within the range recommended for athletes has no strong evidence of kidney damage. However, people who have or have had kidney disease should change their protein intake only on a doctor's advice." },
    ],
    related: [
      { href: "/tools/calorie-calculator", label: "Free calorie calculator" },
      { href: "/blog/how-to-count-daily-calories", label: "Calculating daily calories and calorie deficit" },
      { href: "/calorie-counter", label: "Arion calorie counter" },
      { href: "/blog/how-to-write-a-bodybuilding-program", label: "How to write a bodybuilding program?" },
    ],
  },
  "beginner-gym-program-3-days": {
    title: "3-Day Bodybuilding Program for Beginners (Full Example)",
    metaTitle: "3-Day Bodybuilding Program for Beginners | Full Example with Sets and Reps",
    description:
      "A beginner's 3-day bodybuilding program with a complete table of exercises, sets and reps, progressive overload, warm-up, rest, and common beginner mistakes at the gym.",
    keywords: [
      "3-day bodybuilding program",
      "beginner bodybuilding program",
      "beginner gym workout plan",
      "full body workout",
      "beginner sets and reps",
      "starting bodybuilding",
    ],
    excerpt:
      "A complete 3-day bodybuilding program for beginners: exercises, sets and reps, progressive overload and rest.",
    takeaways: [
      "For a beginner, three full-body sessions per week with a rest day between them is enough and effective.",
      "Each session focuses on basic movements (squat, press, row, Romanian deadlift).",
      "Good form matters more than heavy weight; progress gradually and track your workouts.",
      "Every 4 to 6 weeks, a lighter week (a deload) gives your body a chance to recover.",
      "If you have an illness or injury, consult a doctor or physiotherapist before starting.",
    ],
    blocks: [
      { type: "p", text: "If you are just starting bodybuilding, the biggest danger is making things complicated: 6-day programs, strange exercises and a long list of supplements. The reality is that a beginner with a simple, consistent program, three days a week, can see significant progress in the first few months. In this article you will see a complete 3-day full-body program you can start right now, along with how to progress and common mistakes." },
      { type: "p", text: "This program is a general example. If you have a heart condition, a joint problem, high blood pressure or an injury, consult a doctor before starting." },
      { type: "h2", text: "Why 3 days of full body for beginners?" },
      { type: "p", text: "In a full-body program, every session trains all the main muscle groups. That means each muscle is stimulated 3 times a week, which is ideal for beginners: movement skills are learned faster, the volume of each session stays balanced, and there is a full rest day between sessions (for example Saturday, Monday, Wednesday) for recovery." },
      { type: "h2", text: "Before you start" },
      {
        type: "ul",
        items: [
          "Fix your training days: for example Saturday, Monday and Wednesday, or Sunday, Tuesday and Thursday. Leave at least one day between two sessions.",
          "Each session should take about 50 to 60 minutes, including warm-up.",
          "Have a notebook or app to record the weights and reps.",
          "If you do not know the machines, ask the gym coach to show you the form once.",
        ],
      },
      { type: "h2", text: "Warm-up (before every session)" },
      {
        type: "ol",
        items: [
          "5 to 8 minutes of light general movement: stationary bike, treadmill on a small incline or skipping rope.",
          "A few dynamic movements: arm and shoulder circles, hip rotations, bodyweight squats, cat-camel.",
          "One or two light sets of your first main exercise with a light weight, before your working sets.",
        ],
      },
      { type: "h2", text: "The 3-day program table" },
      { type: "p", text: "All days have a similar structure, but two versions, A and B, alternate between sessions to give a more varied movement pattern. Week one: A, B, A; the next week: B, A, B." },
      { type: "h3", text: "Session A" },
      { type: "table", head: ["Exercise", "Sets", "Reps", "Rest"], rows: [
        ["Squat with dumbbells or a light barbell (or goblet squat)", "3", "8 to 10", "90 to 120 seconds"],
        ["Chest press with dumbbells or machine", "3", "8 to 12", "90 seconds"],
        ["Seated cable row or dumbbell bent-over row", "3", "8 to 12", "90 seconds"],
        ["Dumbbell overhead press", "2", "10 to 12", "60 to 90 seconds"],
        ["Plank", "3", "20 to 40 seconds", "45 seconds"],
      ] },
      { type: "h3", text: "Session B" },
      { type: "table", head: ["Exercise", "Sets", "Reps", "Rest"], rows: [
        ["Romanian deadlift with dumbbells or a light barbell", "3", "8 to 10", "90 to 120 seconds"],
        ["Lat pulldown (or assisted pull-up)", "3", "8 to 12", "90 seconds"],
        ["Dumbbell incline press", "3", "8 to 12", "90 seconds"],
        ["Lunge or leg press", "2", "10 to 12 per leg", "60 to 90 seconds"],
        ["Biceps and triceps (light superset)", "2", "10 to 15", "60 seconds"],
        ["Crunch or knee raise", "3", "10 to 15", "45 seconds"],
      ] },
      { type: "h3", text: "Sample week" },
      { type: "table", head: ["Day", "Plan"], rows: [
        ["Saturday", "Session A"],
        ["Sunday", "Rest or light walk"],
        ["Monday", "Session B"],
        ["Tuesday", "Rest"],
        ["Wednesday", "Session A (next week B)"],
        ["Thursday and Friday", "Full rest, enough sleep and good nutrition"],
      ] },
      { type: "h2", text: "Choosing weight and intensity" },
      { type: "p", text: "For each exercise, choose a weight that lets you finish the sets with clean form and leaves 2 to 3 reps in reserve at the end of each set (meaning you could have done 2 to 3 more reps). In the first few weeks you do not need to reach complete failure. The goal is to learn the movement pattern and let your joints and tendons adapt." },
      { type: "h2", text: "Progressive overload: how to progress" },
      {
        type: "ol",
        items: [
          "Weeks 1 and 2: light weight, focus on form, and each exercise at the bottom of the rep range (for example 8).",
          "From week 3: in each session, try to get one more rep in one or two sets.",
          "When all sets of an exercise reach the top of the rep range (for example 12), increase the weight by about 2.5 kg for upper body or 5 kg for lower body, and start again from 8.",
          "Record the weight and reps in every session; if you cannot maintain the reps for two sessions in a row, lower the weight a little.",
          "Every 4 to 6 weeks, take a lighter week (about 60 percent of the weight) so that your whole body can recover.",
        ],
      },
      { type: "tip", title: "Form first", text: "If your form breaks down on the last reps, stop the set there. A heavier weight with bad form is not progress; it just raises the risk of injury. Filming your sets from the side is the simplest way to check your form." },
      { type: "h2", text: "Nutrition and sleep for beginners" },
      { type: "p", text: "Even the best program does not work without food and enough sleep. In short: calculate your daily calories for your goal (for muscle building, near maintenance or slightly above; for fat loss, slightly below), aim for about 1.6 to 2 grams of protein per kilogram of target body weight per day, and sleep 7 to 9 hours. Details on these topics are in the calorie and protein articles on this blog." },
      { type: "cta", text: "Calculate your daily calorie needs for your bodybuilding goal.", href: "/tools/calorie-calculator", label: "Free calorie calculator" },
      { type: "h2", text: "Common beginner mistakes" },
      {
        type: "ul",
        items: [
          "Starting with a heavy weight and poor form to impress others.",
          "Training every day without rest; muscle grows during recovery.",
          "Skipping the warm-up because of lack of time.",
          "Constantly switching programs before giving it 6 to 8 weeks.",
          "Ignoring the lower body and focusing only on chest and arms.",
          "Not recording weights and not comparing your progress with your own previous weeks.",
        ],
      },
      { type: "h2", text: "What to do after 8 to 12 weeks?" },
      { type: "p", text: "Once you know the basic movements and your weights have been going up steadily, you can move to a 4-day upper/lower program or Push/Pull/Legs. The principles for choosing a program are in the article \"How to write a bodybuilding program.\"" },
      { type: "h2", text: "A brief guide to the main exercises" },
      { type: "h3", text: "Squat" },
      { type: "p", text: "Feet slightly wider than shoulder width, toes turned slightly out, chest up and lower back neutral. Push your hips back and down as if sitting onto a chair until your thighs are close to parallel with the floor, then drive up through the whole foot. Keep your knees in line with your toes and do not let them cave inward." },
      { type: "h3", text: "Chest press" },
      { type: "p", text: "Pull your shoulder blades back and down, keep your feet firmly on the floor and your wrists in line with your forearms. Lower the weight under control to near your chest and press it up without locking your elbows hard." },
      { type: "h3", text: "Row" },
      { type: "p", text: "Keep your back straight and chest forward, pull your elbows toward your hips and bring your shoulder blades together at the end of the movement. Avoid swinging your upper body to lift the weight." },
      { type: "h3", text: "Romanian deadlift" },
      { type: "p", text: "Keep your knees slightly bent and fixed, push your hips back as if closing a car door, and lower the weight close to your legs until you feel a stretch in the back of your thighs; then return by driving your hips forward. Your back stays straight throughout the movement." },
      { type: "h2", text: "If you do not have machines or free weights" },
      { type: "p", text: "You can replace squats with bodyweight squats or goblet squats with a heavy water bottle, the chest press with push-ups, the row with a resistance band or a heavy backpack, and the deadlift with a band or a good morning exercise. The principle does not change: basic movements, appropriate reps, tracking and progressive overload." },
      { type: "h2", text: "Separating muscle soreness from injury pain" },
      { type: "p", text: "A dull, spread-out muscle soreness that appears 1 to 3 days after a new training program is usually normal and improves with light exercise and movement. However, sharp, localized pain in a joint or tendon, swelling, numbness, or pain that gets worse over several days is a sign of injury. Stop training that area, and if it continues, see a doctor or physiotherapist." },
      { type: "h2", text: "Building a program in Arion" },
      { type: "p", text: "If you do not want to build the program yourself, Arion creates a weekly program based on your goal, experience, training days and any physical limitations, and tracks your workout progress. Bodybuilding is a separate module, and a new account gets a 3-day trial." },
      { type: "cta", text: "Build a bodybuilding program that matches your goal and your free days.", href: "/bodybuilding-program", label: "Arion bodybuilding program" },
    ],
    faq: [
      { q: "Is 3 days a week enough for a beginner?", a: "Yes. For a beginner, three full-body sessions a week with a rest day between them usually provide enough stimulus to learn the movements and make early progress. Results depend more on consistency, nutrition and sleep than on the number of days. More days can be added later if needed." },
      { q: "How long should a beginner's bodybuilding session take?", a: "About 45 to 60 minutes including warm-up is enough for most beginners. Longer sessions are not necessarily better and may increase fatigue. What matters is doing your main sets with quality and correct form and respecting your rest periods." },
      { q: "Should I do cardio or weights first?", a: "For strength and volume goals, weights are usually recommended first, followed by light cardio, so that your energy is preserved for the main movements. Only a light 5 to 8 minute warm-up is needed before weights. More cardio can be done on separate days or after training." },
      { q: "How many weeks until I see results?", a: "Strength usually goes up within the first few weeks because your nervous system learns the movements. Visible changes in muscle and fat usually take from a few weeks to several months, depending on nutrition, sleep and genetics. No one can promise a definite, fast result; consistency is the most important factor." },
      { q: "What should I do if I miss a session?", a: "Do not worry. Move that session to the next day, or let it go and follow your program for the next session. Making up for it with two sessions back to back or suddenly increasing the weight is not recommended. If you have not trained for several weeks, come back with lighter weights." },
    ],
    related: [
      { href: "/bodybuilding-program", label: "Arion AI bodybuilding program" },
      { href: "/blog/how-to-write-a-bodybuilding-program", label: "How to write a bodybuilding program?" },
      { href: "/blog/how-much-protein-per-day", label: "How much protein do we need per day?" },
      { href: "/tools/calorie-calculator", label: "Free calorie calculator" },
    ],
  },
  "what-is-bmi": {
    title: "What Is BMI and How Is It Calculated?",
    metaTitle: "What Is BMI? The Body Mass Index Formula and Chart",
    description:
      "What is BMI, or body mass index? The calculation formula with an example, the WHO classification chart, the limits of BMI, and when it can be misleading.",
    keywords: [
      "what is BMI",
      "body mass index",
      "BMI calculation",
      "BMI formula",
      "BMI chart",
      "ideal weight",
    ],
    excerpt:
      "The BMI formula with an example, the WHO classification chart, and the limitations of this index.",
    takeaways: [
      "BMI is calculated by dividing weight (kilograms) by height (meters) squared.",
      "The normal range in the WHO classification is 18.5 to 24.9.",
      "BMI is only a screening index and does not see body composition (muscle and fat).",
      "It should be interpreted with caution for athletes, older adults and teenagers.",
      "This article is general information; see a doctor to assess your own health.",
    ],
    blocks: [
      { type: "p", text: "BMI is one of the best-known numbers we hear about weight, from the doctor's office to health apps. But many of us do not know where this number comes from, exactly what it shows, and what it does not show. In this article you will learn the BMI formula with an example, see the classification chart, and understand why you should not rely on a single number." },
      { type: "p", text: "This article is general information and does not replace medical advice. Interpreting BMI for any person's health should take into account age, medical history and body composition." },
      { type: "h2", text: "What does BMI mean?" },
      { type: "p", text: "BMI stands for body mass index. It is a number that shows the ratio of weight to height, and it is used in medicine and public health research for initial screening; that is, to quickly and cheaply find out whether a person may be in the underweight or overweight category. This index was proposed in the nineteenth century by a Belgian mathematician named Adolphe Quetelet." },
      { type: "h2", text: "The BMI formula" },
      { type: "table", head: ["Unit", "Formula"], rows: [
        ["Metric (the standard in Iran)", "BMI = weight (kg) ÷ (height in meters)²"],
        ["Height in centimeters", "BMI = weight (kg) ÷ (height in cm)² × 10000"],
      ] },
      { type: "h3", text: "A step-by-step example" },
      { type: "p", text: "Suppose your weight is 72 kilograms and your height is 175 centimeters:" },
      {
        type: "ol",
        items: [
          "Convert height to meters: 175 centimeters = 1.75 meters.",
          "Square the height: 1.75 × 1.75 = 3.0625.",
          "Divide the weight by this number: 72 ÷ 3.0625 = about 23.5.",
          "Compare 23.5 with the chart: it falls within the normal range (18.5 to 24.9).",
        ],
      },
      { type: "cta", text: "Enter your height and weight to see your BMI and its category instantly.", href: "/tools/bmi-calculator", label: "Free BMI calculator" },
      { type: "h2", text: "BMI classification chart (World Health Organization)" },
      { type: "p", text: "The World Health Organization (WHO) uses this classification for adults over 18 years of age:" },
      { type: "table", head: ["BMI", "Category"], rows: [
        ["Below 18.5", "Underweight"],
        ["18.5 to 24.9", "Normal weight"],
        ["25 to 29.9", "Overweight"],
        ["30 to 34.9", "Obesity class 1"],
        ["35 to 39.9", "Obesity class 2"],
        ["40 and above", "Obesity class 3"],
      ] },
      { type: "p", text: "For some populations, such as Asian populations, the WHO has noted that the risk of metabolic problems starts at a lower BMI, and some countries use stricter thresholds for overweight. So if your BMI is borderline, it is better to talk to your own doctor." },
      { type: "h2", text: "What does BMI not show?" },
      { type: "p", text: "BMI only sees weight and height. This means it is blind to several important things:" },
      {
        type: "ul",
        items: [
          "Body composition: muscle is heavier than fat. A muscular athlete may have a BMI above 25 without having much fat.",
          "Fat distribution: fat around the abdomen (visceral fat) is usually more dangerous than fat in other parts of the body, but BMI does not distinguish between them.",
          "Age and sex: with age, muscle decreases and fat increases even if weight stays the same. Men and women also have different normal body fat percentages.",
          "Skeletal structure and height: the index is less accurate for people who are very tall or very short.",
          "Children and teenagers: for them, age- and sex-specific percentile charts are used, not the adult chart.",
          "Pregnancy: BMI is not a suitable measure during pregnancy.",
        ],
      },
      { type: "h2", text: "Indicators that complement BMI" },
      { type: "p", text: "Doctors and specialists usually look at BMI alongside other indicators. Waist circumference is a simple and useful one; for example, a waist above about 94 centimeters in men and 80 centimeters in women is cited in international sources as a threshold for increased risk. The waist-to-height ratio (usually recommended to stay below one half), body fat percentage, blood pressure and blood tests also help." },
      { type: "tip", title: "A signal, not a verdict", text: "Treat BMI as an early warning light, not a health score. A normal number does not guarantee health, and a high number is not necessarily a disease. The trend of weight changes, waist circumference, energy levels and test results give a fuller picture." },
      { type: "h2", text: "From BMI to a target weight" },
      { type: "p", text: "If you want to know what weight corresponds to the normal BMI range for your height, reverse the formula: weight = BMI × (height in meters)². For a height of 1.75 meters: the lowest weight in the normal range is 18.5 × 3.0625 = about 56.7 kilograms, and the highest is 24.9 × 3.0625 = about 76.3 kilograms. This is a range, not a magic number. The right weight for each person within this range depends on muscle, age and health." },
      { type: "h2", text: "What should I do if my BMI is outside the normal range?" },
      {
        type: "ol",
        items: [
          "Do not worry, and do not treat one number as the end of the story; first look at your waist circumference, overall appearance and activity level.",
          "If your BMI is very low or very high, speak with a doctor or dietitian so the necessary checks can be done.",
          "Focus your goal on habits: regular movement, enough sleep, balanced nutrition and tracking trends, not just the number on the scale.",
          "For weight change, choose a reasonable and gradual pace; set your calorie deficit or surplus based on your own TDEE.",
        ],
      },
      { type: "h2", text: "BMI across different groups" },
      { type: "h3", text: "Athletes and muscular people" },
      { type: "p", text: "A bodybuilder or strength athlete with high muscle mass may have a BMI between 26 and 30 while having a low body fat percentage. In this group, body fat percentage, waist circumference and body measurements are more informative than BMI." },
      { type: "h3", text: "Older adults" },
      { type: "p", text: "With age, height decreases slightly and muscle turns into fat. In older adults, a BMI a bit higher than the young adult range is sometimes considered harmless or even protective, while a very low BMI is associated with weakness and increased risk. Interpretation should be done with a doctor." },
      { type: "h3", text: "Pregnancy and breastfeeding" },
      { type: "p", text: "During pregnancy, weight rises for natural reasons, so the current BMI is not a suitable measure. Doctors usually use the BMI from before pregnancy to set an appropriate range for weight gain." },
      { type: "h2", text: "Common mistakes when using BMI" },
      { type: "ul", items: [
        "Recording height in shoes or weight in heavy clothing, which can change the number by a few tenths.",
        "Comparing your number with others without considering age, sex and body composition.",
        "Believing that reaching an \"ideal\" BMI is the ultimate health goal.",
        "Using the adult chart for children and teenagers.",
        "Relying on BMI for severe diet decisions without professional advice.",
      ] },
      { type: "h2", text: "A small exercise: see where you stand in your range" },
      { type: "ol", items: [
        "Measure your weight and height under the same conditions (morning, fasting, no shoes).",
        "Calculate your BMI with the formula or a calculator and check its category.",
        "Measure your waist at the level of your navel with a flexible tape.",
        "Repeat these measurements every one to two months and note the trend.",
        "If the trend is worrying or you have doubts, discuss the results with a doctor.",
      ] },
      { type: "p", text: "To turn your goal into a calorie number, the article \"Calculating daily calories\" in this blog explains it step by step. In Arion you can also track your weight and calorie goal in the calorie counter section; this section is a separate module, and a new account gets a 3-day trial." },
      { type: "cta", text: "Calculate your daily calorie target based on your height, weight and activity.", href: "/tools/calorie-calculator", label: "Free calorie calculator" },
    ],
    faq: [
      { q: "What is BMI and how is it calculated?", a: "BMI, or body mass index, is obtained by dividing weight in kilograms by height in meters squared. For example, a weight of 72 kilograms and a height of 1.75 meters gives a BMI of 72 ÷ 3.0625, or about 23.5. This index is a simple screening tool and not a medical diagnosis." },
      { q: "What is a normal BMI?", a: "According to the WHO classification for adults, a BMI between 18.5 and 24.9 is normal. Below 18.5 is underweight, 25 to 29.9 is overweight, and 30 and above is considered obesity. These categories apply to people over 18 and are not precise for every group." },
      { q: "Why is BMI misleading for athletes?", a: "Because BMI only sees weight and height and does not distinguish between muscle and fat weight. Muscle is denser, so a muscular athlete may have a high BMI without much fat. For them, body fat percentage and waist circumference are better measures." },
      { q: "Is BMI the same for children and teenagers?", a: "No. For people under 18, BMI is interpreted using percentile charts specific to age and sex, and the adult chart does not apply. Because the body is still growing, interpretation should be done with a doctor or pediatric dietitian." },
      { q: "Is BMI alone enough to assess health?", a: "No. BMI is a simple, general index. For a fuller picture, waist circumference, body fat percentage, blood pressure, blood sugar and blood fats, activity level and lifestyle habits are also examined. For an accurate assessment of your health, see a doctor." },
    ],
    related: [
      { href: "/tools/bmi-calculator", label: "Free BMI calculator" },
      { href: "/blog/how-to-count-daily-calories", label: "Calculating daily calories and calorie deficit" },
      { href: "/calorie-counter", label: "Arion calorie counter" },
      { href: "/blog/how-much-protein-per-day", label: "How much protein do we need per day?" },
    ],
  },
};
