import type { BlogPostEn } from "./types";

// ترجمه‌ی ../trading.ts — کلید = slug
export const TRADING_POSTS_EN: Record<string, BlogPostEn> = {
  "what-is-a-trading-journal": {
    title: "What Is a Trading Journal and How Do You Keep One?",
    metaTitle: "What Is a Trading Journal? A Guide to Keeping a Trading Journal",
    description:
      "What a trading journal is, which fields it should contain, and how a regular weekly review helps you spot the repeated mistakes in your trading. A step-by-step guide for forex traders.",
    keywords: ["trading journal", "trade journal", "forex journal", "trade log", "trader performance analysis", "what is a trading journal"],
    excerpt: "What to record for every trade, and how a journal helps you see your repeated patterns.",
    takeaways: [
      "A trading journal is a log that records every trade along with the reason for entry, the risk, and your mental state.",
      "The real value of a journal lies in periodic review, not in the act of recording. Without review, it is just an archive.",
      "R-multiple (result divided by initial risk) makes trades of different sizes comparable.",
      "Record every trade, especially losses and trades taken outside your plan.",
    ],
    blocks: [
      { type: "p", text: "Ask a few experienced traders which habit has had the biggest impact on their work, and many of them will say keeping a journal. A trading journal is a log in which you write down every trade in detail: what you traded, at what size, for what reason, with what risk, in what state of mind, and what the outcome was. The log is not meant to predict the market. Its job is to give you real data in front of you after a few dozen trades, instead of guesses about yourself." },
      { type: "p", text: "In this guide you will learn what a journal actually is, why memory cannot replace it, which fields are worth recording, how a weekly review is done, and which mistakes to avoid." },
      { type: "h2", text: "What exactly is a trading journal?" },
      { type: "p", text: "A trading journal, or trade journal, is a structured history of your trades. It can be a paper notebook, a spreadsheet, or a dedicated tool. The format does not matter much; what matters is that every trade is recorded with the same fields, so you can compare trades with each other and summarize them." },
      { type: "p", text: "A journal is different from your broker’s trade history. The broker history only tells you what was traded, when, and with what result. It does not say why you entered, how much risk you took, whether you followed your plan, or how you felt at the time. These “why” parts are exactly what changes behavior." },
      { type: "h2", text: "Why is memory not enough?" },
      { type: "p", text: "Memory is not neutral about trades. Winning trades stay clearer in your mind, and the reasons behind bad decisions are usually reconstructed later rather than actually remembered. A week on, a loss you took after moving your stop loss can turn into “the market hunted my stop,” while the entry in your journal would have shown that you moved the stop yourself." },
      { type: "p", text: "Another point is sample size. You might take 40 trades in a month. No mind can hold 40 trades with all their details and calculate accurate statistics from them. A journal does this work for you." },
      { type: "h2", text: "What should you record?" },
      { type: "p", text: "Divide your fields into four groups. The first group covers trade bookkeeping, the second covers risk, the third covers decision logic, and the fourth covers behavior." },
      { type: "table", head: ["Group", "Field", "Why it matters"], rows: [
        ["Basic", "Symbol, direction (buy or sell), size", "Shows exactly what was traded"],
        ["Basic", "Entry and exit time, entry and exit price", "Allows analysis by session, weekday, and holding time"],
        ["Risk", "Stop loss, take profit, initial risk (amount or percentage)", "The basis for R and the risk-to-reward ratio"],
        ["Risk", "Final result (amount and R)", "Makes trades of different sizes comparable"],
        ["Logic", "Setup or strategy, reason for entry, reason for exit", "Shows which setups actually work"],
        ["Logic", "Timeframe and chart screenshot", "Lets you review visually later, without relying on memory"],
        ["Behavior", "Mental state before and after, whether you followed the plan", "Separates ordinary losses from losses caused by lack of discipline"],
      ] },
      { type: "h3", text: "Risk and R" },
      { type: "p", text: "R is the unit of risk. If you risk 50 dollars on a trade and make 100 dollars, the result is +2R. If you lose 50 dollars, the result is -1R. With R you can combine a trade of 0.1 lots and a trade of 2 lots in the same statistics. Without recording the initial risk, this calculation is impossible." },
      { type: "h3", text: "Reason for the decision" },
      { type: "p", text: "Write one or two sentences, such as “Broke resistance at 1.0850 with a confirming candle and high volume” or “Bounce from the daily support.” At the moment you record it, this section may seem unimportant. But a month later, when you are reviewing, it is the most valuable column in the journal, because it lets you group trades by setup." },
      { type: "h3", text: "Mental state and adherence to the plan" },
      { type: "p", text: "Write your state before and after the trade as a word or a number from 1 to 5, and record whether you followed the plan. If most of your big losses are marked “not according to plan,” the problem is not the strategy; the problem is execution, and the solution is different." },
      { type: "tip", title: "Keep entries short", text: "If logging a single trade takes more than two or three minutes, you will stop after a few days. Keep only the fields you actually use in your review and remove the rest." },
      { type: "h2", text: "How is a weekly review done?" },
      { type: "p", text: "Recording without review is just archiving. A weekly review does not need to be long; half an hour at the end of the week is enough. Follow these steps:" },
      { type: "ol", items: [
        "Read through all the trades of the week in order and check whether each one followed the plan.",
        "Split the trades into two groups, “according to plan” and “outside the plan,” and total the R of each group separately.",
        "Look at where the biggest losses came from: which setup, which session, or which weekday.",
        "Find a repeated pattern, for example “after two losses in a row I increase my size.”",
        "For the following week, write down just one clear rule that targets that pattern.",
      ] },
      { type: "p", text: "The principle of “one change per period” matters. If you change your strategy, your size, and your trading hours all at once, you will not know which change made the difference." },
      { type: "h2", text: "Which statistics are worth tracking?" },
      { type: "p", text: "Win rate on its own is misleading. A system with a 40 percent win rate can still be profitable, as long as its average win is large enough compared with its average loss. The measures that are most useful are:" },
      { type: "ul", items: [
        "Average R: the average result per trade, measured in units of risk. If it is positive, the system had an edge in this sample.",
        "Profit factor: total profits divided by total losses. Above 1 means you were profitable overall.",
        "Maximum drawdown: the largest drop from peak to trough. It shows how much financial and emotional hardship you need to be able to tolerate.",
        "Longest losing streak: so you know in advance how long a bad run can last.",
      ] },
      { type: "p", text: "An important warning: the statistics of a small sample are not reliable. Ten or fifteen trades do not prove anything yet. Collect at least several dozen trades and read the results with caution." },
      { type: "h2", text: "Common mistakes in keeping a journal" },
      { type: "ul", items: [
        "Not recording losses or trades outside the plan. This makes your statistics look better than reality and makes the journal useless.",
        "Recording late. A week later, the real reason for a decision has slipped from your mind and been replaced by a justification.",
        "Too many fields. Every extra field increases the chance you will abandon the journal.",
        "Never reviewing. A journal that is never read has no effect.",
        "Judging by a single trade. Patterns only appear across a set of trades, not in one win or one loss.",
      ] },
      { type: "h2", text: "Trading journal in Arion" },
      { type: "p", text: "Arion has all the fields above and calculates the statistics itself: profit and loss, win rate, average win and loss, average R, profit factor, streaks, maximum drawdown, and a monthly profit and loss calendar. The entry checklist is also saved at the moment a trade is recorded, so you can later see which trades were opened with a complete checklist and which were not. The trading module comes with a 3-day trial period for new accounts." },
      { type: "cta", text: "See Arion’s trading journal and how it records and analyzes your trades.", href: "/trading-journal", label: "Arion trading journal" },
      { type: "p", text: "If you still choose your trade size by feel, it is worth calculating size from your risk before you start a journal. The free lot size calculator helps with this step." },
      { type: "cta", text: "Calculate your lot size from your risk percentage and the distance to your stop loss.", href: "/tools/lot-size-calculator", label: "Lot size calculator" },
      { type: "p", text: "This is educational content only. Trading in financial markets carries risk, and you may lose part or all of your capital. This article is for education only and is not financial or investment advice." },
    ],
    faq: [
      { q: "What is a trading journal?", a: "A trading journal is a log that records every trade with a fixed set of fields: symbol, direction, size, prices, stop loss and take profit, reason for entry and exit, result, and mental state. Its purpose is to let you see the real patterns in your behavior and performance after a few dozen trades." },
      { q: "Where should I keep a trading journal? Spreadsheet or a dedicated tool?", a: "Both work. A spreadsheet is flexible, but you have to build the statistics and charts yourself. A dedicated journal tool calculates the statistics automatically. The right choice is whichever you will use every day, because consistency matters more than the tool." },
      { q: "How many trades do I need before the journal statistics mean anything?", a: "There is no magic number, but you cannot draw conclusions from 10 or 15 trades. Usually you need at least several dozen trades with one clearly defined strategy, and even then the results should be interpreted with caution." },
      { q: "What does R mean in a trading journal?", a: "R is the unit of your initial risk on each trade. If you risk 50 dollars and make 100 dollars, the result is +2R. With R you can compare trades of different sizes and amounts in a single set of statistics." },
      { q: "How often should I review my journal?", a: "A short weekly review of about half an hour and a deeper monthly review are enough for most traders. What matters is that in each period you look for one repeated pattern and set just one new rule for the next period." },
    ],
    related: [
      { href: "/trading-journal", label: "Arion trading journal" },
      { href: "/blog/trading-checklist-before-entry", label: "Entry checklist for trades" },
      { href: "/blog/risk-reward-ratio", label: "What is the risk-to-reward ratio?" },
      { href: "/blog/forex-money-management", label: "Money management in forex" },
    ],
  },
  "forex-sessions-best-trading-hours-iran-time": {
    title: "Forex Sessions and the Best Trading Hours in Iran Time",
    metaTitle: "Best Forex Trading Hours in Iran Time",
    description:
      "The Sydney, Tokyo, London, and New York session hours in Iran time during summer and winter, which window has the most liquidity in forex, and how daylight saving time changes things.",
    keywords: ["best forex trading hours", "forex market hours in Iran time", "forex sessions", "London session hours", "New York session hours", "forex trading schedule"],
    excerpt: "What time the forex sessions are in Iran time, and which overlap window has the most liquidity.",
    takeaways: [
      "The forex market is open 24 hours, but it is not equally active at all times. Four sessions (Sydney, Tokyo, London, and New York) set the rhythm of the day.",
      "The overlap of London and New York is usually the most liquid window of the day.",
      "Iran does not observe daylight saving time, but London and New York do, so the session times in Tehran shift by one hour between summer and winter.",
      "Session start and end times are conventions and brokers differ slightly; treat the table as an approximate guide.",
    ],
    blocks: [
      { type: "p", text: "One of the most common questions among Iranian traders is: “What is the best time to trade forex in Iran time?” The short answer is that the market is open at all hours, but it does not behave the same way at all of them. The precise answer depends on which currency pair you trade, what volatility your strategy needs, and how your time in Tehran lines up with London and New York. In this article you will see the hours of each session for summer and winter, and learn how to choose your own trading hours." },
      { type: "h2", text: "Why does forex have sessions?" },
      { type: "p", text: "The forex market is not centralized. It is traded among banks, brokers, and financial institutions around the world. When the working day of a major financial center begins, trading volume rises in the currency pairs linked to that center. For this reason the trading day is split into four sessions based on the four main financial centers, and each session has its own volume and character." },
      { type: "h2", text: "The four main sessions" },
      { type: "ul", items: [
        "Sydney: the week opens with this session. Its volume is lower, but it matters for the Australian and New Zealand dollars.",
        "Tokyo: the Asian session. Most activity is in the Japanese yen and other Asian currency pairs, and price usually moves more calmly than in London.",
        "London: the largest session by trading volume, with heavy activity in the euro, the pound, and the Swiss franc.",
        "New York: the American session and the dollar. Most major US economic news is released during this session.",
      ] },
      { type: "h2", text: "Session times in Tehran time" },
      { type: "p", text: "The local hours shown in the table are: Sydney 07:00 to 16:00, Tokyo 09:00 to 18:00, London 08:00 to 16:30, and New York 08:00 to 17:00. These hours are conventions, and sources differ slightly. Iran has not observed daylight saving time since 1401 and stays on UTC+3:30 all year. London is on UTC+1 in summer and UTC+0 in winter, and New York is on UTC-4 in summer and UTC-5 in winter. Sydney, which is in the Southern Hemisphere, observes daylight saving time roughly from October to April." },
      { type: "table", head: ["Session", "Winter (Tehran time)", "Summer (Tehran time)"], rows: [
        ["Sydney", "23:30 to 08:30", "00:30 to 09:30"],
        ["Tokyo", "03:30 to 12:30", "03:30 to 12:30"],
        ["London", "11:30 to 20:00", "10:30 to 19:00"],
        ["New York", "16:30 to 01:30", "15:30 to 00:30"],
        ["London and New York overlap", "16:30 to 20:00", "15:30 to 19:00"],
      ] },
      { type: "p", text: "“Winter” and “summer” in the table refer to the winter and summer time of Europe and America, not to the seasons in Iran. Tokyo does not observe daylight saving time and is always the same." },
      { type: "tip", title: "Do not forget the transition weeks", text: "The US and Europe do not change their clocks on the same date. During a few weeks in spring and autumn, the gap between London and New York differs from its usual value by one hour, which temporarily shifts the overlap. During those weeks, check a live clock instead of the table." },
      { type: "h2", text: "Why is the London and New York overlap the most important window?" },
      { type: "p", text: "During the hours when Europe and America are both active, the largest share of daily forex trading volume takes place. More liquidity usually means tighter spreads and smoother price movement. That is why many traders do their main trading in this window. In Tehran time, this window lasts about 3.5 hours: from 16:30 to 20:00 in winter and from 15:30 to 19:00 in summer." },
      { type: "h2", text: "The best trading hours for each currency pair" },
      { type: "p", text: "The general rule is simple: trade a pair during the session in which its currencies are most active." },
      { type: "ul", items: [
        "EURUSD and GBPUSD: the London session and the London and New York overlap.",
        "USDJPY and other yen pairs: the Tokyo session and the start of London, and also New York for dollar news.",
        "AUDUSD and NZDUSD: the Sydney and Tokyo sessions, along with Australian and New Zealand news.",
        "Gold (XAUUSD): the largest moves usually happen in London and New York, because gold is sensitive to the dollar and US news.",
      ] },
      { type: "h2", text: "Trading hours for an Iranian trader who works a day job" },
      { type: "p", text: "Most Iranian traders trade alongside their main job. If you are at work during the day, the New York session and the second half of the London and New York overlap, which falls in the evening and at night in Tehran time, are usually easier to reach. If you have time in the mornings, the Tokyo session and the start of London are good options. What matters most is choosing a fixed time window and trading in that same window every time, so that your journal lets you compare results by hour." },
      { type: "ol", items: [
        "Identify your free hours each day.",
        "Check which session or overlap those hours match.",
        "Choose the currency pairs that are active in that session.",
        "For a few weeks, trade only within that window and record the results in your journal by hour.",
        "After several dozen trades, choose the better window for yourself based on data, not guesses.",
      ] },
      { type: "h2", text: "When is the forex market completely closed?" },
      { type: "p", text: "The weekend closure begins at 17:00 on Friday New York time and lasts until 17:00 on Sunday New York time. In Tehran time, this closure runs from roughly early Saturday morning (around 00:30 in summer and 01:30 in winter) until the same time early Monday morning. Your broker announces the exact closing time. Note that a broker’s server time is often different from Tehran time, so keep that in mind." },
      { type: "h2", text: "Common mistakes about sessions" },
      { type: "ul", items: [
        "Assuming session times stay the same all year.",
        "Trading a pair that is inactive during a low-volume session, and then complaining about spreads and aimless moves.",
        "Confusing the broker’s server time with Tehran time.",
        "Trading right at the moment a session opens or closes without noticing that spreads usually widen at exactly that time.",
      ] },
      { type: "h2", text: "A sample trading day in Tehran time" },
      { type: "p", text: "Suppose it is winter and you want to work on EURUSD. Early in the night the market starts with Sydney and Tokyo, and price usually moves within a narrow range. Around 11:30, as London opens, volume rises and the first serious moves appear. From 16:30, when New York joins, the overlap begins and US news is released at the same time. After 20:00, with London closing, liquidity drops and moves tend to be slower or more directionless." },
      { type: "p", text: "This is only a general pattern, not a rule. On major news days, or in low-volume months such as late December and the summer holiday months, market behavior can be very different from this pattern." },
      { type: "h2", text: "Spreads and sessions" },
      { type: "p", text: "The spread (the gap between the buy and sell price) is a direct cost of every trade, and it is not constant throughout the day. It is usually lower during the London and New York overlap and higher during low-liquidity hours, such as the gap between New York closing and Sydney opening. If your strategy uses a short stop loss (as scalping does), a high spread can eat a large part of that stop. So choosing your hours is not only about volatility; it is also about cost." },
      { type: "tip", title: "Record the hour in your journal", text: "For every trade, record the entry time in Tehran time or in UTC. After a few dozen trades you will see which session your results are best in. This personal answer is more reliable than any general table." },
      { type: "h2", text: "Arion forex hours" },
      { type: "p", text: "Arion shows whether each of the four sessions is open or closed in your local time, with a countdown to the next opening or closing. The calculation uses the real time zone of each city and its daylight saving time, rather than a fixed number that is only correct for half the year." },
      { type: "cta", text: "See which session is open right now and how much time is left until the next one.", href: "/forex-sessions", label: "Forex market hours" },
      { type: "p", text: "Major economic news is also usually released during the London and New York sessions. Before trading, always check the economic calendar for that day." },
      { type: "cta", text: "Check the high-impact events for today before you enter a trade.", href: "/economic-calendar", label: "Forex economic calendar" },
      { type: "p", text: "This is educational content only. Trading in financial markets carries risk, and you may lose part or all of your capital. This article is for education only and is not financial or investment advice." },
    ],
    faq: [
      { q: "What is the best time to trade forex in Iran time?", a: "For most major currency pairs, the London and New York overlap is the most liquid window. In Tehran time that is roughly 16:30 to 20:00 in winter and 15:30 to 19:00 in summer. However, the best hours for each person depend on their currency pair and strategy." },
      { q: "What time is the London session in Tehran time?", a: "Assuming 08:00 to 16:30 London time, the London session runs from 11:30 to 20:00 Tehran time in winter and from 10:30 to 19:00 in summer. The difference comes from British summer time, since Iran does not observe daylight saving time." },
      { q: "Does Iran observe daylight saving time, and does it affect forex hours?", a: "Iran has not observed daylight saving time since 1401 and stays on UTC+3:30 all year. But London and New York do observe it, so the time difference between Tehran and those cities changes by one hour between summer and winter, and session times in Tehran shift accordingly." },
      { q: "What time does the forex market close on the weekend?", a: "The market is closed from 17:00 on Friday New York time until 17:00 on Sunday New York time. The exact time in Tehran shifts with US daylight saving time, and the precise timing differs slightly between brokers." },
      { q: "Do I have to trade during the London and New York overlap?", a: "No. The overlap has more liquidity but also more volatility and risk. Some strategies work better during the calmer Tokyo session. Find the hours that suit you using your journal and your own data." },
    ],
    related: [
      { href: "/forex-sessions", label: "Forex market hours" },
      { href: "/blog/what-is-an-economic-calendar", label: "What is an economic calendar?" },
      { href: "/blog/what-is-a-trading-journal", label: "What is a trading journal?" },
      { href: "/economic-calendar", label: "Forex economic calendar" },
    ],
  },
  "what-is-an-economic-calendar": {
    title: "What Is an Economic Calendar and How Do You Use It?",
    metaTitle: "What Is an Economic Calendar? A Guide to Using It in Forex",
    description:
      "What a forex economic calendar is, what Actual, Forecast, and Previous mean, which events move the market, and how to use the calendar before you trade.",
    keywords: ["economic calendar", "forex economic calendar", "forex news", "how to read an economic calendar", "important forex news", "non-farm payrolls", "trading around news"],
    excerpt: "What an economic calendar shows and how to use it during a trading day.",
    takeaways: [
      "An economic calendar shows in advance when indicators and economic decisions are released; many sudden moves happen at exactly these moments.",
      "The market reacts more to the gap between Actual and Forecast than to the number itself.",
      "High-impact events such as interest rate decisions, inflation, and US employment should be checked every day.",
      "Reduce size or stay out near major news; spreads and price slippage rise at the moment of release.",
    ],
    blocks: [
      { type: "p", text: "Many sudden moves in forex are not accidental. They happen at the exact minute an economic data point is released on a schedule announced in advance. The economic calendar is where you can see the exact timing of these events beforehand. A trader who does not check the calendar may be in the market with heavy volume at the moment the US employment report is released, and only realize it when a long candle has already hit their stop loss." },
      { type: "p", text: "In this guide you will learn what an economic calendar is, how to read its columns, which events matter most, and what behavior makes more sense before and after a release." },
      { type: "h2", text: "What is an economic calendar?" },
      { type: "p", text: "An economic calendar is a list of scheduled economic events in different countries: central bank decisions, inflation figures, employment, gross domestic product, retail sales, and dozens of other indicators. For each event, it shows the release time, the related country or currency, the level of importance, and the forecast, previous, and actual values." },
      { type: "h2", text: "How do you read the calendar columns?" },
      { type: "ul", items: [
        "Forecast: the figure that analysts estimated before the release.",
        "Previous: the value of the same indicator in the previous period.",
        "Actual: the figure officially announced at the moment of release.",
        "Impact: a low, medium, or high label showing how likely the event is to move the market.",
      ] },
      { type: "p", text: "The key point is that the market usually reacts to the gap between Actual and Forecast, not to the Actual figure itself. A figure that is “good” but exactly matches the forecast sometimes causes little movement; a figure that is far from the forecast can cause a sharp swing. A simple example: if a country’s inflation forecast is 3.0 percent and the actual figure is announced at 3.4 percent, the market may buy that country’s currency in anticipation of higher interest rates. The reverse would apply if the figure came in at 2.6 percent." },
      { type: "tip", title: "The direction of the reaction is not certain", text: "Even when Actual is better than Forecast, the price can still move the other way, because the market may already have priced it in. The calendar tells you when the risk is high, not which direction to take." },
      { type: "h2", text: "Which events are the most important?" },
      { type: "table", head: ["Event", "Affected currency", "Why it matters"], rows: [
        ["Central bank interest rate decision (such as the Federal Reserve, ECB, or Bank of England)", "US dollar, euro, pound, and others", "Interest rates are one of the main drivers of a currency’s appeal"],
        ["Inflation rate (CPI)", "Relevant country’s currency", "Inflation directly affects expectations for the central bank’s next decision"],
        ["US non-farm payrolls (NFP)", "US dollar and most currency pairs", "Usually released on the first Friday of the month and causes sharp moves"],
        ["Gross domestic product (GDP)", "Relevant country’s currency", "A broad picture of economic growth"],
        ["Speech and press conference by a central bank head", "Relevant currency", "The tone of the speech can change expectations for interest rates"],
        ["Retail sales and purchasing managers’ index (PMI)", "Relevant country’s currency", "A sign of the health of the economy and of consumption"],
      ] },
      { type: "p", text: "The dates and times of these events change every month, so never assume them from memory. Check the calendar for the current day every day." },
      { type: "h2", text: "What should you do before every trade?" },
      { type: "ol", items: [
        "Open today’s calendar and filter for high-impact events only.",
        "Check which currencies are involved and whether the pair you want to trade is linked to them.",
        "Convert the release time to Tehran time and look at it alongside the session hours.",
        "Decide: avoid entering new trades in the half hour to one hour before the news, or reduce your size, or close the open position, or secure your stop loss.",
        "After the news, wait a few minutes for spreads to return to normal and for the initial volatility to settle.",
      ] },
      { type: "h2", text: "Risks of trading around news" },
      { type: "p", text: "At the moment a major news item is released, three things can happen. The spread can suddenly multiply. The price can jump from one level to another without any trades in between (a gap). And a trade can be filled at a price far from your stop loss (slippage). In other words, the risk you calculated using a normal stop loss can become larger in practice. This is why many traders stay out of the market in the minutes around major releases." },
      { type: "h3", text: "Should you trade the news?" },
      { type: "p", text: "News trading is a style that only makes sense with clear rules, fast execution, and low risk. Beginners are usually better off avoiding it and using the calendar mainly to avoid unwanted risk, rather than to hunt volatility." },
      { type: "h2", text: "The economic calendar and session hours" },
      { type: "p", text: "Most of the major dollar and euro events are released during the London or New York session, which is when liquidity is high. However, the release time in Tehran time shifts by an hour when the countries’ daylight saving time changes. A good calendar shows the time directly in your local time zone, so you do not have to convert it yourself." },
      { type: "h2", text: "Why does the calendar source need to be up to date?" },
      { type: "p", text: "A calendar that is updated late or only includes some of the events is worse than having no calendar at all, because it gives you a false sense of security. Seeing the actual figure is also important: a calendar that does not fill in the Actual value after the release is of little use for review and journaling." },
      { type: "h2", text: "An example of a news day" },
      { type: "p", text: "Suppose the US employment report is released at 16:30 Tehran time today, and you want to trade EURUSD. The calendar shows a forecast of 180,000 jobs and a previous figure of 150,000. There are several scenarios. If the actual figure comes in far above the forecast, the dollar usually strengthens and EURUSD falls. If it comes in far below, the reverse usually happens. If it lands close to the forecast, the initial move may be short and then reverse. In all three cases, spreads and volatility are unusual for a few minutes before and after the release." },
      { type: "p", text: "A simple plan is this: thirty minutes before the release, you do not open new trades. You either close any open trade or reduce its risk, and then you wait until the initial candles have passed and the price structure is clear." },
      { type: "h2", text: "Common mistakes when using the calendar" },
      { type: "ul", items: [
        "Not checking the calendar and being caught off guard by a sudden move in the middle of a trade.",
        "Not converting the news time to Tehran time, or confusing it with the broker’s server time.",
        "Assuming that an Actual figure better than the Forecast automatically means the currency will rise. The market sometimes reacts the other way.",
        "Paying attention to every event instead of only those linked to your currency pair and with high impact. The calendar becomes crowded and the important events get lost.",
        "Ignoring speeches and press conferences that appear in the calendar without a numeric value.",
      ] },
      { type: "h2", text: "Economic calendar in Arion" },
      { type: "p", text: "Arion shows events with Persian (Solar Hijri) dates, lets you filter them by currency and impact level, and sends reminders before each event is released. A history of past events is also available, so you can see how the market reacted last time." },
      { type: "cta", text: "See today’s high-impact events, filtered by currency and impact.", href: "/economic-calendar", label: "Forex economic calendar" },
      { type: "p", text: "If you trade daily, recording in your journal whether a trade was opened close to a news release can reveal a hidden pattern in your losses." },
      { type: "cta", text: "Note in your trading journal whether a trade was near a news release, and compare later.", href: "/trading-journal", label: "Trading journal" },
      { type: "p", text: "This is educational content only. Trading in financial markets carries risk, and you may lose part or all of your capital. This article is for education only and is not financial or investment advice." },
    ],
    faq: [
      { q: "What is an economic calendar?", a: "An economic calendar is a list of scheduled economic events and indicators, such as interest rates, inflation, and employment data. It shows the release time, country, level of importance, and the forecast, previous, and actual values for each. Traders use it to know when volatility is likely to be high." },
      { q: "What do Actual, Forecast, and Previous mean?", a: "Forecast is analysts’ estimate, Previous is the value from the previous period, and Actual is the official figure announced at the moment of release. The market usually reacts to the gap between Actual and Forecast, not to the figure itself." },
      { q: "What are the most important forex news events?", a: "Central bank interest rate decisions, inflation data (CPI), US non-farm payrolls (NFP), gross domestic product, and speeches by central bank heads. These events usually carry a high-impact label." },
      { q: "Should I trade during a news release?", a: "For most beginners, it is better not to open new trades in the minutes around major news. Spreads and price slippage rise, and a stop loss may be filled at a price you did not expect. News trading only makes sense with clear rules and low risk." },
      { q: "What time is forex news released in Tehran time?", a: "Each release has its own time. Because London and New York observe daylight saving time and Iran does not, the Tehran time of a release can shift by up to one hour between summer and winter. It is best to use a calendar that shows the time directly in your local time zone." },
    ],
    related: [
      { href: "/economic-calendar", label: "Forex economic calendar" },
      { href: "/blog/forex-sessions-best-trading-hours-iran-time", label: "Forex sessions and the best trading hours" },
      { href: "/blog/forex-money-management", label: "Money management in forex" },
      { href: "/forex-sessions", label: "Forex market hours" },
    ],
  },
  "forex-lot-size-calculation": {
    title: "Lot Size Calculation in Forex: Formula and Examples for EURUSD, Yen Pairs, and Gold",
    metaTitle: "Forex Lot Size Calculation: Formula and Examples",
    description:
      "How to calculate forex lot size with a simple formula: risk amount divided by stop loss in pips multiplied by the pip value. Numerical examples for EURUSD, yen pairs, and gold.",
    keywords: ["lot size calculation", "forex lot size", "lot size formula", "pip value", "gold trade size", "lot size calculator", "pip calculation"],
    excerpt: "The formula for calculating lot size from risk percentage and stop loss, with numerical examples for EURUSD, USDJPY, and gold.",
    takeaways: [
      "Basic formula: lot size = risk amount divided by (stop loss in pips multiplied by the pip value for one lot).",
      "Size should be set by your risk, not by feel or by a desired profit.",
      "The pip value for EURUSD is about 10 dollars per lot, but it differs for yen pairs and gold.",
      "The definition of a pip or point for gold differs between brokers; always check your broker’s contract specifications.",
      "Round the result down so your actual risk never exceeds your planned risk.",
    ],
    blocks: [
      { type: "p", text: "One of the biggest mistakes beginner forex traders make is setting trade size by feel: “This time I will trade 0.5 lots because I am sure.” Size should be the result of a calculation, not a feeling. The correct size comes from two numbers: how much money you are willing to lose on this trade, and how far your stop loss is from your entry price. In this article you will see the formula step by step, and then calculate it with real examples for EURUSD, a yen pair, and gold." },
      { type: "h2", text: "What are a lot, a pip, and a pip value?" },
      { type: "ul", items: [
        "Lot: the unit of trade size. A standard lot in forex is usually 100,000 units of the base currency. A 0.1 lot (mini) equals 10,000 units, and a 0.01 lot (micro) equals 1,000 units.",
        "Pip: the smallest standard price movement. For most currency pairs it is 0.0001, and for yen pairs it is 0.01.",
        "Pip value: the amount of money one pip of price movement gains or loses for you on one lot.",
      ] },
      { type: "p", text: "For pairs where the quote currency is the dollar (such as EURUSD and GBPUSD) and your account is in dollars, the pip value for one lot is about 10 dollars: 100,000 multiplied by 0.0001 equals 10 dollars." },
      { type: "h2", text: "The lot size formula" },
      { type: "p", text: "The main formula is:" },
      { type: "p", text: "Lot size = risk amount divided by (stop loss in pips multiplied by the pip value for one lot)" },
      { type: "p", text: "The risk amount comes from multiplying your account balance by your risk percentage. For example, with a balance of 5,000 dollars and 1 percent risk, the risk amount is 50 dollars." },
      { type: "ol", items: [
        "Set your risk percentage (for example, 1 percent) and calculate the risk amount.",
        "Set your stop loss based on the chart, not on a size you have already chosen, and count its distance from your entry price in pips.",
        "Find the pip value for one lot of that currency pair.",
        "Solve the formula and round the result down to two decimal places.",
        "Check that your possible loss, after rounding, does not exceed the risk amount.",
      ] },
      { type: "tip", title: "Stop loss first, then size", text: "Take your stop loss from the chart, then set the size to match it. If you do it the other way around and pick the size first, you will end up placing your stop where the chart gives no reason for it." },
      { type: "h2", text: "Example 1: EURUSD" },
      { type: "p", text: "Balance 5,000 dollars, risk 1 percent (50 dollars), stop loss 25 pips, and a pip value of 10 dollars per lot:" },
      { type: "p", text: "Size = 50 divided by (25 × 10) = 50 divided by 250 = 0.20 lots." },
      { type: "p", text: "If the stop loss were 40 pips, the size would be 50 divided by 400, which is 0.125. Platforms usually use a 0.01 step, so we round down: 0.12 lots, and the actual risk is about 48 dollars. Note that a larger stop loss means a smaller size; the risk stays the same." },
      { type: "h2", text: "Example 2: a yen pair (USDJPY)" },
      { type: "p", text: "On yen pairs, the pip is 0.01 and profits and losses are recorded in yen. So you have to convert the pip value into dollars. For one lot, each pip equals 100,000 × 0.01, which is 1,000 yen. If USDJPY is at 150, the pip value is about 1,000 divided by 150, which is 6.67 dollars." },
      { type: "p", text: "Balance 3,000 dollars, risk 1 percent (30 dollars), and a stop loss of 30 pips:" },
      { type: "p", text: "Size = 30 divided by (30 × 6.67) = 30 divided by 200 = 0.15 lots." },
      { type: "p", text: "Remember that the pip value changes with the current price of the currency pair. The higher USDJPY goes, the lower the dollar value of each pip becomes." },
      { type: "h2", text: "Example 3: gold (XAUUSD)" },
      { type: "p", text: "Gold has a different table, and this is where most mistakes happen. At most brokers, one lot of the gold contract is 100 ounces. This means that if the gold price moves by one dollar, one lot gains or loses 100 dollars. This is a more reliable rule than pips." },
      { type: "p", text: "However, there is no single standard for how big a “pip” of gold is. Some brokers and tools count a gold pip as 0.1 dollars (so 10 dollars per lot), and some call a 0.01 move a point (which is 1 dollar per lot). For this reason, it is better to state your gold stop loss directly as a dollar price movement." },
      { type: "p", text: "Balance 10,000 dollars, risk 1 percent (100 dollars), and a stop loss of 5 dollars of price movement:" },
      { type: "p", text: "Loss per lot = 5 × 100 = 500 dollars. Size = 100 divided by 500 = 0.20 lots." },
      { type: "p", text: "In terms of a 0.1-dollar pip, the same stop loss is 50 pips, and 100 divided by (50 × 10) still gives 0.20. Both methods give the same answer, as long as you confirm the definition with your broker." },
      { type: "tip", title: "Check your broker’s contract specification", text: "The contract size, the number of decimal places in the price, and the definition of a pip or point are listed in the specification of each symbol on your broker’s platform. The contract size for gold, silver, and indices is not the same across brokers." },
      { type: "h2", text: "Reference table: pip value for one lot" },
      { type: "table", head: ["Symbol", "Pip size", "Approximate value per pip (dollar account)"], rows: [
        ["EURUSD, GBPUSD, AUDUSD", "0.0001", "10 dollars"],
        ["USDJPY (at a price of 150)", "0.01", "About 6.67 dollars (1,000 yen divided by the price)"],
        ["USDCHF and USDCAD", "0.0001", "10 units of the second currency divided by the price"],
        ["XAUUSD (100-ounce contract)", "0.1 dollars (common definition)", "10 dollars; each 1 dollar of movement equals 100 dollars"],
      ] },
      { type: "p", text: "The figures in this table are approximate and change with the current price and account type. For a real trade, confirm the pip value with your platform or your broker’s calculation tool as well." },
      { type: "h2", text: "Common mistakes in calculating size" },
      { type: "ul", items: [
        "Mixing up pips and points. Many brokers show prices with an extra decimal place (a pipette), so a “point” is one tenth of a pip.",
        "Forgetting the spread. Your stop loss should be set with the spread and commission in mind, because the simple formula does not account for them.",
        "Rounding up. Rounding up makes the risk larger than the planned amount.",
        "Using an old balance. You should always use your current balance.",
        "Moving the stop loss after entry without changing the size. If you move the stop further away, your risk goes up.",
      ] },
      { type: "h2", text: "How do lot size and leverage relate?" },
      { type: "p", text: "Leverage determines how much margin is needed to open a position, but it does not determine the risk of a trade. Only size and the distance of the stop loss create risk. An account with 1:500 leverage that opens 0.1 lots with a short stop loss carries less risk than an account with 1:30 leverage that opens 1 lot with a distant stop loss. So high leverage only allows you to open larger positions; it does not mean you should." },
      { type: "h2", text: "What if the account is small?" },
      { type: "p", text: "With a small balance, the formula may give a size below 0.01 lots. For example, a balance of 200 dollars with 1 percent risk means 2 dollars. With a 25-pip stop loss on EURUSD, the size would be 2 divided by 250, which is 0.008 lots, below the minimum allowed size. In this case you can either tighten your stop loss (if the chart structure allows it), knowingly accept a risk above your plan, or use accounts that offer smaller sizes. Never remove your stop loss just to reach the minimum size." },
      { type: "h2", text: "A quick practice table" },
      { type: "table", head: ["Balance", "Risk", "Stop loss on EURUSD", "Size"], rows: [
        ["1,000 dollars", "1 percent (10 dollars)", "20 pips", "0.05 lots"],
        ["2,500 dollars", "1 percent (25 dollars)", "25 pips", "0.10 lots"],
        ["5,000 dollars", "2 percent (100 dollars)", "50 pips", "0.20 lots"],
        ["10,000 dollars", "0.5 percent (50 dollars)", "10 pips", "0.50 lots"],
      ] },
      { type: "p", text: "You can check any row with the formula. For example, the first row is 10 divided by (20 × 10), which equals 0.05." },
      { type: "h2", text: "Arion lot size calculator" },
      { type: "p", text: "So that you do not have to solve the formula by hand every time, Arion includes a free lot size calculator. You enter your balance, risk percentage, symbol, and stop loss, and it gives you a suggested size. The result is rounded down in 0.01 steps so that your actual risk never exceeds the risk you asked for. Commission, spread, and swap are not included in the calculation." },
      { type: "cta", text: "Calculate lot size from your risk percentage and stop loss. Free, with no sign-up required.", href: "/tools/lot-size-calculator", label: "Lot size calculator" },
      { type: "p", text: "After calculating your size, recording the risk of each trade in your journal helps you see whether you actually followed your risk rule." },
      { type: "cta", text: "Record the risk and result of every trade in your journal.", href: "/trading-journal", label: "Trading journal" },
      { type: "p", text: "This is educational content only. Trading in financial markets carries risk, and you may lose part or all of your capital. This article is for education only and is not financial or investment advice." },
    ],
    faq: [
      { q: "What is the formula for forex lot size?", a: "Lot size equals the risk amount divided by the stop loss in pips multiplied by the pip value for one lot. The risk amount comes from multiplying your balance by your risk percentage. For example, 50 dollars of risk, a 25-pip stop loss, and a pip value of 10 dollars give a size of 0.20 lots." },
      { q: "What is the pip value for EURUSD?", a: "For one standard lot (100,000 units) and a dollar account, the pip value for EURUSD is about 10 dollars. For 0.1 lots it is about 1 dollar, and for 0.01 lots about 0.10 dollars." },
      { q: "How is gold lot size calculated?", a: "At most brokers, one gold lot is 100 ounces, so every 1 dollar of price movement gains or loses 100 dollars per lot. Set your stop loss in dollars, multiply it by 100, and divide your risk amount by that result. The definition of a gold pip differs between brokers." },
      { q: "Why does the pip value differ for yen pairs?", a: "Because the pip on yen pairs is 0.01 and profits and losses are recorded in yen. To convert to dollars, you divide 1,000 yen (the pip value of one lot) by the price of the pair. As the price changes, the dollar value of the pip changes too." },
      { q: "What percentage of my balance should I risk on each trade?", a: "Many traders risk between 0.5 and 2 percent of their balance per trade, and beginners often prefer the lower end. The right figure depends on your strategy and your tolerance for drawdowns. This is not financial advice." },
    ],
    related: [
      { href: "/tools/lot-size-calculator", label: "Lot size calculator" },
      { href: "/blog/forex-money-management", label: "Money management in forex" },
      { href: "/blog/risk-reward-ratio", label: "What is the risk-to-reward ratio?" },
      { href: "/trading-journal", label: "Arion trading journal" },
    ],
  },
  "forex-money-management": {
    title: "Money Management in Forex: The 1 to 2 Percent Rule and Daily Loss Limits",
    metaTitle: "Money Management in Forex: The 1 to 2 Percent Rule",
    description:
      "Money management in forex means controlling the risk of every trade and every day. Learn the 1 to 2 percent rule, daily loss limits, the drawdown recovery table, and position sizing.",
    keywords: ["money management in forex", "2 percent rule", "forex risk management", "daily loss limit", "drawdown", "position size", "trading money management"],
    excerpt: "The 1 to 2 percent rule, daily loss limits, and the drawdown recovery table: the foundation of staying in the game.",
    takeaways: [
      "Money management means deciding in advance the maximum you will risk on each trade and each day.",
      "A common rule is to risk between 0.5 and 2 percent of your balance on each trade.",
      "Drawdowns are asymmetric: to recover a 50 percent loss you need a 100 percent gain.",
      "A daily loss cap prevents emotional decisions after a run of losses.",
      "Calculate trade size from your stop loss and risk percentage, not from feel.",
    ],
    blocks: [
      { type: "p", text: "Any trader who has stayed in the market for several years will confirm one thing: losing traders usually do not leave the market because of a bad strategy. They leave because of excessive risk. Even a good strategy goes through losing streaks, and if you lose a large part of your capital during those streaks, there is no way to keep profiting from the strategy. Money management means building rules that keep you in the market." },
      { type: "h2", text: "What exactly is money management?" },
      { type: "p", text: "Money management is the set of rules that determines how much you risk on each trade, the maximum loss you accept in a day or a week, and what you do after a losing period. Market analysis tells you “where to enter,” while money management tells you “with what size and how far.” These rules should be written down before you open a trade, and they should not change in the middle of a trade." },
      { type: "h2", text: "The 1 to 2 percent rule" },
      { type: "p", text: "The most common rule is that the risk of any single trade should not exceed a small fraction of your balance, usually between 0.5 and 2 percent. Risk means the amount you would lose if your stop loss is hit, not the full value of the trade. With a balance of 10,000 dollars and 1 percent risk, the maximum loss on each trade is 100 dollars." },
      { type: "p", text: "The mathematical reason is that losing streaks are unavoidable. The table below shows how much of your balance remains after 10 losing trades in a row at different risk percentages (assuming risk is taken from the current balance each time):" },
      { type: "table", head: ["Risk per trade", "Loss after 10 losses in a row", "Balance remaining from 100"], rows: [
        ["1 percent", "About 9.6 percent", "About 90.4"],
        ["2 percent", "About 18.3 percent", "About 81.7"],
        ["5 percent", "About 40.1 percent", "About 59.9"],
        ["10 percent", "About 65.1 percent", "About 34.9"],
      ] },
      { type: "p", text: "With 1 percent risk, a bad run of 10 trades is still recoverable. With 10 percent risk, the same run takes more than two thirds of the account." },
      { type: "h2", text: "Why is recovering from a loss harder than taking it?" },
      { type: "p", text: "Drawdowns are asymmetric. If you lose 50 percent of your account, you need to gain 100 percent to get back to the starting point, not 50 percent. The exact formula is: gain needed to recover = drawdown divided by (1 minus drawdown)." },
      { type: "table", head: ["Drawdown", "Gain needed to recover"], rows: [
        ["5 percent", "5.26 percent"],
        ["10 percent", "11.11 percent"],
        ["20 percent", "25 percent"],
        ["30 percent", "42.86 percent"],
        ["40 percent", "66.67 percent"],
        ["50 percent", "100 percent"],
        ["60 percent", "150 percent"],
        ["75 percent", "300 percent"],
        ["90 percent", "900 percent"],
      ] },
      { type: "p", text: "This table shows why avoiding large drawdowns is the most important task. A 20 percent drawdown recovers with a 25 percent gain; recovering from a 60 percent drawdown, which needs a 150 percent gain, is almost unrealistic." },
      { type: "h2", text: "Daily loss limit" },
      { type: "p", text: "A trader’s worst decisions are usually made after a few losses in a row: they increase size to win it back, move their stop loss, or open trades without a reason. A daily loss cap breaks this cycle. The rule is simple: if the total of losses in one day reaches a set number (for example, 2 to 3 percent of the balance, or two or three losses in a row), close the platform and do not trade until the next day." },
      { type: "ul", items: [
        "Set the cap before the day starts and write it down where you will see it.",
        "Calculate how many times your risk per trade fits into the daily cap. For example, 1 percent risk with a 3 percent cap means at most three full losses.",
        "Also set a weekly cap. After reaching it, take a break for the rest of the week and review your journal.",
        "Do not count hitting the cap as a failure; see it as a sign that your protective system is working correctly.",
      ] },
      { type: "h2", text: "How is position size determined?" },
      { type: "p", text: "Position sizing is the bridge between your risk rule and the actual trade. The common method is “fixed percentage risk”: each trade risks the same percentage of your current balance, so after a loss the risk amount automatically gets smaller, and after a gain it gets larger." },
      { type: "ol", items: [
        "Read your current balance and multiply it by your risk percentage.",
        "Set your stop loss in pips based on the chart structure.",
        "Calculate the lot size with the formula: size = risk amount divided by (stop loss in pips multiplied by pip value).",
        "Round the size down and check the possible loss once more before you enter.",
      ] },
      { type: "p", text: "Example: a balance of 8,000 dollars and 1 percent risk means 80 dollars. On EURUSD with a 20-pip stop loss, the size is 80 divided by (20 × 10), which is 0.40 lots. More detail is in the guide to calculating lot size." },
      { type: "h2", text: "Simultaneous trades and correlation" },
      { type: "p", text: "If you open two buy trades on EURUSD and GBPUSD at the same time, the two are highly correlated and in practice behave like one larger trade. The 1 percent risk on each may in effect be close to 2 percent of risk on a single idea. A cap on total simultaneous risk (for example, 2 to 3 percent across all open trades) is useful." },
      { type: "h2", text: "Common mistakes" },
      { type: "ul", items: [
        "Increasing size after a loss to recover quickly (martingale). This method destroys an account after a few losses in a row.",
        "Trading without a stop loss, or moving it further away after entry.",
        "Taking high risk because of “confidence” in a setup. Confidence does not change the probability of winning.",
        "High leverage and the belief that leverage means bigger size. Leverage is a margin tool; size and stop loss determine the risk.",
        "Not writing down the rules. A rule that exists only in your head is forgotten under pressure.",
      ] },
      { type: "tip", title: "Write the rules down and record them", text: "Make a sheet with three numbers: the risk percentage per trade, the daily loss cap, and the total risk cap. Then record in your journal whether each trade stayed within this framework. In your weekly review you will see how many times you broke the rules." },
      { type: "h2", text: "A simple money management plan" },
      { type: "p", text: "To make the rules workable, write them on a one-page sheet. A sample structure:" },
      { type: "ul", items: [
        "Risk per trade: 1 percent of current balance.",
        "Maximum simultaneous trades: two, with total open risk at most 2 percent.",
        "Daily loss cap: 3 percent; after reaching it, the platform is closed.",
        "Weekly loss cap: 6 percent; after reaching it, until next week, only journaling and review.",
        "If the drawdown from the highest balance reaches 10 percent: halve the risk per trade until stability returns.",
      ] },
      { type: "p", text: "These numbers are examples and should be adjusted to your strategy and your tolerance for losses. The main point is that they are written down in advance." },
      { type: "h2", text: "What to do after a losing period?" },
      { type: "p", text: "The natural reaction after a loss is to increase size to recover quickly, and this is exactly the worst thing to do. The recovery table above shows that returning from a large drawdown requires a large gain, and chasing a large gain means larger risk. The more logical path is to reduce risk: once the drawdown passes a certain level, make your size smaller and rebuild confidence and consistency with low-risk trades. Also review your recent trades in your journal: were the losses caused by following your plan, or by breaking it?" },
      { type: "h2", text: "Money management with Arion tools" },
      { type: "p", text: "Arion helps in two ways: a free lot size calculator that works out size from your risk, and a trading journal that shows the risk of each trade, the result in R, and the maximum drawdown." },
      { type: "cta", text: "Calculate lot size from your risk percentage and stop loss.", href: "/tools/lot-size-calculator", label: "Lot size calculator" },
      { type: "cta", text: "Track your risk, results, and drawdown in the journal.", href: "/trading-journal", label: "Trading journal" },
      { type: "p", text: "This is educational content only. Trading in financial markets carries risk, and you may lose part or all of your capital. This article is for education only and is not financial or investment advice." },
    ],
    faq: [
      { q: "What does money management in forex mean?", a: "Money management is the set of rules that determines how much you risk on each trade, the maximum you accept losing in a day, and what you do after a losing period. Its goal is to survive in the market and avoid large drawdowns, not to make quick profits." },
      { q: "What is the 2 percent rule in forex?", a: "The rule that the risk of any single trade should not exceed 2 percent of your balance. With 10,000 dollars, the maximum loss per trade is 200 dollars. Many traders prefer 1 percent or less when starting out. It is a common rule of thumb and does not guarantee any profit." },
      { q: "How large should a daily loss limit be?", a: "There is no fixed number. It is common to set the daily cap at 2 to 3 times the risk of a single trade, for example 1 percent risk with a 3 percent cap. What matters is that you set the number in advance and stop trading once you reach it." },
      { q: "How much profit do I need to recover a 50 percent loss?", a: "100 percent. The formula: gain needed = drawdown divided by (1 minus drawdown). A 20 percent loss needs a 25 percent gain, and a 10 percent loss needs an 11.11 percent gain. This is why avoiding large drawdowns matters more than recovering from them." },
      { q: "Can money management work with a small balance?", a: "Yes, but with a very small balance, the minimum lot size of 0.01 may risk more than your chosen percentage. In that case you can tighten your stop loss, use an account or broker that offers smaller sizes, or knowingly accept a risk above your plan and be aware of it." },
    ],
    related: [
      { href: "/blog/forex-lot-size-calculation", label: "Lot size calculation in forex" },
      { href: "/blog/risk-reward-ratio", label: "What is the risk-to-reward ratio?" },
      { href: "/tools/lot-size-calculator", label: "Lot size calculator" },
      { href: "/trading-journal", label: "Arion trading journal" },
    ],
  },
  "trading-checklist-before-entry": {
    title: "Entry Checklist for Trades: What to Check Before You Press Buy or Sell",
    metaTitle: "Forex Entry Checklist + Ready-to-Use Template",
    description:
      "What an entry checklist is and why it stops emotional trades. A complete example, tips for keeping it short, and how to record it in your trading journal.",
    keywords: ["trade entry checklist", "trading checklist", "trader checklist", "before entering a trade", "trading discipline", "emotional trading"],
    excerpt: "The questions an entry checklist asks, why it works, and how to keep it short and usable.",
    takeaways: [
      "An entry checklist is a set of yes-or-no questions you answer before opening a trade.",
      "Its goal is not to predict the market, but to prevent avoidable mistakes and emotional trades.",
      "The best checklist is short: between 5 and 10 questions, each of which affects the outcome.",
      "Record the checklist together with the trade result, so you can see which questions actually matter.",
    ],
    blocks: [
      { type: "p", text: "Pilots start every flight with a checklist, not because they do not know how the aircraft works, but because under pressure even the most skilled people miss simple things. Trading is the same. Most of a trader’s avoidable losses come not from a lack of knowledge but from forgetting a simple rule: you did not set a stop loss, you missed a major news release, you were not in line with the main trend, or you entered out of excitement. An entry checklist prevents exactly these." },
      { type: "h2", text: "What is an entry checklist?" },
      { type: "p", text: "An entry checklist is a short list of conditions that you must answer “yes” to before opening any trade. It is not meant to generate signals. Your strategy tells you which setup to trade; the checklist only confirms that the setup, the risk, and the market conditions match your own rules." },
      { type: "h2", text: "Why does a checklist work?" },
      { type: "ul", items: [
        "Our working memory is limited, and it becomes even more limited under emotion; a checklist takes over the job of memory.",
        "It turns decision-making from a matter of “feeling” into a yes-or-no matter.",
        "It places a short pause between impulse and action, and that pause alone sidelines many emotional entries.",
        "It produces data: if you record the checklist, you can later see whether fully completed trades perform better than incomplete ones.",
      ] },
      { type: "h2", text: "A sample entry checklist" },
      { type: "p", text: "This is only an example, and you should adjust it to your own strategy. The questions are grouped into three categories: market, setup, and risk." },
      { type: "table", head: ["Group", "Question", "Desired answer"], rows: [
        ["Market", "Does the trend on the higher timeframe support my trade?", "Yes"],
        ["Market", "Is there no high-impact news event for this pair in the next one to two hours?", "Yes"],
        ["Market", "Am I in the right session for this pair, and is the spread normal?", "Yes"],
        ["Setup", "Does the setup match exactly the written rules of my strategy?", "Yes"],
        ["Setup", "Have I seen the entry confirmation (for example, a closed candle), not just guessed?", "Yes"],
        ["Risk", "Have I set my stop loss based on the chart?", "Yes"],
        ["Risk", "Have I calculated my size from my set risk percentage?", "Yes"],
        ["Risk", "Is the risk-to-reward ratio at least the minimum I have set?", "Yes"],
        ["Risk", "Have I not yet reached my daily loss cap?", "Yes"],
        ["My state", "Is this entry not driven by revenge, fear of missing out, or fatigue?", "Yes"],
      ] },
      { type: "p", text: "Notice that every question is written so that the desired answer is “yes.” This makes evaluation simple: if even one answer is “no,” you do not enter." },
      { type: "h2", text: "How do you keep the checklist short and usable?" },
      { type: "p", text: "The biggest risk of a checklist is that it grows so long that filling it in becomes tedious, and after a few days you are just ticking boxes without thinking. These rules help:" },
      { type: "ol", items: [
        "Start with 5 to 8 questions, not 25.",
        "Each question should trace back to a real mistake you have made before. If you never answer “no” to a question, remove it.",
        "Write the questions briefly and in a measurable way: “Do I have a stop loss?” is better than “Is my risk management appropriate?”",
        "Review it once a month and add or remove a question based on your journal.",
        "Completing the checklist should not take more than one minute.",
      ] },
      { type: "tip", title: "Start with your own mistakes", text: "Read your journal and identify the three most common causes of your unnecessary losses. Turn those same three into questions on the checklist. A checklist built from your real mistakes is more effective than any ready-made template." },
      { type: "h2", text: "An incomplete checklist should not prevent you from recording a trade" },
      { type: "p", text: "A subtle point: the checklist is a tool for awareness, not a lock. If some questions were “no” and you entered anyway, do not deceive yourself; record the trade in your journal along with your honest answers. That honest record is what later shows how much those trades lost or made. A journal that only records “clean” trades gives a false picture." },
      { type: "h2", text: "A checklist for managing the trade" },
      { type: "p", text: "Beyond entry, some traders keep a short checklist for while a trade is open: are you only planning to move your stop loss to break-even? Are you exiting according to your original plan, or out of fear? The same principle applies here: keep it short and build it from real mistakes." },
      { type: "h2", text: "How do you measure whether the checklist is working?" },
      { type: "p", text: "After a few dozen trades, divide them into two groups: “full checklist” and “incomplete checklist.” Compare the average R and win rate of each group. If the full group shows no meaningful difference, the questions may not be linked to your real mistakes. If the incomplete group is clearly worse, the checklist is doing its job and the problem is your discipline." },
      { type: "h2", text: "Common mistakes when using a checklist" },
      { type: "ul", items: [
        "Ticking boxes automatically without thinking. If the answers are always “yes,” the questions are probably either not honest or too easy.",
        "Filling in the checklist after entering. A checklist only makes sense before you press the button.",
        "Building a checklist from ideals rather than real experience. Rules that have never been broken are of no use.",
        "Using the checklist to justify a trade you have already decided on. If you change “no” into “maybe,” the checklist has not done its job.",
        "Constantly changing the checklist in the middle of a bad week. Make changes during the monthly review, calmly.",
      ] },
      { type: "h2", text: "An example of the checklist’s impact" },
      { type: "p", text: "Suppose a trader sees in their journal that, out of 30 trades last month, 9 were opened without checking the economic calendar, and 7 of those closed at a loss. They add the question “Is there no high-impact news in the coming hours?” to their checklist. The following month, trades near news are almost eliminated. These numbers are only a hypothetical example, but they show the mechanism: the journal finds the repeated mistake, and the checklist prevents it from repeating." },
      { type: "h2", text: "Checklists and building habits" },
      { type: "p", text: "In the first few weeks, filling in the checklist feels like extra work. If you turn it into a fixed routine before every entry, it becomes automatic after a while: you look at the chart, open the checklist, answer, and then enter. The more consistent this sequence, the harder it is to skip. If you pressed the buy or sell button before opening the checklist, note in your journal why." },
      { type: "h2", text: "Entry checklist in Arion" },
      { type: "p", text: "In Arion’s trading journal you can build your own checklist. The checklist status at the moment each trade is recorded is saved, and it does not change if you later edit the checklist. An incomplete checklist also does not stop you from recording a trade, so your journal stays complete and honest." },
      { type: "cta", text: "Build your entry checklist and record its status with every trade.", href: "/trading-journal", label: "Arion trading journal" },
      { type: "p", text: "If your checklist includes a line for “correct size,” you can get the answer on the spot with the free lot size calculator." },
      { type: "cta", text: "Calculate your size from your risk and tick it off on the checklist.", href: "/tools/lot-size-calculator", label: "Lot size calculator" },
      { type: "p", text: "This is educational content only. Trading in financial markets carries risk, and you may lose part or all of your capital. This article is for education only and is not financial or investment advice." },
    ],
    faq: [
      { q: "What is a trade entry checklist?", a: "A list of short yes-or-no questions about the market, the setup, and the risk that you answer before opening any trade. Its purpose is to prevent avoidable mistakes such as forgetting a stop loss or entering emotionally, not to predict the market." },
      { q: "How many questions should a trading checklist have?", a: "For most traders, 5 to 10 questions is enough. A long checklist becomes tiresome and is ticked without thought. Each question should be linked to a real past mistake of your own." },
      { q: "What should I do if one of the checklist questions is “no”?", a: "The ideal rule is not to enter. If you do enter, record the trade along with your honest answers, so you can later compare the results of complete and incomplete checklists." },
      { q: "Does a checklist replace a strategy?", a: "No. The strategy tells you which setup to trade, and the checklist only checks that the setup, the risk, and the market conditions match your rules. A checklist without a strategy has no meaning." },
      { q: "How often should I update my checklist?", a: "About once a month, together with your journal review. Remove any question that is never answered “no,” and if you find a new pattern of repeated mistakes, add a question that addresses it." },
    ],
    related: [
      { href: "/trading-journal", label: "Arion trading journal" },
      { href: "/blog/what-is-a-trading-journal", label: "What is a trading journal?" },
      { href: "/blog/forex-money-management", label: "Money management in forex" },
      { href: "/blog/risk-reward-ratio", label: "What is the risk-to-reward ratio?" },
    ],
  },
  "risk-reward-ratio": {
    title: "What Is the Risk-to-Reward Ratio? Formula, Break-Even Table, and Examples",
    metaTitle: "What Is the Risk-to-Reward Ratio? Formula and Win Rate Table",
    description:
      "What the risk-to-reward ratio (R:R) is, how to calculate it, and what win rate you need to break even at each ratio. Formula, table, and numerical examples for forex traders.",
    keywords: ["risk to reward ratio", "risk reward ratio", "risk to profit", "R:R in forex", "break-even win rate", "mathematical expectancy", "what is risk reward"],
    excerpt: "What the risk-to-reward ratio is, and what win rate you need to break even at each ratio.",
    takeaways: [
      "The risk-to-reward ratio is the ratio of a trade’s potential loss to its potential gain; an R:R of 1:2 means 2 units of target profit for every 1 unit of risk.",
      "The break-even win rate equals 1 divided by (1 + R), before spread and commission.",
      "A high win rate without a suitable R:R does not make a profit, and a high R:R without a sufficient win rate does not either.",
      "The real measure is mathematical expectancy, which looks at win rate and R:R together.",
    ],
    blocks: [
      { type: "p", text: "If you ask several traders what percentage of their strategy wins, they will usually name a high number. But the win rate on its own says almost nothing. A trader with a 70 percent win rate can still lose money, and a trader with a 35 percent win rate can be profitable. The missing piece is the risk-to-reward ratio: how much you make when you win compared with how much you lose when you lose." },
      { type: "h2", text: "What is the risk-to-reward ratio?" },
      { type: "p", text: "The risk-to-reward ratio (R:R) is the ratio of a trade’s potential loss to its potential gain. The potential loss is the distance from entry to stop loss, and the potential gain is the distance from entry to take profit. If the distance to the stop loss is 20 pips and the distance to the take profit is 40 pips, the R:R is 1:2: for every 1 unit of risk, you have 2 units of target profit." },
      { type: "h3", text: "The R unit" },
      { type: "p", text: "In journaling, the initial risk of each trade is treated as one R. If you risk 50 dollars and make 150 dollars, the result is +3R. If your stop loss is hit, the result is -1R. This approach makes trades of different sizes comparable." },
      { type: "h2", text: "How is it calculated?" },
      { type: "ol", items: [
        "Calculate the distance from the entry price to the stop loss (in pips or in price).",
        "Calculate the distance from the entry price to the take profit.",
        "Divide the profit distance by the loss distance. The resulting number is R, and the ratio is written as 1:R.",
      ] },
      { type: "p", text: "Example: buying EURUSD at 1.0850, with a stop loss at 1.0830 (20 pips) and a take profit at 1.0890 (40 pips). R equals 40 divided by 20, which is 2, so the R:R is 1:2." },
      { type: "tip", title: "Include the spread", text: "The spread makes your entry slightly worse and pushes your take profit slightly further away. If your stop loss is 10 pips and the spread is 1.5 pips, your real risk is more than 10 pips, and your real R:R is lower than the figure on paper." },
      { type: "h2", text: "The relationship between win rate and R:R: a break-even table" },
      { type: "p", text: "If the profit on each win equals R times the loss on each loss, the win rate needed to break even is:" },
      { type: "p", text: "Break-even win rate = 1 divided by (1 + R)" },
      { type: "p", text: "This formula comes from simplifying “win rate × R minus loss rate equals zero.” The table below shows the exact values (without spread and commission):" },
      { type: "table", head: ["R:R", "R", "Minimum win rate to break even"], rows: [
        ["1:0.5", "0.5", "66.67 percent"],
        ["1:1", "1", "50 percent"],
        ["1:1.5", "1.5", "40 percent"],
        ["1:2", "2", "33.33 percent"],
        ["1:3", "3", "25 percent"],
        ["1:4", "4", "20 percent"],
        ["1:5", "5", "16.67 percent"],
      ] },
      { type: "p", text: "In other words, with an R:R of 1:2 you only need to win one of every three trades to avoid a net loss. With an R:R of 1:0.5, you need to win two thirds of your trades. This table shows why “a close take profit and a distant stop loss” is hard to sustain in the long run." },
      { type: "h2", text: "Mathematical expectancy: the full picture" },
      { type: "p", text: "The break-even win rate only shows zero. To know whether a system is truly profitable, you need mathematical expectancy. In units of R, the formula is:" },
      { type: "p", text: "Expectancy = (win rate × R) minus loss rate" },
      { type: "table", head: ["Win rate", "R:R", "Expectancy per trade"], rows: [
        ["70 percent", "1:0.3", "70 percent × 0.3 minus 30 percent = -0.09 R"],
        ["50 percent", "1:1", "0 R"],
        ["40 percent", "1:2", "40 percent × 2 minus 60 percent = +0.2 R"],
        ["35 percent", "1:3", "35 percent × 3 minus 65 percent = +0.4 R"],
        ["30 percent", "1:2", "30 percent × 2 minus 70 percent = -0.1 R"],
      ] },
      { type: "p", text: "An interesting point: a system with a 70 percent win rate and a weak R:R has negative expectancy, while a system with a 40 percent win rate and an R:R of 1:2 has positive expectancy. These are mathematical calculations on hypothetical inputs. In practice, you learn your real win rate and R:R only from your journal data." },
      { type: "h2", text: "What R:R is appropriate?" },
      { type: "p", text: "There is no single “correct” ratio; it depends on the strategy. Trend-following strategies usually have a lower win rate and a higher R:R. Scalping and mean-reversion strategies usually have a higher win rate and a lower R:R. What matters is that these two numbers are consistent with each other and confirmed by real journal data, not just by what you expect." },
      { type: "h3", text: "Take the R:R from the chart, not the other way around" },
      { type: "p", text: "A common mistake is choosing a desired R:R first (for example, 1:3) and then forcing the take profit far away to match it. The take profit should sit behind a logical level, such as resistance, support, or a price structure. If a setup does not offer the R:R you need, do not trade it." },
      { type: "h2", text: "Common mistakes" },
      { type: "ul", items: [
        "Looking only at R:R and forgetting that a distant take profit lowers the chance of price reaching it.",
        "Moving the stop loss after entry, which makes the real R:R worse than the original plan.",
        "Closing winning trades early and holding losing trades, so the real R:R ends up far below the planned R:R.",
        "Ignoring costs: spread, commission, and swap push the break-even win rate a little higher.",
      ] },
      { type: "h2", text: "A full example: two traders with two systems" },
      { type: "p", text: "The first trader has a system with a 60 percent win rate and an R:R of 1:0.7. Over 100 trades with a fixed risk of 1R, they win about 60 times at 0.7R (42R) and lose 40 times at 1R (-40R), for a total of +2R. This is very close to break-even, and with spread and commission it will probably turn negative. The second trader has a system with a 40 percent win rate and an R:R of 1:2. Over 100 trades, they win 40 times at 2R (80R) and lose 60 times at 1R (-60R), for a total of +20R. With 1 percent risk, this is roughly 20 percent profit on paper, before costs." },
      { type: "p", text: "These two examples are constructed, but their math is accurate. The point is that the second trader loses more than half of their trades and still comes out ahead. If they cannot emotionally handle a run of 6 or 7 losses in a row, they will not stick with the system, and this is where a journal and money management help." },
      { type: "h2", text: "Psychological tolerance for a low win rate" },
      { type: "p", text: "A high R:R usually means a lower win rate and longer losing streaks. With a 35 percent win rate, the chance of ten losing trades in a row is not small. If your risk per trade is 1 percent, those 10 losses take about 9.6 percent of the account and are recoverable; but if your risk is 5 percent, the account drops by nearly 40 percent. Therefore, your choice of R:R and risk percentage should be made together, with your own psychological tolerance in mind." },
      { type: "h2", text: "R:R in your trading journal" },
      { type: "p", text: "In the Arion journal, the stop loss and take profit of each trade are recorded, and the average R, win rate, and profit factor are calculated automatically. This lets you compare your planned R:R with your actual R:R and see how closely you actually stuck to the plan. The free risk calculator also helps you set size from a fixed risk." },
      { type: "cta", text: "Record the stop loss, take profit, and result of each trade and see your average R.", href: "/trading-journal", label: "Arion trading journal" },
      { type: "cta", text: "Calculate trade size from a fixed risk.", href: "/tools/lot-size-calculator", label: "Lot size calculator" },
      { type: "p", text: "This is educational content only. Trading in financial markets carries risk, and you may lose part or all of your capital. This article is for education only and is not financial or investment advice." },
    ],
    faq: [
      { q: "What is the risk-to-reward ratio?", a: "It is the ratio of a trade’s potential loss to its potential gain. If the distance to the stop loss is 20 pips and the distance to the take profit is 40 pips, the R:R is 1:2: for every 1 unit of risk, you have 2 units of target profit." },
      { q: "What win rate do I need to break even?", a: "The break-even win rate equals 1 divided by (1 + R). With an R:R of 1:1 you need to win 50 percent of trades, with 1:2 about 33.33 percent, and with 1:3 about 25 percent. These figures are before spread and commission." },
      { q: "Is a higher R:R always better?", a: "No. A distant take profit lowers the chance of price reaching it, and the win rate falls. You need to look at R:R and win rate together, which is the mathematical expectancy. The best ratio is the one that is positive in your own real journal data." },
      { q: "What is a reasonable minimum R:R?", a: "There is no fixed figure. Many traders set a minimum of 1:1.5 or 1:2, but strategies with a high win rate may accept a lower R:R. Determine your minimum from your own real statistics." },
      { q: "How is mathematical expectancy calculated in trading?", a: "In units of R: win rate multiplied by average win in R, minus the loss rate. For example, with a 40 percent win rate and an average win of 2R, the result is 0.4 × 2 minus 0.6, which is +0.2 R per trade. Positive expectancy needs to be confirmed over enough data." },
    ],
    related: [
      { href: "/blog/forex-money-management", label: "Money management in forex" },
      { href: "/blog/forex-lot-size-calculation", label: "Lot size calculation in forex" },
      { href: "/blog/trading-checklist-before-entry", label: "Entry checklist for trades" },
      { href: "/tools/lot-size-calculator", label: "Lot size calculator" },
    ],
  },
};
