// تولیدِ shimِ @prisma/client برای اپ موبایل از روی prisma/schema.prisma:
// enumها (مقدار + تایپ، دقیقا شکلِ کلاینتِ تولیدیِ Prisma)، تایپِ مدل‌ها
// (any — کلاینت فقط اسمشون رو می‌خواد)، و Prisma.DbNull/JsonNull/AnyNull.
// اجرا: `npm run gen:prisma-shim` — تستِ src/shims/prismaShim.test.ts تضمین
// می‌کنه فایلِ کامیت‌شده با schema هم‌گام بمونه.

/** @param {string} schema */
export function parseEnums(schema) {
  const out = [];
  const re = /^enum\s+(\w+)\s*\{([\s\S]*?)^\}/gm;
  let m;
  while ((m = re.exec(schema))) {
    const values = m[2]
      .split("\n")
      .map((l) => l.replace(/\/\/.*$/, "").trim())
      .filter((l) => l && !l.startsWith("@@"))
      .map((l) => l.split(/\s+/)[0]);
    out.push({ name: m[1], values });
  }
  return out;
}

/** @param {string} schema */
export function parseModels(schema) {
  return [...schema.matchAll(/^model\s+(\w+)\s*\{/gm)].map((m) => m[1]);
}

/** @param {string} schema */
export function generatePrismaShim(schema) {
  const enums = parseEnums(schema);
  const models = parseModels(schema);
  const lines = [
    "// GENERATED by mobile/tooling/prismaShim.mjs from prisma/schema.prisma — do not edit.",
    "// shimِ @prisma/client برای باندلِ کلاینتِ اپ موبایل (بدونِ query engine).",
    "/* eslint-disable */",
    "",
  ];
  for (const e of enums) {
    lines.push(`export const ${e.name} = {`);
    for (const v of e.values) lines.push(`  ${v}: "${v}",`);
    lines.push("} as const;");
    lines.push(`export type ${e.name} = (typeof ${e.name})[keyof typeof ${e.name}];`);
    lines.push("");
  }
  for (const m of models) lines.push(`export type ${m} = any;`);
  lines.push(
    "",
    "class NullTypeValue {",
    "  constructor(readonly _name: string) {}",
    "}",
    "",
    "export class PrismaClientKnownRequestError extends Error {",
    "  code = \"\";",
    "}",
    "",
    "export const Prisma = {",
    "  DbNull: new NullTypeValue(\"DbNull\"),",
    "  JsonNull: new NullTypeValue(\"JsonNull\"),",
    "  AnyNull: new NullTypeValue(\"AnyNull\"),",
    "  PrismaClientKnownRequestError,",
    "};",
    "",
    "export declare namespace Prisma {",
    "  type JsonValue = any;",
    "  type InputJsonValue = any;",
    "  type JsonObject = Record<string, any>;",
    "  type TransactionClient = any;",
    // تایپ‌های عمومیِ هر مدل (UncheckedCreateInput/CreateInput/UncheckedUpdateInput/
    // WhereInput/GetPayload<T>) — کدِ سرورِ وب که در باندلِ کلاینت هم import می‌شه
    // (مثلا lib/tradeServer.ts) اینا رو فقط برای type-check لازم داره، نه واقعیِ
    // runtime؛ `any` کافیه (قرارِ استفاده‌ی واقعی هیچ‌وقت به این‌جا نمی‌رسه).
    ...models.flatMap((m) => [
      `  type ${m}UncheckedCreateInput = any;`,
      `  type ${m}CreateInput = any;`,
      `  type ${m}UncheckedUpdateInput = any;`,
      `  type ${m}UpdateInput = any;`,
      `  type ${m}WhereInput = any;`,
      `  type ${m}WhereUniqueInput = any;`,
      `  type ${m}GetPayload<T> = any;`,
    ]),
    "}",
    "",
    "// delegateها طوری تایپ شده‌ن که findMany آرایه برگردونه (کدِ سرورِ وب که",
    "// فقط از راهِ import typeِ زنجیره‌ای type-check می‌شه، implicit any نده).",
    "type PrismaDelegate = ((...args: any[]) => any) & {",
    "  findMany(...args: any[]): Promise<any[]>;",
    "  [method: string]: any;",
    "};",
    "",
    "export class PrismaClient {",
    "  [key: string]: PrismaDelegate;",
    "  constructor(..._args: unknown[]) {",
    "    throw new Error(\"PrismaClient is server-only\");",
    "  }",
    "}",
    ""
  );
  return lines.join("\n");
}
