import { localizedRecord } from "@/lib/localizedRecord";
// لیبل فارسی اکشن‌های AuditLog — مشترک بین صفحه‌ی لاگ و تاریخچه‌ی کاربر
export const AUDIT_ACTION_LABELS: Record<string, string> = localizedRecord<string>({
  "user.block": ["مسدودکردن کاربر", "Block user"],
  "user.unblock": ["رفع مسدودی", "Unblock user"],
  "user.profile_update": ["ویرایش پروفایل", "Edit profile"],
  "user.module_access": ["تغییر دسترسی ماژول‌ها", "Change module access"],
  "user.soft_delete": ["حذف حساب", "Delete account"],
  "user.hard_delete": ["حذف دائمی حساب", "Permanently delete account"],
  "user.restore": ["بازگردانی حساب", "Restore account"],
  "user.sessions_revoke": ["خروج اجباری از دستگاه‌ها", "Force sign-out from devices"],
  "user.export": ["خروجی CSV کاربران", "Export users CSV"],
  "admin.grant": ["ادمین‌کردن", "Make admin"],
  "admin.update": ["تغییر دسترسی ادمین", "Change admin permissions"],
  "admin.revoke": ["گرفتن نقش ادمین", "Remove admin role"],
  "setting.ai_cost_rate": ["تغییر نرخ هزینه AI", "Change AI cost rate"],
  "setting.feature_flags": ["روشن/خاموش‌کردن قابلیت‌ها", "Turn features on/off"],
  "setting.maintenance": ["تغییر حالت اطلاع‌رسانی تعمیر", "Change maintenance notice"],
  "broadcast.create": ["ارسال پیام همگانی", "Send broadcast"],
  "broadcast.cancel": ["لغو پیام همگانی", "Cancel broadcast"],
  "setting.plan_pricing": ["تغییر قیمت پلن‌ها", "Change plan prices"],
  "setting.plan_pricing_reset": ["بازگشت قیمت پلن‌ها به پیش‌فرض", "Reset plan prices to default"],
  "chat.warning": ["اخطار چت", "Chat warning"],
  "chat.ban_72h": ["بن موقت چت", "Temporary chat ban"],
  "chat.disable_chat": ["غیرفعال‌کردن چت", "Disable chat"],
  "chat.enable_chat": ["رفع محدودیت چت", "Enable chat"],
  "mentor.verify_identity": ["بررسی احراز هویت مربی", "Verify mentor identity"],
  "mentor.verify_certificate": ["بررسی مدرک مربی", "Verify mentor certificate"],
  "mentor.suspend": ["تعلیق مربی", "Suspend mentor"],
  "mentor.unsuspend": ["رفع تعلیق مربی", "Unsuspend mentor"],
  "mentor.review_hide": ["پنهان‌کردن نظر مربی", "Hide mentor review"],
  "mentor.review_restore": ["بازگردانی نظر مربی", "Restore mentor review"],
  "mentor.report_resolve": ["رسیدگی به گزارش مربی‌ها", "Resolve mentor reports"],
  "mentor.document_view": ["مشاهده مدرک مربی", "View mentor document"],
  "chat.report_dismiss": ["رد گزارش چت", "Dismiss chat report"],
  "chat.report_delete_message": ["حذف پیام گزارش‌شده", "Delete reported message"],
  "support.reply": ["پاسخ به تیکت پشتیبانی", "Reply to support ticket"],
  "support.close": ["بستن تیکت پشتیبانی", "Close support ticket"],
  "discount_code.create": ["ساخت کد تخفیف", "Create discount code"],
  "discount_code.delete": ["حذف کد تخفیف", "Delete discount code"],
  "announcement.create": ["ساخت اطلاعیه", "Create announcement"],
  "announcement.update": ["ویرایش اطلاعیه", "Edit announcement"],
  "announcement.delete": ["حذف اطلاعیه", "Delete announcement"],
  "economic_event.create": ["افزودن رویداد اقتصادی", "Add economic event"],
  "economic_event.update": ["ویرایش رویداد اقتصادی", "Edit economic event"],
  "economic_event.delete": ["حذف رویداد اقتصادی", "Delete economic event"],
  "economic_event.sync": ["همگام‌سازی تقویم اقتصادی", "Sync economic calendar"],
  "exercise_media.upsert": ["ثبت عکس حرکت ورزشی", "Save exercise media"],
  "exercise_media.delete": ["حذف عکس حرکت ورزشی", "Delete exercise media"],
  // رمزگذاری سرتاسری گفت‌وگو — فقط رویداد، هرگز محتوا (agent D)
  "e2ee.key_create": ["فعال‌سازی رمزگذاری گفت‌وگو", "Enable chat encryption"],
  "e2ee.key_reset": ["ساخت کلید تازه‌ی گفت‌وگو", "Create new chat encryption key"],
  "e2ee.passcode_change": ["تغییر کلید رمزگذاری گفت‌وگو", "Change chat encryption key"],
  "mentor.broadcast": ["ارسال گروهی مربی", "Mentor group message"],
  "demo.seed": ["ساخت داده‌ی آزمایشی", "Create demo data"],
  "demo.clear": ["حذف داده‌ی آزمایشی", "Delete demo data"],
});

export function auditLabel(action: string) {
  return AUDIT_ACTION_LABELS[action] || action;
}
