// لیبل فارسی اکشن‌های AuditLog — مشترک بین صفحه‌ی لاگ و تاریخچه‌ی کاربر
export const AUDIT_ACTION_LABELS: Record<string, string> = {
  "user.block": "مسدودکردن کاربر",
  "user.unblock": "رفع مسدودی",
  "user.profile_update": "ویرایش پروفایل",
  "user.module_access": "تغییر دسترسی ماژول‌ها",
  "user.soft_delete": "حذف حساب",
  "user.hard_delete": "حذف دائمی حساب",
  "user.restore": "بازگردانی حساب",
  "user.sessions_revoke": "خروج اجباری از دستگاه‌ها",
  "user.export": "خروجی CSV کاربران",
  "admin.grant": "ادمین‌کردن",
  "admin.update": "تغییر دسترسی ادمین",
  "admin.revoke": "گرفتن نقش ادمین",
  "setting.ai_cost_rate": "تغییر نرخ هزینه AI",
  "setting.feature_flags": "روشن/خاموش‌کردن قابلیت‌ها",
  "setting.plan_pricing": "تغییر قیمت پلن‌ها",
  "setting.plan_pricing_reset": "بازگشت قیمت پلن‌ها به پیش‌فرض",
  "chat.warning": "اخطار چت",
  "chat.ban_72h": "بن موقت چت",
  "chat.disable_chat": "غیرفعال‌کردن چت",
  "chat.enable_chat": "رفع محدودیت چت",
  "mentor.verify_identity": "بررسی احراز هویت مربی",
  "mentor.verify_certificate": "بررسی مدرک مربی",
  "mentor.suspend": "تعلیق مربی",
  "mentor.unsuspend": "رفع تعلیق مربی",
  "mentor.review_hide": "پنهان‌کردن نظر مربی",
  "mentor.review_restore": "بازگردانی نظر مربی",
  "mentor.report_resolve": "رسیدگی به گزارش مربی‌ها",
  "mentor.document_view": "مشاهده مدرک مربی",
  "chat.report_dismiss": "رد گزارش چت",
  "chat.report_delete_message": "حذف پیام گزارش‌شده",
  "support.reply": "پاسخ به تیکت پشتیبانی",
  "support.close": "بستن تیکت پشتیبانی",
  "discount_code.create": "ساخت کد تخفیف",
  "discount_code.delete": "حذف کد تخفیف",
  "announcement.create": "ساخت اطلاعیه",
  "announcement.update": "ویرایش اطلاعیه",
  "announcement.delete": "حذف اطلاعیه",
  "economic_event.create": "افزودن رویداد اقتصادی",
  "economic_event.update": "ویرایش رویداد اقتصادی",
  "economic_event.delete": "حذف رویداد اقتصادی",
  "economic_event.sync": "همگام‌سازی تقویم اقتصادی",
  "exercise_media.upsert": "ثبت عکس حرکت ورزشی",
  "exercise_media.delete": "حذف عکس حرکت ورزشی",
  // رمزگذاری سرتاسری گفت‌وگو — فقط رویداد، هرگز محتوا (agent D)
  "e2ee.key_create": "فعال‌سازی رمزگذاری گفت‌وگو",
  "e2ee.key_reset": "ساخت کلید تازه‌ی گفت‌وگو",
  "e2ee.passcode_change": "تغییر کلید رمزگذاری گفت‌وگو",
  "mentor.broadcast": "ارسال گروهی مربی",
  "demo.seed": "ساخت داده‌ی آزمایشی",
  "demo.clear": "حذف داده‌ی آزمایشی",
};

export function auditLabel(action: string) {
  return AUDIT_ACTION_LABELS[action] || action;
}
