// نام انگلیسی غذاهای کاتالوگ داخلی (lib/foodSeed.ts) — فقط برای نمایش و جستجو.
// کلید = همون نام فارسی؛ نام فارسی ذخیره‌شده در ثبت‌های کاربر (customName) عوض نمی‌شه.
import { isEn } from "./i18n";

export const FOOD_NAME_EN: Record<string, string> = {
  "برنج پخته": "Cooked rice",
  "برنج قهوه‌ای پخته": "Cooked brown rice",
  "نان لواش": "Lavash bread",
  "نان سنگک": "Sangak bread",
  "نان بربری": "Barbari bread",
  "نان تافتون": "Taftoon bread",
  "نان باگت": "Baguette",
  "نان تست": "Toast bread",
  "نان سبوس‌دار": "Whole-grain bread",
  "ماکارونی پخته": "Cooked macaroni",
  "اسپاگتی پخته": "Cooked spaghetti",
  "رشته آش": "Ash noodles",
  "نودل پخته": "Cooked noodles",
  "جو دوسر خام": "Raw oats",
  "جو دوسر پخته (فرنی)": "Cooked oats (porridge)",
  "بلغور گندم پخته": "Cooked bulgur",
  "کینوا پخته": "Cooked quinoa",
  "ذرت پخته": "Cooked corn",
  "پاپ‌کورن ساده": "Plain popcorn",
  "کورن‌فلکس": "Corn flakes",
  "ماست کم‌چرب": "Low-fat yogurt",
  "ماست پرچرب": "Full-fat yogurt",
  "ماست یونانی": "Greek yogurt",
  "ماست موسیر": "Shallot yogurt (mast-musir)",
  "دوغ": "Doogh (yogurt drink)",
  "کشک": "Kashk",
  "پنیر لاکتیک": "Lactic cheese",
  "پنیر سفید ایرانی": "Iranian white cheese",
  "پنیر پیتزا": "Pizza cheese",
  "پنیر خامه‌ای": "Cream cheese",
  "پنیر پروسس": "Processed cheese",
  "کره حیوانی": "Butter",
  "کره گیاهی": "Margarine",
  "خامه صبحانه": "Breakfast cream",
  "شیر کم‌چرب": "Low-fat milk",
  "شیر پرچرب": "Whole milk",
  "شیر کاکائو": "Chocolate milk",
  "بستنی وانیلی": "Vanilla ice cream",
  "بستنی سنتی": "Traditional ice cream",
  "سینه مرغ گریل": "Grilled chicken breast",
  "سینه مرغ سوخاری": "Fried chicken breast",
  "ران مرغ کبابی": "Grilled chicken thigh",
  "جوجه‌کباب": "Chicken kebab (joojeh)",
  "مرغ سوخاری فست‌فودی": "Fast-food fried chicken",
  "گوشت قرمز کبابی": "Grilled red meat",
  "گوشت چرخ‌کرده کبابی": "Grilled ground meat",
  "کباب کوبیده": "Koobideh kebab",
  "جگر مرغ سرخ‌شده": "Fried chicken liver",
  "جگر گوسفندی کبابی": "Grilled lamb liver",
  "دل و قلوه کبابی": "Grilled heart and kidney",
  "ماهی سالمون گریل": "Grilled salmon",
  "ماهی قزل‌آلا کبابی": "Grilled trout",
  "ماهی تیلاپیا گریل": "Grilled tilapia",
  "ماهی کنسروی (تن)": "Canned fish (tuna)",
  "میگو گریل": "Grilled shrimp",
  "تخم‌مرغ آب‌پز": "Boiled egg",
  "تخم‌مرغ نیمرو": "Fried egg",
  "املت": "Omelette",
  "کالباس مرغ": "Chicken cold cut",
  "کالباس گوشت": "Beef cold cut",
  "سوسیس": "Sausage",
  "ژامبون": "Ham",
  "عدس پخته": "Cooked lentils",
  "نخود پخته": "Cooked chickpeas",
  "لوبیا قرمز پخته": "Cooked red beans",
  "لوبیا چیتی پخته": "Cooked pinto beans",
  "لوبیا سفید پخته": "Cooked white beans",
  "لپه پخته": "Cooked split peas",
  "ماش پخته": "Cooked mung beans",
  "سویا پخته": "Cooked soybeans",
  "موز": "Banana",
  "سیب": "Apple",
  "پرتقال": "Orange",
  "نارنگی": "Tangerine",
  "انگور": "Grapes",
  "هندوانه": "Watermelon",
  "خربزه": "Melon",
  "طالبی": "Cantaloupe",
  "گلابی": "Pear",
  "هلو": "Peach",
  "شلیل": "Nectarine",
  "آلبالو": "Sour cherry",
  "گیلاس": "Cherry",
  "انار": "Pomegranate",
  "خرما": "Dates",
  "کیوی": "Kiwi",
  "آناناس": "Pineapple",
  "انبه": "Mango",
  "توت‌فرنگی": "Strawberry",
  "زردآلو": "Apricot",
  "گریپ‌فروت": "Grapefruit",
  "لیمو ترش": "Lime",
  "لیموشیرین": "Sweet lemon",
  "نارگیل تازه": "Fresh coconut",
  "هلو کمپوتی": "Canned peaches",
  "ازگیل": "Medlar",
  "به": "Quince",
  "خیار": "Cucumber",
  "گوجه‌فرنگی": "Tomato",
  "کاهو": "Lettuce",
  "فلفل دلمه‌ای": "Bell pepper",
  "پیاز": "Onion",
  "سیر": "Garlic",
  "هویج": "Carrot",
  "کدو سبز": "Zucchini",
  "بادمجان کبابی": "Grilled eggplant",
  "اسفناج پخته": "Cooked spinach",
  "کلم بروکلی بخارپز": "Steamed broccoli",
  "کلم سفید": "White cabbage",
  "قارچ سرخ‌شده": "Fried mushrooms",
  "قارچ خام": "Raw mushrooms",
  "ذرت شیرین": "Sweet corn",
  "لوبیا سبز پخته": "Cooked green beans",
  "سیب‌زمینی پخته": "Boiled potato",
  "سیب‌زمینی سرخ‌کرده": "French fries",
  "پوره سیب‌زمینی": "Mashed potatoes",
  "چغندر پخته": "Cooked beetroot",
  "کرفس": "Celery",
  "تربچه": "Radish",
  "کدو حلوایی پخته": "Cooked pumpkin",
  "سبزیجات بخارپز": "Steamed vegetables",
  "سبزی خوردن": "Fresh herbs (sabzi khordan)",
  "ترشی مخلوط": "Mixed pickles",
  "بادام": "Almonds",
  "گردو": "Walnuts",
  "پسته": "Pistachios",
  "فندق": "Hazelnuts",
  "بادام‌زمینی خام": "Raw peanuts",
  "بادام‌زمینی برشته نمکی": "Roasted salted peanuts",
  "بادام هندی برشته": "Roasted cashews",
  "کشمش": "Raisins",
  "انجیر خشک": "Dried figs",
  "زردآلو خشک": "Dried apricots",
  "توت خشک": "Dried mulberries",
  "نارگیل خشک": "Dried coconut",
  "تخمه آفتابگردان": "Sunflower seeds",
  "تخمه هندوانه": "Watermelon seeds",
  "تخمه کدو": "Pumpkin seeds",
  "آجیل خام مخلوط": "Raw mixed nuts",
  "آجیل شور مخلوط": "Salted mixed nuts",
  "نخودچی و کشمش": "Roasted chickpeas and raisins",
  "نخود برشته": "Roasted chickpeas",
  "روغن زیتون": "Olive oil",
  "روغن آفتابگردان": "Sunflower oil",
  "روغن کنجد": "Sesame oil",
  "کره بادام‌زمینی": "Peanut butter",
  "سس مایونز": "Mayonnaise",
  "سس کچاپ": "Ketchup",
  "سس باربیکیو": "Barbecue sauce",
  "رب گوجه‌فرنگی": "Tomato paste",
  "رب انار": "Pomegranate molasses",
  "عسل": "Honey",
  "مربا": "Jam",
  "شکر": "Sugar",
  "سرکه": "Vinegar",
  "زیتون پرورده": "Marinated olives",
  "خیارشور": "Pickled cucumber",
  "سیر ترشی": "Pickled garlic",
  "چای (بدون شکر)": "Tea (no sugar)",
  "قهوه (بدون شکر)": "Coffee (no sugar)",
  "نوشابه گازدار": "Soda",
  "نوشابه رژیمی": "Diet soda",
  "آب‌میوه صنعتی": "Packaged fruit juice",
  "آب پرتقال طبیعی": "Fresh orange juice",
  "نوشیدنی انرژی‌زا": "Energy drink",
  "دلستر": "Malt beverage (Delester)",
  "شربت آبلیمو": "Lime syrup drink",
  "شربت سکنجبین": "Sekanjabin syrup drink",
  "شربت خاکشیر": "Khakshir drink",
  "شربت آلبالو": "Sour cherry syrup drink",
  "کنسرو لوبیا": "Canned beans",
  "کنسرو ذرت": "Canned corn",
  "چلوکباب کوبیده": "Chelo koobideh (rice with kebab)",
  "زرشک‌پلو با مرغ": "Barberry rice with chicken",
  "قورمه‌سبزی": "Ghormeh sabzi",
  "قیمه": "Gheymeh",
  "فسنجان": "Fesenjan",
  "کوکو سبزی": "Kuku sabzi",
  "دلمه برگ مو": "Stuffed grape leaves (dolmeh)",
  "آش رشته": "Ash reshteh",
  "دیزی": "Dizi (abgoosht)",
  "کشک بادمجان": "Kashk-e bademjan",
  "میرزا قاسمی": "Mirza ghasemi",
  "ته‌چین مرغ": "Chicken tahchin",
  "باقالی پلو با گوشت": "Dill and broad bean rice with meat",
  "عدس‌پلو": "Lentil rice",
  "لوبیا پلو": "Green bean rice",
  "خورش کرفس": "Celery stew",
  "خورش بادمجان": "Eggplant stew",
  "آبگوشت": "Abgoosht",
  "کله‌جوش": "Kalleh joosh",
  "حلیم": "Haleem",
  "کتلت": "Cutlet (katlet)",
  "شامی کباب": "Shami kebab",
  "کوفته تبریزی": "Tabrizi meatball",
  "فلافل": "Falafel",
  "ساندویچ کالباس": "Cold cut sandwich",
  "پیراشکی گوشت": "Meat piroshki",
  "پیتزا مخلوط": "Mixed pizza",
  "پیتزا مارگاریتا": "Margherita pizza",
  "پاستا آلفردو": "Fettuccine Alfredo",
  "پاستا بولونیز": "Spaghetti Bolognese",
  "سوشی (رول کالیفرنیا)": "Sushi (California roll)",
  "همبرگر گوشت": "Beef hamburger",
  "چیزبرگر": "Cheeseburger",
  "ساندویچ مرغ": "Chicken sandwich",
  "هات‌داگ": "Hot dog",
  "تاکو گوشت": "Beef taco",
  "بوریتو مرغ": "Chicken burrito",
  "پنکیک": "Pancake",
  "وافل": "Waffle",
  "کروسان": "Croissant",
  "دونات": "Donut",
  "سالاد سزار با مرغ": "Chicken Caesar salad",
  "سالاد الویه": "Olivier salad",
  "سالاد فصل": "Seasonal salad",
  "رامن مرغ": "Chicken ramen",
  "پاد تای": "Pad Thai",
  "کاری مرغ هندی": "Indian chicken curry",
  "حمص": "Hummus",
  "فلافل عربی": "Arabic falafel",
  "شاورما مرغ": "Chicken shawarma",
  "لازانیا": "Lasagna",
  "بستنی مک‌فلوری": "McFlurry ice cream",
  "سیب‌زمینی سرخ‌کرده فست‌فودی": "Fast-food french fries",
  "ناگت مرغ": "Chicken nuggets",
  "سوپ جو": "Barley soup",
  "سوپ قارچ": "Mushroom soup",
  "چیپس سیب‌زمینی": "Potato chips",
  "پفک نمکی": "Salted cheese puffs",
  "چیپس و پنیر": "Cheese chips",
  "لیز": "Lay's-style chips",
  "پسته خندان": "Open pistachios",
  "کشک و بادمجان اسنکی": "Kashk and eggplant snack",
  "بیسکویت ساده": "Plain biscuit",
  "کیک یزدی": "Yazdi cake",
  "کیک کاکائویی بسته‌بندی": "Packaged chocolate cake",
  "کیک رولت": "Swiss roll cake",
  "ویفر": "Wafer",
  "شکلات تلخ": "Dark chocolate",
  "شکلات شیری": "Milk chocolate",
  "تافی": "Toffee",
  "آدامس": "Chewing gum",
  "پاستیل": "Gummy candy",
  "مارشمالو": "Marshmallow",
  "نبات": "Rock candy (nabat)",
  "گز اصفهان": "Isfahan gaz (nougat)",
  "سوهان قم": "Qom sohan (brittle)",
  "قطاب یزد": "Yazd ghottab",
  "کلوچه فومنی": "Fooman kolooche",
  "باقلوا": "Baklava",
  "زولبیا": "Zoolbia",
  "بامیه": "Bamieh",
  "حلوا ارده": "Tahini halva",
  "حلوا شکری": "Sugar halva",
  "آب‌نبات چوبی": "Lollipop",
  "چوب شور": "Salty stick snack",
  "کراکر نمکی": "Salted crackers",
  "پفیلا": "Pofila (puffed snack)",
  "چیز بال": "Cheese balls",
  "پاپکورن کارامل": "Caramel popcorn",
  "کوکی شکلاتی": "Chocolate cookie",
  "دونات پودری": "Powdered donut",
  "کیک اسفنجی خانگی": "Homemade sponge cake",
};

/** نام غذا برای نمایش: در انگلیسی نام انگلیسی کاتالوگ (اگه بود)، وگرنه همون نام ذخیره‌شده. */
export function foodNameDisplay(nameFa: string, nameEn?: string | null): string {
  if (!isEn()) return nameFa;
  return nameEn || FOOD_NAME_EN[nameFa] || nameFa;
}

/** جستجوی انگلیسی در نام غذاها (سمت کلاینت)؛ خروجی نام‌های فارسی کلید. */
export function searchFoodNamesEn(query: string, limit = 10): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const out: string[] = [];
  for (const fa of Object.keys(FOOD_NAME_EN)) {
    if (FOOD_NAME_EN[fa].toLowerCase().includes(q)) {
      out.push(fa);
      if (out.length >= limit) break;
    }
  }
  return out;
}
